//所有项目的类型枚举
package enumType

import "fmt"

var nameToIdx map[string]int32

const(

	CharacterSexType_Male = 1 //男
	CharacterSexType_Female = 2 //女
	CharacterType_Attack = 1 //先锋
	CharacterType_Help = 2 //支援
	CharacterType_Defend = 3 //攻坚
	CharacterCampType_Varia = 1 //瓦利安
	CharacterCampType_Vongola = 2 //彭格列十代家族
	CharacterCampType_Cavallone = 3 //加百罗涅
	CharacterCampType_Rainbow = 4 //彩虹之子
	CharacterPropertyType_Empty = 1 //无
	CharacterPropertyType_Fog = 2 //雾
	CharacterPropertyType_Cloud = 3 //云
	CharacterPropertyType_Rain = 4 //雨
	CharacterPropertyType_Sunny = 5 //晴
	CharacterPropertyType_Mist = 6 //岚
	CharacterPropertyType_Thunder = 7 //雷
	CharacterPropertyType_Air = 8 //大空
	CharacterSonFunctionType_LevelUP = 1 //升级
	CharacterSonFunctionType_BreakThrough = 2 //突破
	CharacterSonFunctionType_Skill = 3 //技能
	CharacterSonFunctionType_Gene = 4 //基因
	ItemType_Item = 1 //道具
	ItemType_Fragment = 2 //碎片
	CurrencyType_Gold = 1 //金币
	CurrencyType_Diamond = 2 //钻石
	DrawCardsType_Single = 1 //单抽
	DrawCardsType_TenTimes = 2 //十连抽
	SystemEnum_Shop = 1 //商店
	IOType_Item = 1 //产出表道具大类
	IOType_UsualAttribute = 2 //产出表通用属性
	IOType_Character = 3 //产出表角色
	IOType_Equip = 4 //产出表装备
	IOType_Weapon = 5 //产出表武器
	QuestHandleType_Auto = 1 //
	QuestHandleType_Manually = 2 //
	QuestHandleType_NPC = 3 //
	QuestHandleType_Item = 4 //
	QuestHandleType_Range = 5 //
	QuestType_MainStory = 1 //
	QuestType_Daily = 2 //
	QuestType_Weekly = 3 //
	QuestType_DailyReward = 4 //
	QuestType_NewbieGift = 5 //
	QuestType_BigSecret = 6 //
	QuestType_Entrust = 7 //
	QuestConditionType_DailyLogin = 1 //
	QuestConditionType_AccumulateLogin = 2 //
	QuestConditionType_OnlineTime = 3 //
	QuestConditionType_ConsumeResource = 4 //
	QuestConditionType_YuruInteract = 5 //
	QuestConditionType_DailyActiveness = 6 //
	QuestConditionType_EnterDorm = 7 //
	QuestConditionType_ExchangeFatigue = 8 //
	QuestConditionType_PlayerLevelUp = 9 //
	QuestConditionType_AnyInstanceSucceed = 10 //
	QuestConditionType_InstanceSucceed = 11 //
	QuestConditionType_AnyMaterialInstanceSucceed = 12 //
	QuestConditionType_AnyScarsInstanceSucceed = 13 //
	QuestConditionType_AnyRoleLevelUp = 14 //
	QuestConditionType_AnyRoleBreak = 15 //
	QuestConditionType_RoleBreak = 16 //
	QuestConditionType_RoleLevelUp = 17 //
	QuestConditionType_AnyWeaponLevelUp = 18 //
	QuestConditionType_AnyWeaponBreak = 19 //
	QuestConditionType_AnyWeaponRefine = 20 //
	QuestConditionType_WeaponOwned = 21 //
	QuestConditionType_WeaponEquipped = 22 //
	QuestConditionType_AnyEquipLevelUp = 23 //
	QuestConditionType_AnyEquipRefine = 24 //
	QuestConditionType_EquipOwned = 25 //
	QuestConditionType_EquipEquipped = 26 //
	QuestConditionType_QuestComplete = 27 //
	QuestConditionType_FatigueRegen = 28 //
	QuestConditionType_AnyWorldQuestInstanceSucceed = 29 //
	QuestConditionType_AnyShopPurchase = 30 //
	QuestConditionType_BranchInstancePass = 31 //
	QuestConditionType_CharacterInstancePass = 32 //
	QuestConditionType_RoleLevel = 33 //
	QuestConditionType_RoleSkillLevelUp = 34 //
	QuestConditionType_RoleSkillLevel = 35 //
	QuestConditionType_RoleEquipCount = 36 //
	QuestConditionType_AnySecretInstanceSucceed = 37 //
	QuestConditionType_TrailCount = 38 //
	QuestConditionType_AnyTrailInstanceSucceed = 39 //
	QuestConditionType_ScarsIngrainDifficultInstanceSucceed = 40 //
	QuestConditionType_ScarsIngrainScore = 41 //
	QuestConditionType_AnyDrawcardTimes = 42 //
	QuestConditionType_WeeklyLogin = 43 //
	QuestConditionType_WeeklyActiveness = 44 //
	QuestConditionType_EquipRarityOwned = 45 //
	QuestConditionType_BigSecretPassTimes = 46 //
	QuestConditionType_BigSecretBestScore = 47 //
	QuestConditionType_WeaponRarityOwned = 48 //
	QuestEventType_AddBuff = 1 //
	ResourceConsumeType_Item = 1 //
	ResourceConsumeType_UsualAttribute = 2 //
	DungeonClearType_KillAppointMonster = 1 //
	DungeonClearType_ReachArea = 2 //
	DungeonClearType_SurviveForSeconds = 3 //
	DungeonClearType_Interact = 4 //
	DungeonClearType_SkillMonsterCount = 5 //
	DungeonClearType_PlayAnim = 6 //
	DungeonStarConditionType_DeathLimit = 1 //
	DungeonStarConditionType_PassTimeLimit = 2 //
	DungeonStarConditionType_BeHitTimesLimit = 3 //
	DungeonStarConditionType_BeHitHpLimit = 4 //
	DungeonStarConditionType_TimeRangeDamage = 5 //
	DungeonStarConditionType_TimeRangeKill = 6 //
	DungeonStarConditionType_UseUltimateTimes = 7 //
	DungeonStarConditionType_UltimateEvasionTimes = 8 //
	DungeonStarConditionType_GuardTargetHp = 9 //
	DungeonStarConditionType_GuardPassMonsterLimit = 10 //
	DungeonTeamLimitType_CharacterCountLimit = 1 //
	DungeonTeamLimitType_AppointCharacter = 2 //
	MainChapterType_Normal = 1 //普通
	MainChapterType_Difficult = 2 //困难
	MainChapterType_Hidden = 3 //隐藏
	MainChapterType_Branch = 4 //支线
	MainChapterType_Character = 5 //角色
	DropPoolType_Rand = 1 //
	DropPoolType_Fixed = 2 //
	DropType_Item = 1 //
	DropType_UsualAttribute = 2 //
	DropType_Equip = 3 //
	DropType_Pool = 4 //
	DropType_Character = 5 //
	DropType_Weapon = 6 //
	RewardType_Item = 1 //
	RewardType_Equip = 2 //
	RewardType_Weapon = 3 //
	RewardType_UsualAttribute = 4 //
	WeaponType_Sword = 1 //单手剑
	WeaponType_Gloves = 2 //拳套
	WeaponType_DoubleGun = 3 //双枪
	WeaponType_Dagger = 4 //匕首
	WeaponType_Hammer = 5 //大锤
	WeaponType_DoubleSword = 6 //双刀
	WeaponType_GreatSword = 7 //大剑
	WeaponType_Katana = 8 //太刀
	WeaponType_Spear = 9 //长枪
	WeaponType_Sickle = 10 //镰刀
	WeaponType_Amplifier = 11 //增幅器
	WeaponType_Arch = 12 //弓
	RarityType_Star1 = 1 //Star1
	RarityType_Star2 = 2 //Star2
	RarityType_Star3 = 3 //Star3
	RarityType_Star4 = 4 //Star4
	RarityType_Star5 = 5 //Star5
	RarityType_Star6 = 6 //Star6
	QualityType_C = 1 //C
	QualityType_B = 2 //B
	QualityType_A = 3 //A
	QualityType_S = 4 //S
	QualityType_SS = 5 //SS
	QualityType_SSS = 6 //SSS
	QualityType_SSSP = 7 //SSS+
	QualityType_SSSPP = 8 //SSS++
	YuruTouchTriggerType_Click = 1 //
	YuruTouchTriggerType_Standby = 2 //
	YuruTouchTriggerType_ReturnHome = 3 //
	YuruTouchTriggerType_Time = 4 //
	YuruTouchTriggerType_EnterUIType = 5 //
	YuruTouchTriggerType_ExitUIType = 6 //
	YuruTouchCheckType_TimeRange = 1 //
	YuruTouchCheckType_UI = 2 //
	YuruTouchCheckType_WeaponOn = 3 //
	DialogueType_Story = 1 //
	DialogueType_BottomTips = 2 //
	ScarsIngrainDifficultType_Experiment = 1 //稳定
	ScarsIngrainDifficultType_Elites = 2 //异常
	ScarsIngrainDifficultType_Knight = 3 //失控
	ScarsIngrainDifficultType_Chaos = 4 //暴走
	ScarsIngrainDifficultType_Hell = 5 //超限
	ScarsIngrainBossChallengeType_BeHit = 1 //受击数
	ScarsIngrainBossChallengeType_Time = 2 //时间
	DungeonCostType_FatigueCost = 1 //
	DungeonCostType_BigSecretItemCost = 2 //
	DungeonUnlockType_MainChapter = 1 //
	DungeonUnlockType_MaterialDungeon = 2 //
	DungeonUnlockType_PlayerLevel = 3 //
	DungeonUnlockType_TrialDungeon = 4 //
	DungeonSystemType_MainChapter = 1 //
	DungeonSystemType_Material = 2 //
	DungeonSystemType_ScarsIngrain = 3 //
	DungeonSystemType_WorldQuest = 4 //
	DungeonSystemType_Secret = 5 //
	DungeonSystemType_Trial = 6 //
	DungeonSystemType_Prologue = 99 //
	DungeonSystemType_BigSecret = 7 //
	ItemTimeLimitType_Duration = 1 //
	ItemTimeLimitType_Date = 2 //
	DungeonDisplayType_MainChapter = 1 //
	DungeonDisplayType_MaterialDungeon = 2 //
	DungeonDisplayType_PlayerLevel = 3 //
	ConsciousEffectType_XX = 1 //
	UIType_Yuru = 1 //看板界面
	UIType_BattleDialogue = 2 //战斗对话
	UIType_Team = 3 //编队界面
	UIType_TeammateSelect = 4 //编队选人界面
	UIType_RoleSelect = 5 //角色选择界面
	UIType_RoleLevelUp = 6 //角色升级
	UIType_SwitchYuru = 7 //选择看板娘
	UIType_RoleFavor = 8 //角色好感界面
	UIType_SafeArea = 9 //基地界面
	UIType_RoleWeapon = 10 //角色武器界面
	UIType_RoleGene = 11 //角色基因界面-常规
	UIType_DrawCardResult = 12 //抽卡结果界面
	UIType_RoleEquip = 13 //角色束流器界面
	UIType_RoleSkill = 14 //角色技能界面
	UIType_RoleGeneZoomIn = 15 //角色基因界面-放大后
	UIType_WeaponSelect = 16 //武器选择界面
	UIType_WeaponDevelop = 17 //武器培养界面
	UIType_ScarsIngrainBoss = 18 //战痕BOSS界面
	UIType_BackpackPanel = 19 //背包界面
	UIType_SettingsPanel = 20 //设置界面
	UIType_ScarsIngrain = 21 //战痕区域
	UIType_QuestPanel = 22 //任务界面
	UIType_MainDrawCard = 23 //抽卡界面
	UIType_DrawCardTargetDetail = 24 //抽卡精准目标详情界面
	UIType_CharacterChapter = 25 //角色剧情主界面
	UIType_CharacterDungeon = 26 //角色剧情子界面
	UIType_Friend = 27 //好友界面
	UIType_Shop = 28 //商店界面
	UIType_ShoppingMall = 29 //商城界面
	UIType_Mail = 30 //邮件界面
	UIType_Synthesis = 31 //合成界面
	FunctionType_WorldMap = 1 //世界地图
	FunctionType_WorldQuest = 9 //势力委托
	FunctionType_ScarsIngrain = 10 //战痕印刻
	FunctionType_Lottery = 13 //勘察
	FunctionType_Quest = 14 //任务
	FunctionType_Talk = 15 //聊天
	FunctionType_Bag = 16 //背包
	FunctionType_Shop = 17 //商店
	FunctionType_Trail = 19 //黑月探秘
	FunctionType_Secret = 20 //深渊秘境
	FunctionType_MaterialDungeon = 21 //资源副本
	FunctionType_ChanllengeDungeon = 22 //挑战副本
	FunctionType_CharacterDungeon = 23 //角色副本
	FunctionType_GrowUpQuest = 24 //成长任务
	FunctionType_DailyQuest = 25 //日常任务
	FunctionType_WeeklyQuest = 26 //周常任务
	FunctionType_Welfare = 27 //福利
	FunctionType_Recharge = 28 //商城
	FunctionType_Friend = 29 //好友
	FunctionType_TeamSetting = 30 //编队
	FunctionType_Activity = 31 //活动
	FunctionType_Mail = 32 //邮件
	FunctionType_announcement = 33 //公告
	FunctionType_DailyShop = 34 //日常商店
	FunctionType_ChallengeShop = 35 //挑战商店
	FunctionType_ScarsIngrainShop = 36 //战痕商店
	FunctionType_SecretShop = 37 //秘境商店
	FunctionType_FakeUnlock1 = 1001 //虚数之作
	FunctionType_FakeUnlock2 = 1002 //赤色峡谷
	FunctionType_FakeUnlock3 = 1003 //黑夜深渊
	FunctionType_FakeUnlock4 = 1004 //虚数之作<隐藏>
	FunctionType_FakeUnlock5 = 1005 //赤色峡谷<隐藏>
	FunctionType_FakeUnlock6 = 1006 //黑夜深渊<隐藏>
	FunctionType_FakeUnlock7 = 1007 //流星-极夜流星Ⅰ
	FunctionType_FakeUnlock8 = 1008 //卡娜-教父Ⅰ
	FunctionType_FakeUnlock9 = 1009 //花火-兔兔日记Ⅰ
	FunctionType_FakeUnlock10 = 1010 //开学计划
	FunctionUnlockType_PlayerLevel = 1 //
	FunctionUnlockType_DungeonPass = 2 //
	FunctionUnlockType_TimeRange = 3 //
	FunctionUnlockType_Default = 4 //
	FunctionUnlockType_PlayerGuide = 5 //
	DamageElementType_Fire = 1 //火
	DamageElementType_Thunder = 2 //雷
	DamageElementType_Wind = 4 //风
	DamageElementType_Source = 8 //源
	GiftType_Food = 1 //食物
	GiftType_Game = 2 //游戏
	GiftType_Movie = 3 //电影
	EquipSkillLimitType_Main = 1 //
	PlayerCharacterSkillTagType_Active = 1 //主动技能
	PlayerCharacterSkillTagType_Passive = 2 //被动技能
	PlayerCharacterSkillTagType_Damage = 3 //输出技能
	PlayerCharacterSkillTagType_Control = 4 //控制技能
	PlayerCharacterSkillTagType_Recover = 5 //回复技能
	PlayerCharacterSkillTagType_Buff = 6 //增益技能
	PlayerCampType_Camp1 = 1 //流浪者营地
	PlayerCampType_Camp2 = 2 //巴雷特家族
	PlayerCampType_Camp3 = 3 //白鹰安保
	PlayerCampType_Camp4 = 4 //生态管理局
	PlayerCampReputationLevelType_Level1 = 1 //中立
	PlayerCampReputationLevelType_Level2 = 2 //友善
	PlayerCampReputationLevelType_Level3 = 3 //亲密
	PlayerCampReputationLevelType_Level4 = 4 //尊敬
	PlayerCampReputationLevelType_Level5 = 5 //崇敬
	PlayerCampReputationLevelType_Level6 = 6 //崇拜
	WorldQuestType_KillMonster = 1 //歼灭
	WorldQuestType_KillTargetMonster = 2 //刺杀
	WorldQuestType_EscortNpcToTargetLocation = 3 //救援
	WorldQuestType_ProtectNpc = 4 //防御
	WorldQuestType_KeepAlive = 5 //生存
	WorldQuestType_Collect = 6 //收集
	WorldQuestType_ToTargetLocation = 7 //间谍
	WorldQuestType_Destroy = 8 //破坏
	ProductLimitType_Daily = 1 //每日限购
	ProductLimitType_Weekly = 2 //每周限购
	ProductLimitType_Monthly = 3 //每月限购
	ProductLimitType_Lifelong = 4 //终身限购
	ProductLimitType_Date = 5 //时间限购
	ShopType_Daily = 1 //日常商店
	ShopType_Challenge = 2 //挑战商店
	ShopType_ScarsIngrain = 3 //战痕商店
	ShopType_Secret = 4 //秘境商店
	MaterialDungeonType_Gold = 1 //寻宝大作战
	MaterialDungeonType_CharacterExp = 2 //荒原磨炼
	MaterialDungeonType_WeaponExp = 3 //废城拾遗
	MaterialDungeonType_SkillExp = 4 //秘境探索
	MaterialDungeonType_CharacterBreak = 5 //灵能界点
	MaterialDungeonType_WeaponBreak = 6 //装备测试
	MaterialDungeonType_CommonMaterial = 7 //一号任务
	SecretDifficultyType_Level1 = 1 //简单
	SecretDifficultyType_Level2 = 2 //普通
	SecretDifficultyType_Level3 = 3 //困难
	SecretDifficultyType_Level4 = 4 //噩梦
	BattleAttributeType_Base = 1 //基础属性
	BattleAttributeType_Advanced = 2 //进阶属性
	WeaponSortType_Rarity = 1 //品质顺序
	WeaponSortType_BreakLevel = 2 //突破等级顺序
	WeaponSortType_Level = 3 //等级顺序
	WeaponSortType_ID = 4 //
	WeaponSortType_WeaponType = 5 //
	WeaponSortType_RefineLevel = 6 //精炼顺序
	WeaponSortType_AcquireTime = 7 //获取时间顺序
	WeaponSortType_InsID = 8 //
	EquipType_Attack = 1 //攻击型
	EquipType_Defend = 2 //防御型
	EquipType_Help = 3 //辅助型
	VoicePlayTriggerType_GameLogo = 1 //游戏标题界面
	VoicePlayTriggerType_PlayerLogin = 2 //玩家登陆进游戏时
	VoicePlayTriggerType_RoleSelect = 3 //角色列表选中时
	VoicePlayTriggerType_RoleInTeam = 4 //角色编入队伍时
	VoicePlayTriggerType_RoleBeCaptain = 5 //角色成为队长时
	VoicePlayTriggerType_SafeAreaRoleIdle = 6 //角色安全区Idle时
	VoicePlayTriggerType_GetDailyQuestAward = 7 //获取日常奖励时
	VoicePlayTriggerType_DrawCardGetRole = 8 //抽卡抽出角色时
	VoicePlayTriggerType_BattleSkill = 9 //释放技能时
	VoicePlayTriggerType_BattleEXSkill = 10 //释放大招时
	VoicePlayTriggerType_BattleBeHitLong = 11 //受击时长语音
	VoicePlayTriggerType_BattleBeHitShort = 12 //受击时短语音
	VoicePlayTriggerType_BattleDying = 13 //濒死时
	VoicePlayTriggerType_BattleDead = 14 //死亡时
	VoicePlayTriggerType_BattleRoleIdle = 15 //战斗时角色Idle
	VoicePlayTriggerType_LevelWarning = 16 //关卡警告
	VoicePlayTriggerType_LevelSucceed = 17 //关卡成功
	VoicePlayConditionType_RoleID = 1 //角色ID
	VoicePlayConditionType_SkillName = 2 //技能名称
	MaterialType_Character = 1 //角色培养材料
	MaterialType_Skill = 2 //角色技能培养素材
	MaterialType_Weapon = 3 //角色武器培养素材
	MaterialSystemType_Synthesis  = 1 //合成系统
	MaterialSystemType_Conversion = 2 //转换系统
	AnnouncementType_System = 1 //系统公告
	AnnouncementType_Activity = 2 //活动公告
	AnnouncementContentType_OnlyImage = 1 //图片公告
	AnnouncementContentType_ImageAndText = 2 //图文公告
	SignType_Month = 1 //月度签到
	SignType_Activity = 2 //活动签到
	SignType_Beginner = 3 //新手签到
	SignType_Questionnaire = 4 //问卷签到
	WelfareType_Sign = 1 //签到类型活动
	WelfareType_Other = 2 //其他活动
	CharacterDevelopmentPanelPage_Attribute = 1 //属性
	CharacterDevelopmentPanelPage_Weapon = 2 //武器
	CharacterDevelopmentPanelPage_Skill = 3 //技能
	CharacterDevelopmentPanelPage_Equip = 4 //束流器
	CharacterDevelopmentPanelPage_Gene = 5 //灵能融合
	BigSecretMonsterGroupType_AllNormal = 1 //
	BigSecretMonsterGroupType_OneElite = 2 //
	BigSecretMonsterGroupType_AllElite = 3 //
	BigSecretMonsterGroupType_OneBoss = 4 //
	ChainSkillType_Bind = 1 //
	ChainSkillType_Sign = 2 //
	ChainSkillType_Line = 3 //
	BigSecretAffixType_Normal = 1 //
	BigSecretAffixType_Advance = 2 //
	BigSecretAffixType_Aura = 3 //
	BigSecretAffixType_Linkage = 4 //
	TalentLevelUpConditionType_PlayerLv = 1 //账号等级
)

func init() {	
	nameToIdx = map[string]int32{}
	
	nameToIdx["CharacterSexType_Male"] = 1	
	nameToIdx["CharacterSexType_Female"] = 2	
	nameToIdx["CharacterType_Attack"] = 1	
	nameToIdx["CharacterType_Help"] = 2	
	nameToIdx["CharacterType_Defend"] = 3	
	nameToIdx["CharacterCampType_Varia"] = 1	
	nameToIdx["CharacterCampType_Vongola"] = 2	
	nameToIdx["CharacterCampType_Cavallone"] = 3	
	nameToIdx["CharacterCampType_Rainbow"] = 4	
	nameToIdx["CharacterPropertyType_Empty"] = 1	
	nameToIdx["CharacterPropertyType_Fog"] = 2	
	nameToIdx["CharacterPropertyType_Cloud"] = 3	
	nameToIdx["CharacterPropertyType_Rain"] = 4	
	nameToIdx["CharacterPropertyType_Sunny"] = 5	
	nameToIdx["CharacterPropertyType_Mist"] = 6	
	nameToIdx["CharacterPropertyType_Thunder"] = 7	
	nameToIdx["CharacterPropertyType_Air"] = 8	
	nameToIdx["CharacterSonFunctionType_LevelUP"] = 1	
	nameToIdx["CharacterSonFunctionType_BreakThrough"] = 2	
	nameToIdx["CharacterSonFunctionType_Skill"] = 3	
	nameToIdx["CharacterSonFunctionType_Gene"] = 4	
	nameToIdx["ItemType_Item"] = 1	
	nameToIdx["ItemType_Fragment"] = 2	
	nameToIdx["CurrencyType_Gold"] = 1	
	nameToIdx["CurrencyType_Diamond"] = 2	
	nameToIdx["DrawCardsType_Single"] = 1	
	nameToIdx["DrawCardsType_TenTimes"] = 2	
	nameToIdx["SystemEnum_Shop"] = 1	
	nameToIdx["IOType_Item"] = 1	
	nameToIdx["IOType_UsualAttribute"] = 2	
	nameToIdx["IOType_Character"] = 3	
	nameToIdx["IOType_Equip"] = 4	
	nameToIdx["IOType_Weapon"] = 5	
	nameToIdx["QuestHandleType_Auto"] = 1	
	nameToIdx["QuestHandleType_Manually"] = 2	
	nameToIdx["QuestHandleType_NPC"] = 3	
	nameToIdx["QuestHandleType_Item"] = 4	
	nameToIdx["QuestHandleType_Range"] = 5	
	nameToIdx["QuestType_MainStory"] = 1	
	nameToIdx["QuestType_Daily"] = 2	
	nameToIdx["QuestType_Weekly"] = 3	
	nameToIdx["QuestType_DailyReward"] = 4	
	nameToIdx["QuestType_NewbieGift"] = 5	
	nameToIdx["QuestType_BigSecret"] = 6	
	nameToIdx["QuestType_Entrust"] = 7	
	nameToIdx["QuestConditionType_DailyLogin"] = 1	
	nameToIdx["QuestConditionType_AccumulateLogin"] = 2	
	nameToIdx["QuestConditionType_OnlineTime"] = 3	
	nameToIdx["QuestConditionType_ConsumeResource"] = 4	
	nameToIdx["QuestConditionType_YuruInteract"] = 5	
	nameToIdx["QuestConditionType_DailyActiveness"] = 6	
	nameToIdx["QuestConditionType_EnterDorm"] = 7	
	nameToIdx["QuestConditionType_ExchangeFatigue"] = 8	
	nameToIdx["QuestConditionType_PlayerLevelUp"] = 9	
	nameToIdx["QuestConditionType_AnyInstanceSucceed"] = 10	
	nameToIdx["QuestConditionType_InstanceSucceed"] = 11	
	nameToIdx["QuestConditionType_AnyMaterialInstanceSucceed"] = 12	
	nameToIdx["QuestConditionType_AnyScarsInstanceSucceed"] = 13	
	nameToIdx["QuestConditionType_AnyRoleLevelUp"] = 14	
	nameToIdx["QuestConditionType_AnyRoleBreak"] = 15	
	nameToIdx["QuestConditionType_RoleBreak"] = 16	
	nameToIdx["QuestConditionType_RoleLevelUp"] = 17	
	nameToIdx["QuestConditionType_AnyWeaponLevelUp"] = 18	
	nameToIdx["QuestConditionType_AnyWeaponBreak"] = 19	
	nameToIdx["QuestConditionType_AnyWeaponRefine"] = 20	
	nameToIdx["QuestConditionType_WeaponOwned"] = 21	
	nameToIdx["QuestConditionType_WeaponEquipped"] = 22	
	nameToIdx["QuestConditionType_AnyEquipLevelUp"] = 23	
	nameToIdx["QuestConditionType_AnyEquipRefine"] = 24	
	nameToIdx["QuestConditionType_EquipOwned"] = 25	
	nameToIdx["QuestConditionType_EquipEquipped"] = 26	
	nameToIdx["QuestConditionType_QuestComplete"] = 27	
	nameToIdx["QuestConditionType_FatigueRegen"] = 28	
	nameToIdx["QuestConditionType_AnyWorldQuestInstanceSucceed"] = 29	
	nameToIdx["QuestConditionType_AnyShopPurchase"] = 30	
	nameToIdx["QuestConditionType_BranchInstancePass"] = 31	
	nameToIdx["QuestConditionType_CharacterInstancePass"] = 32	
	nameToIdx["QuestConditionType_RoleLevel"] = 33	
	nameToIdx["QuestConditionType_RoleSkillLevelUp"] = 34	
	nameToIdx["QuestConditionType_RoleSkillLevel"] = 35	
	nameToIdx["QuestConditionType_RoleEquipCount"] = 36	
	nameToIdx["QuestConditionType_AnySecretInstanceSucceed"] = 37	
	nameToIdx["QuestConditionType_TrailCount"] = 38	
	nameToIdx["QuestConditionType_AnyTrailInstanceSucceed"] = 39	
	nameToIdx["QuestConditionType_ScarsIngrainDifficultInstanceSucceed"] = 40	
	nameToIdx["QuestConditionType_ScarsIngrainScore"] = 41	
	nameToIdx["QuestConditionType_AnyDrawcardTimes"] = 42	
	nameToIdx["QuestConditionType_WeeklyLogin"] = 43	
	nameToIdx["QuestConditionType_WeeklyActiveness"] = 44	
	nameToIdx["QuestConditionType_EquipRarityOwned"] = 45	
	nameToIdx["QuestConditionType_BigSecretPassTimes"] = 46	
	nameToIdx["QuestConditionType_BigSecretBestScore"] = 47	
	nameToIdx["QuestConditionType_WeaponRarityOwned"] = 48	
	nameToIdx["QuestEventType_AddBuff"] = 1	
	nameToIdx["ResourceConsumeType_Item"] = 1	
	nameToIdx["ResourceConsumeType_UsualAttribute"] = 2	
	nameToIdx["DungeonClearType_KillAppointMonster"] = 1	
	nameToIdx["DungeonClearType_ReachArea"] = 2	
	nameToIdx["DungeonClearType_SurviveForSeconds"] = 3	
	nameToIdx["DungeonClearType_Interact"] = 4	
	nameToIdx["DungeonClearType_SkillMonsterCount"] = 5	
	nameToIdx["DungeonClearType_PlayAnim"] = 6	
	nameToIdx["DungeonStarConditionType_DeathLimit"] = 1	
	nameToIdx["DungeonStarConditionType_PassTimeLimit"] = 2	
	nameToIdx["DungeonStarConditionType_BeHitTimesLimit"] = 3	
	nameToIdx["DungeonStarConditionType_BeHitHpLimit"] = 4	
	nameToIdx["DungeonStarConditionType_TimeRangeDamage"] = 5	
	nameToIdx["DungeonStarConditionType_TimeRangeKill"] = 6	
	nameToIdx["DungeonStarConditionType_UseUltimateTimes"] = 7	
	nameToIdx["DungeonStarConditionType_UltimateEvasionTimes"] = 8	
	nameToIdx["DungeonStarConditionType_GuardTargetHp"] = 9	
	nameToIdx["DungeonStarConditionType_GuardPassMonsterLimit"] = 10	
	nameToIdx["DungeonTeamLimitType_CharacterCountLimit"] = 1	
	nameToIdx["DungeonTeamLimitType_AppointCharacter"] = 2	
	nameToIdx["MainChapterType_Normal"] = 1	
	nameToIdx["MainChapterType_Difficult"] = 2	
	nameToIdx["MainChapterType_Hidden"] = 3	
	nameToIdx["MainChapterType_Branch"] = 4	
	nameToIdx["MainChapterType_Character"] = 5	
	nameToIdx["DropPoolType_Rand"] = 1	
	nameToIdx["DropPoolType_Fixed"] = 2	
	nameToIdx["DropType_Item"] = 1	
	nameToIdx["DropType_UsualAttribute"] = 2	
	nameToIdx["DropType_Equip"] = 3	
	nameToIdx["DropType_Pool"] = 4	
	nameToIdx["DropType_Character"] = 5	
	nameToIdx["DropType_Weapon"] = 6	
	nameToIdx["RewardType_Item"] = 1	
	nameToIdx["RewardType_Equip"] = 2	
	nameToIdx["RewardType_Weapon"] = 3	
	nameToIdx["RewardType_UsualAttribute"] = 4	
	nameToIdx["WeaponType_Sword"] = 1	
	nameToIdx["WeaponType_Gloves"] = 2	
	nameToIdx["WeaponType_DoubleGun"] = 3	
	nameToIdx["WeaponType_Dagger"] = 4	
	nameToIdx["WeaponType_Hammer"] = 5	
	nameToIdx["WeaponType_DoubleSword"] = 6	
	nameToIdx["WeaponType_GreatSword"] = 7	
	nameToIdx["WeaponType_Katana"] = 8	
	nameToIdx["WeaponType_Spear"] = 9	
	nameToIdx["WeaponType_Sickle"] = 10	
	nameToIdx["WeaponType_Amplifier"] = 11	
	nameToIdx["WeaponType_Arch"] = 12	
	nameToIdx["RarityType_Star1"] = 1	
	nameToIdx["RarityType_Star2"] = 2	
	nameToIdx["RarityType_Star3"] = 3	
	nameToIdx["RarityType_Star4"] = 4	
	nameToIdx["RarityType_Star5"] = 5	
	nameToIdx["RarityType_Star6"] = 6	
	nameToIdx["QualityType_C"] = 1	
	nameToIdx["QualityType_B"] = 2	
	nameToIdx["QualityType_A"] = 3	
	nameToIdx["QualityType_S"] = 4	
	nameToIdx["QualityType_SS"] = 5	
	nameToIdx["QualityType_SSS"] = 6	
	nameToIdx["QualityType_SSSP"] = 7	
	nameToIdx["QualityType_SSSPP"] = 8	
	nameToIdx["YuruTouchTriggerType_Click"] = 1	
	nameToIdx["YuruTouchTriggerType_Standby"] = 2	
	nameToIdx["YuruTouchTriggerType_ReturnHome"] = 3	
	nameToIdx["YuruTouchTriggerType_Time"] = 4	
	nameToIdx["YuruTouchTriggerType_EnterUIType"] = 5	
	nameToIdx["YuruTouchTriggerType_ExitUIType"] = 6	
	nameToIdx["YuruTouchCheckType_TimeRange"] = 1	
	nameToIdx["YuruTouchCheckType_UI"] = 2	
	nameToIdx["YuruTouchCheckType_WeaponOn"] = 3	
	nameToIdx["DialogueType_Story"] = 1	
	nameToIdx["DialogueType_BottomTips"] = 2	
	nameToIdx["ScarsIngrainDifficultType_Experiment"] = 1	
	nameToIdx["ScarsIngrainDifficultType_Elites"] = 2	
	nameToIdx["ScarsIngrainDifficultType_Knight"] = 3	
	nameToIdx["ScarsIngrainDifficultType_Chaos"] = 4	
	nameToIdx["ScarsIngrainDifficultType_Hell"] = 5	
	nameToIdx["ScarsIngrainBossChallengeType_BeHit"] = 1	
	nameToIdx["ScarsIngrainBossChallengeType_Time"] = 2	
	nameToIdx["DungeonCostType_FatigueCost"] = 1	
	nameToIdx["DungeonCostType_BigSecretItemCost"] = 2	
	nameToIdx["DungeonUnlockType_MainChapter"] = 1	
	nameToIdx["DungeonUnlockType_MaterialDungeon"] = 2	
	nameToIdx["DungeonUnlockType_PlayerLevel"] = 3	
	nameToIdx["DungeonUnlockType_TrialDungeon"] = 4	
	nameToIdx["DungeonSystemType_MainChapter"] = 1	
	nameToIdx["DungeonSystemType_Material"] = 2	
	nameToIdx["DungeonSystemType_ScarsIngrain"] = 3	
	nameToIdx["DungeonSystemType_WorldQuest"] = 4	
	nameToIdx["DungeonSystemType_Secret"] = 5	
	nameToIdx["DungeonSystemType_Trial"] = 6	
	nameToIdx["DungeonSystemType_Prologue"] = 99	
	nameToIdx["DungeonSystemType_BigSecret"] = 7	
	nameToIdx["ItemTimeLimitType_Duration"] = 1	
	nameToIdx["ItemTimeLimitType_Date"] = 2	
	nameToIdx["DungeonDisplayType_MainChapter"] = 1	
	nameToIdx["DungeonDisplayType_MaterialDungeon"] = 2	
	nameToIdx["DungeonDisplayType_PlayerLevel"] = 3	
	nameToIdx["ConsciousEffectType_XX"] = 1	
	nameToIdx["UIType_Yuru"] = 1	
	nameToIdx["UIType_BattleDialogue"] = 2	
	nameToIdx["UIType_Team"] = 3	
	nameToIdx["UIType_TeammateSelect"] = 4	
	nameToIdx["UIType_RoleSelect"] = 5	
	nameToIdx["UIType_RoleLevelUp"] = 6	
	nameToIdx["UIType_SwitchYuru"] = 7	
	nameToIdx["UIType_RoleFavor"] = 8	
	nameToIdx["UIType_SafeArea"] = 9	
	nameToIdx["UIType_RoleWeapon"] = 10	
	nameToIdx["UIType_RoleGene"] = 11	
	nameToIdx["UIType_DrawCardResult"] = 12	
	nameToIdx["UIType_RoleEquip"] = 13	
	nameToIdx["UIType_RoleSkill"] = 14	
	nameToIdx["UIType_RoleGeneZoomIn"] = 15	
	nameToIdx["UIType_WeaponSelect"] = 16	
	nameToIdx["UIType_WeaponDevelop"] = 17	
	nameToIdx["UIType_ScarsIngrainBoss"] = 18	
	nameToIdx["UIType_BackpackPanel"] = 19	
	nameToIdx["UIType_SettingsPanel"] = 20	
	nameToIdx["UIType_ScarsIngrain"] = 21	
	nameToIdx["UIType_QuestPanel"] = 22	
	nameToIdx["UIType_MainDrawCard"] = 23	
	nameToIdx["UIType_DrawCardTargetDetail"] = 24	
	nameToIdx["UIType_CharacterChapter"] = 25	
	nameToIdx["UIType_CharacterDungeon"] = 26	
	nameToIdx["UIType_Friend"] = 27	
	nameToIdx["UIType_Shop"] = 28	
	nameToIdx["UIType_ShoppingMall"] = 29	
	nameToIdx["UIType_Mail"] = 30	
	nameToIdx["UIType_Synthesis"] = 31	
	nameToIdx["FunctionType_WorldMap"] = 1	
	nameToIdx["FunctionType_WorldQuest"] = 9	
	nameToIdx["FunctionType_ScarsIngrain"] = 10	
	nameToIdx["FunctionType_Lottery"] = 13	
	nameToIdx["FunctionType_Quest"] = 14	
	nameToIdx["FunctionType_Talk"] = 15	
	nameToIdx["FunctionType_Bag"] = 16	
	nameToIdx["FunctionType_Shop"] = 17	
	nameToIdx["FunctionType_Trail"] = 19	
	nameToIdx["FunctionType_Secret"] = 20	
	nameToIdx["FunctionType_MaterialDungeon"] = 21	
	nameToIdx["FunctionType_ChanllengeDungeon"] = 22	
	nameToIdx["FunctionType_CharacterDungeon"] = 23	
	nameToIdx["FunctionType_GrowUpQuest"] = 24	
	nameToIdx["FunctionType_DailyQuest"] = 25	
	nameToIdx["FunctionType_WeeklyQuest"] = 26	
	nameToIdx["FunctionType_Welfare"] = 27	
	nameToIdx["FunctionType_Recharge"] = 28	
	nameToIdx["FunctionType_Friend"] = 29	
	nameToIdx["FunctionType_TeamSetting"] = 30	
	nameToIdx["FunctionType_Activity"] = 31	
	nameToIdx["FunctionType_Mail"] = 32	
	nameToIdx["FunctionType_announcement"] = 33	
	nameToIdx["FunctionType_DailyShop"] = 34	
	nameToIdx["FunctionType_ChallengeShop"] = 35	
	nameToIdx["FunctionType_ScarsIngrainShop"] = 36	
	nameToIdx["FunctionType_SecretShop"] = 37	
	nameToIdx["FunctionType_FakeUnlock1"] = 1001	
	nameToIdx["FunctionType_FakeUnlock2"] = 1002	
	nameToIdx["FunctionType_FakeUnlock3"] = 1003	
	nameToIdx["FunctionType_FakeUnlock4"] = 1004	
	nameToIdx["FunctionType_FakeUnlock5"] = 1005	
	nameToIdx["FunctionType_FakeUnlock6"] = 1006	
	nameToIdx["FunctionType_FakeUnlock7"] = 1007	
	nameToIdx["FunctionType_FakeUnlock8"] = 1008	
	nameToIdx["FunctionType_FakeUnlock9"] = 1009	
	nameToIdx["FunctionType_FakeUnlock10"] = 1010	
	nameToIdx["FunctionUnlockType_PlayerLevel"] = 1	
	nameToIdx["FunctionUnlockType_DungeonPass"] = 2	
	nameToIdx["FunctionUnlockType_TimeRange"] = 3	
	nameToIdx["FunctionUnlockType_Default"] = 4	
	nameToIdx["FunctionUnlockType_PlayerGuide"] = 5	
	nameToIdx["DamageElementType_Fire"] = 1	
	nameToIdx["DamageElementType_Thunder"] = 2	
	nameToIdx["DamageElementType_Wind"] = 4	
	nameToIdx["DamageElementType_Source"] = 8	
	nameToIdx["GiftType_Food"] = 1	
	nameToIdx["GiftType_Game"] = 2	
	nameToIdx["GiftType_Movie"] = 3	
	nameToIdx["EquipSkillLimitType_Main"] = 1	
	nameToIdx["PlayerCharacterSkillTagType_Active"] = 1	
	nameToIdx["PlayerCharacterSkillTagType_Passive"] = 2	
	nameToIdx["PlayerCharacterSkillTagType_Damage"] = 3	
	nameToIdx["PlayerCharacterSkillTagType_Control"] = 4	
	nameToIdx["PlayerCharacterSkillTagType_Recover"] = 5	
	nameToIdx["PlayerCharacterSkillTagType_Buff"] = 6	
	nameToIdx["PlayerCampType_Camp1"] = 1	
	nameToIdx["PlayerCampType_Camp2"] = 2	
	nameToIdx["PlayerCampType_Camp3"] = 3	
	nameToIdx["PlayerCampType_Camp4"] = 4	
	nameToIdx["PlayerCampReputationLevelType_Level1"] = 1	
	nameToIdx["PlayerCampReputationLevelType_Level2"] = 2	
	nameToIdx["PlayerCampReputationLevelType_Level3"] = 3	
	nameToIdx["PlayerCampReputationLevelType_Level4"] = 4	
	nameToIdx["PlayerCampReputationLevelType_Level5"] = 5	
	nameToIdx["PlayerCampReputationLevelType_Level6"] = 6	
	nameToIdx["WorldQuestType_KillMonster"] = 1	
	nameToIdx["WorldQuestType_KillTargetMonster"] = 2	
	nameToIdx["WorldQuestType_EscortNpcToTargetLocation"] = 3	
	nameToIdx["WorldQuestType_ProtectNpc"] = 4	
	nameToIdx["WorldQuestType_KeepAlive"] = 5	
	nameToIdx["WorldQuestType_Collect"] = 6	
	nameToIdx["WorldQuestType_ToTargetLocation"] = 7	
	nameToIdx["WorldQuestType_Destroy"] = 8	
	nameToIdx["ProductLimitType_Daily"] = 1	
	nameToIdx["ProductLimitType_Weekly"] = 2	
	nameToIdx["ProductLimitType_Monthly"] = 3	
	nameToIdx["ProductLimitType_Lifelong"] = 4	
	nameToIdx["ProductLimitType_Date"] = 5	
	nameToIdx["ShopType_Daily"] = 1	
	nameToIdx["ShopType_Challenge"] = 2	
	nameToIdx["ShopType_ScarsIngrain"] = 3	
	nameToIdx["ShopType_Secret"] = 4	
	nameToIdx["MaterialDungeonType_Gold"] = 1	
	nameToIdx["MaterialDungeonType_CharacterExp"] = 2	
	nameToIdx["MaterialDungeonType_WeaponExp"] = 3	
	nameToIdx["MaterialDungeonType_SkillExp"] = 4	
	nameToIdx["MaterialDungeonType_CharacterBreak"] = 5	
	nameToIdx["MaterialDungeonType_WeaponBreak"] = 6	
	nameToIdx["MaterialDungeonType_CommonMaterial"] = 7	
	nameToIdx["SecretDifficultyType_Level1"] = 1	
	nameToIdx["SecretDifficultyType_Level2"] = 2	
	nameToIdx["SecretDifficultyType_Level3"] = 3	
	nameToIdx["SecretDifficultyType_Level4"] = 4	
	nameToIdx["BattleAttributeType_Base"] = 1	
	nameToIdx["BattleAttributeType_Advanced"] = 2	
	nameToIdx["WeaponSortType_Rarity"] = 1	
	nameToIdx["WeaponSortType_BreakLevel"] = 2	
	nameToIdx["WeaponSortType_Level"] = 3	
	nameToIdx["WeaponSortType_ID"] = 4	
	nameToIdx["WeaponSortType_WeaponType"] = 5	
	nameToIdx["WeaponSortType_RefineLevel"] = 6	
	nameToIdx["WeaponSortType_AcquireTime"] = 7	
	nameToIdx["WeaponSortType_InsID"] = 8	
	nameToIdx["EquipType_Attack"] = 1	
	nameToIdx["EquipType_Defend"] = 2	
	nameToIdx["EquipType_Help"] = 3	
	nameToIdx["VoicePlayTriggerType_GameLogo"] = 1	
	nameToIdx["VoicePlayTriggerType_PlayerLogin"] = 2	
	nameToIdx["VoicePlayTriggerType_RoleSelect"] = 3	
	nameToIdx["VoicePlayTriggerType_RoleInTeam"] = 4	
	nameToIdx["VoicePlayTriggerType_RoleBeCaptain"] = 5	
	nameToIdx["VoicePlayTriggerType_SafeAreaRoleIdle"] = 6	
	nameToIdx["VoicePlayTriggerType_GetDailyQuestAward"] = 7	
	nameToIdx["VoicePlayTriggerType_DrawCardGetRole"] = 8	
	nameToIdx["VoicePlayTriggerType_BattleSkill"] = 9	
	nameToIdx["VoicePlayTriggerType_BattleEXSkill"] = 10	
	nameToIdx["VoicePlayTriggerType_BattleBeHitLong"] = 11	
	nameToIdx["VoicePlayTriggerType_BattleBeHitShort"] = 12	
	nameToIdx["VoicePlayTriggerType_BattleDying"] = 13	
	nameToIdx["VoicePlayTriggerType_BattleDead"] = 14	
	nameToIdx["VoicePlayTriggerType_BattleRoleIdle"] = 15	
	nameToIdx["VoicePlayTriggerType_LevelWarning"] = 16	
	nameToIdx["VoicePlayTriggerType_LevelSucceed"] = 17	
	nameToIdx["VoicePlayConditionType_RoleID"] = 1	
	nameToIdx["VoicePlayConditionType_SkillName"] = 2	
	nameToIdx["MaterialType_Character"] = 1	
	nameToIdx["MaterialType_Skill"] = 2	
	nameToIdx["MaterialType_Weapon"] = 3	
	nameToIdx["MaterialSystemType_Synthesis "] = 1	
	nameToIdx["MaterialSystemType_Conversion"] = 2	
	nameToIdx["AnnouncementType_System"] = 1	
	nameToIdx["AnnouncementType_Activity"] = 2	
	nameToIdx["AnnouncementContentType_OnlyImage"] = 1	
	nameToIdx["AnnouncementContentType_ImageAndText"] = 2	
	nameToIdx["SignType_Month"] = 1	
	nameToIdx["SignType_Activity"] = 2	
	nameToIdx["SignType_Beginner"] = 3	
	nameToIdx["SignType_Questionnaire"] = 4	
	nameToIdx["WelfareType_Sign"] = 1	
	nameToIdx["WelfareType_Other"] = 2	
	nameToIdx["CharacterDevelopmentPanelPage_Attribute"] = 1	
	nameToIdx["CharacterDevelopmentPanelPage_Weapon"] = 2	
	nameToIdx["CharacterDevelopmentPanelPage_Skill"] = 3	
	nameToIdx["CharacterDevelopmentPanelPage_Equip"] = 4	
	nameToIdx["CharacterDevelopmentPanelPage_Gene"] = 5	
	nameToIdx["BigSecretMonsterGroupType_AllNormal"] = 1	
	nameToIdx["BigSecretMonsterGroupType_OneElite"] = 2	
	nameToIdx["BigSecretMonsterGroupType_AllElite"] = 3	
	nameToIdx["BigSecretMonsterGroupType_OneBoss"] = 4	
	nameToIdx["ChainSkillType_Bind"] = 1	
	nameToIdx["ChainSkillType_Sign"] = 2	
	nameToIdx["ChainSkillType_Line"] = 3	
	nameToIdx["BigSecretAffixType_Normal"] = 1	
	nameToIdx["BigSecretAffixType_Advance"] = 2	
	nameToIdx["BigSecretAffixType_Aura"] = 3	
	nameToIdx["BigSecretAffixType_Linkage"] = 4	
	nameToIdx["TalentLevelUpConditionType_PlayerLv"] = 1
}

func GetEnumType(name string) (int32,error) {
	if idx, ok := nameToIdx[name]; ok {
		return idx,nil
	}else {
		return 0,fmt.Errorf("%s is not find",name)
	}
}
