// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ss/proto/ssmessage/mailUpdate.proto

package ssmessage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MailUpdate struct {
	Global               *bool    `protobuf:"varint,1,opt,name=global" json:"global,omitempty"`
	GameID               []uint64 `protobuf:"varint,2,rep,name=gameID" json:"gameID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailUpdate) Reset()         { *m = MailUpdate{} }
func (m *MailUpdate) String() string { return proto.CompactTextString(m) }
func (*MailUpdate) ProtoMessage()    {}
func (*MailUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd1aaec9637afdc9, []int{0}
}

func (m *MailUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailUpdate.Unmarshal(m, b)
}
func (m *MailUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailUpdate.Marshal(b, m, deterministic)
}
func (m *MailUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailUpdate.Merge(m, src)
}
func (m *MailUpdate) XXX_Size() int {
	return xxx_messageInfo_MailUpdate.Size(m)
}
func (m *MailUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_MailUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_MailUpdate proto.InternalMessageInfo

func (m *MailUpdate) GetGlobal() bool {
	if m != nil && m.Global != nil {
		return *m.Global
	}
	return false
}

func (m *MailUpdate) GetGameID() []uint64 {
	if m != nil {
		return m.GameID
	}
	return nil
}

func init() {
	proto.RegisterType((*MailUpdate)(nil), "ssmessage.mailUpdate")
}

func init() {
	proto.RegisterFile("ss/proto/ssmessage/mailUpdate.proto", fileDescriptor_fd1aaec9637afdc9)
}

var fileDescriptor_fd1aaec9637afdc9 = []byte{
	// 128 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2e, 0x2e, 0xd6, 0x2f,
	0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2f, 0x2e, 0xce, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0xcf,
	0x4d, 0xcc, 0xcc, 0x09, 0x2d, 0x48, 0x49, 0x2c, 0x49, 0xd5, 0x03, 0x4b, 0x09, 0x71, 0xc2, 0xe5,
	0x94, 0x6c, 0xb8, 0xb8, 0x10, 0xd2, 0x42, 0x62, 0x5c, 0x6c, 0xe9, 0x39, 0xf9, 0x49, 0x89, 0x39,
	0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x1c, 0x41, 0x50, 0x1e, 0x58, 0x3c, 0x31, 0x37, 0xd5, 0xd3, 0x45,
	0x82, 0x49, 0x81, 0x59, 0x83, 0x25, 0x08, 0xca, 0x73, 0x52, 0x89, 0x52, 0xca, 0xcc, 0xcb, 0x2c,
	0xc9, 0x4c, 0xcc, 0x29, 0xc9, 0x28, 0x4a, 0x4d, 0x85, 0xd8, 0x9c, 0x9c, 0x9f, 0xa3, 0x5f, 0x5c,
	0x8c, 0xb0, 0x1f, 0x10, 0x00, 0x00, 0xff, 0xff, 0x00, 0xba, 0x43, 0x06, 0x94, 0x00, 0x00, 0x00,
}
