// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/lbproto.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LbReport struct {
	Logic                *uint32  `protobuf:"varint,1,req,name=logic" json:"logic,omitempty"`
	Priority             *uint32  `protobuf:"varint,2,req,name=priority" json:"priority,omitempty"`
	Capacity             *uint32  `protobuf:"varint,3,req,name=capacity" json:"capacity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LbReport) Reset()         { *m = LbReport{} }
func (m *LbReport) String() string { return proto.CompactTextString(m) }
func (*LbReport) ProtoMessage()    {}
func (*LbReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_9dec10b7c6667436, []int{0}
}

func (m *LbReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LbReport.Unmarshal(m, b)
}
func (m *LbReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LbReport.Marshal(b, m, deterministic)
}
func (m *LbReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LbReport.Merge(m, src)
}
func (m *LbReport) XXX_Size() int {
	return xxx_messageInfo_LbReport.Size(m)
}
func (m *LbReport) XXX_DiscardUnknown() {
	xxx_messageInfo_LbReport.DiscardUnknown(m)
}

var xxx_messageInfo_LbReport proto.InternalMessageInfo

func (m *LbReport) GetLogic() uint32 {
	if m != nil && m.Logic != nil {
		return *m.Logic
	}
	return 0
}

func (m *LbReport) GetPriority() uint32 {
	if m != nil && m.Priority != nil {
		return *m.Priority
	}
	return 0
}

func (m *LbReport) GetCapacity() uint32 {
	if m != nil && m.Capacity != nil {
		return *m.Capacity
	}
	return 0
}

func init() {
	proto.RegisterType((*LbReport)(nil), "proto.lbReport")
}

func init() { proto.RegisterFile("proto/lbproto.proto", fileDescriptor_9dec10b7c6667436) }

var fileDescriptor_9dec10b7c6667436 = []byte{
	// 103 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x49, 0x02, 0xd3, 0x7a, 0x60, 0x52, 0x88, 0x15, 0x4c, 0x29, 0x45, 0x70, 0x71,
	0xe4, 0x24, 0x05, 0xa5, 0x16, 0xe4, 0x17, 0x95, 0x08, 0x89, 0x70, 0xb1, 0xe6, 0xe4, 0xa7, 0x67,
	0x26, 0x4b, 0x30, 0x2a, 0x30, 0x69, 0xf0, 0x06, 0x41, 0x38, 0x42, 0x52, 0x5c, 0x1c, 0x05, 0x45,
	0x99, 0xf9, 0x45, 0x99, 0x25, 0x95, 0x12, 0x4c, 0x60, 0x09, 0x38, 0x1f, 0x24, 0x97, 0x9c, 0x58,
	0x90, 0x98, 0x0c, 0x92, 0x63, 0x86, 0xc8, 0xc1, 0xf8, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd0,
	0xce, 0x55, 0x7e, 0x76, 0x00, 0x00, 0x00,
}
