// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ss/proto/rpc/common.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RoleInfo struct {
	UserID               *string  `protobuf:"bytes,1,req,name=userID" json:"userID,omitempty"`
	RoleID               *uint64  `protobuf:"varint,2,req,name=roleID" json:"roleID,omitempty"`
	Game                 *string  `protobuf:"bytes,3,req,name=game" json:"game,omitempty"`
	Face                 *int32   `protobuf:"varint,4,opt,name=Face" json:"Face,omitempty"`
	Hair                 *int32   `protobuf:"varint,5,opt,name=Hair" json:"Hair,omitempty"`
	HairColor            *int32   `protobuf:"varint,6,opt,name=HairColor" json:"HairColor,omitempty"`
	EyeColor             *int32   `protobuf:"varint,7,opt,name=EyeColor" json:"EyeColor,omitempty"`
	Outline              *int32   `protobuf:"varint,8,opt,name=Outline" json:"Outline,omitempty"`
	Name                 *string  `protobuf:"bytes,9,opt,name=Name" json:"Name,omitempty"`
	Cloth                *int32   `protobuf:"varint,10,opt,name=Cloth" json:"Cloth,omitempty"`
	ClothColor           *int32   `protobuf:"varint,11,opt,name=ClothColor" json:"ClothColor,omitempty"`
	Level                *int32   `protobuf:"varint,12,opt,name=Level" json:"Level,omitempty"`
	Portrait             *int32   `protobuf:"varint,13,opt,name=Portrait" json:"Portrait,omitempty"`
	Skills               []*Skill `protobuf:"bytes,14,rep,name=skills" json:"skills,omitempty"`
	Weapon1              *Weapon  `protobuf:"bytes,15,opt,name=weapon1" json:"weapon1,omitempty"`
	Weapon2              *Weapon  `protobuf:"bytes,16,opt,name=weapon2" json:"weapon2,omitempty"`
	RoleType             *int32   `protobuf:"varint,17,opt,name=RoleType" json:"RoleType,omitempty"`
	CampType             *int32   `protobuf:"varint,18,opt,name=CampType" json:"CampType,omitempty"`
	GeneralID            *int32   `protobuf:"varint,19,opt,name=GeneralID" json:"GeneralID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleInfo) Reset()         { *m = RoleInfo{} }
func (m *RoleInfo) String() string { return proto.CompactTextString(m) }
func (*RoleInfo) ProtoMessage()    {}
func (*RoleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c14f55c403fabb0, []int{0}
}

func (m *RoleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleInfo.Unmarshal(m, b)
}
func (m *RoleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleInfo.Marshal(b, m, deterministic)
}
func (m *RoleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleInfo.Merge(m, src)
}
func (m *RoleInfo) XXX_Size() int {
	return xxx_messageInfo_RoleInfo.Size(m)
}
func (m *RoleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoleInfo proto.InternalMessageInfo

func (m *RoleInfo) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *RoleInfo) GetRoleID() uint64 {
	if m != nil && m.RoleID != nil {
		return *m.RoleID
	}
	return 0
}

func (m *RoleInfo) GetGame() string {
	if m != nil && m.Game != nil {
		return *m.Game
	}
	return ""
}

func (m *RoleInfo) GetFace() int32 {
	if m != nil && m.Face != nil {
		return *m.Face
	}
	return 0
}

func (m *RoleInfo) GetHair() int32 {
	if m != nil && m.Hair != nil {
		return *m.Hair
	}
	return 0
}

func (m *RoleInfo) GetHairColor() int32 {
	if m != nil && m.HairColor != nil {
		return *m.HairColor
	}
	return 0
}

func (m *RoleInfo) GetEyeColor() int32 {
	if m != nil && m.EyeColor != nil {
		return *m.EyeColor
	}
	return 0
}

func (m *RoleInfo) GetOutline() int32 {
	if m != nil && m.Outline != nil {
		return *m.Outline
	}
	return 0
}

func (m *RoleInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *RoleInfo) GetCloth() int32 {
	if m != nil && m.Cloth != nil {
		return *m.Cloth
	}
	return 0
}

func (m *RoleInfo) GetClothColor() int32 {
	if m != nil && m.ClothColor != nil {
		return *m.ClothColor
	}
	return 0
}

func (m *RoleInfo) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *RoleInfo) GetPortrait() int32 {
	if m != nil && m.Portrait != nil {
		return *m.Portrait
	}
	return 0
}

func (m *RoleInfo) GetSkills() []*Skill {
	if m != nil {
		return m.Skills
	}
	return nil
}

func (m *RoleInfo) GetWeapon1() *Weapon {
	if m != nil {
		return m.Weapon1
	}
	return nil
}

func (m *RoleInfo) GetWeapon2() *Weapon {
	if m != nil {
		return m.Weapon2
	}
	return nil
}

func (m *RoleInfo) GetRoleType() int32 {
	if m != nil && m.RoleType != nil {
		return *m.RoleType
	}
	return 0
}

func (m *RoleInfo) GetCampType() int32 {
	if m != nil && m.CampType != nil {
		return *m.CampType
	}
	return 0
}

func (m *RoleInfo) GetGeneralID() int32 {
	if m != nil && m.GeneralID != nil {
		return *m.GeneralID
	}
	return 0
}

type Attribute struct {
	Index                *int32   `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Value                *int32   `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Attribute) Reset()         { *m = Attribute{} }
func (m *Attribute) String() string { return proto.CompactTextString(m) }
func (*Attribute) ProtoMessage()    {}
func (*Attribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c14f55c403fabb0, []int{1}
}

func (m *Attribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attribute.Unmarshal(m, b)
}
func (m *Attribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attribute.Marshal(b, m, deterministic)
}
func (m *Attribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attribute.Merge(m, src)
}
func (m *Attribute) XXX_Size() int {
	return xxx_messageInfo_Attribute.Size(m)
}
func (m *Attribute) XXX_DiscardUnknown() {
	xxx_messageInfo_Attribute.DiscardUnknown(m)
}

var xxx_messageInfo_Attribute proto.InternalMessageInfo

func (m *Attribute) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *Attribute) GetValue() int32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

type Skill struct {
	SkillID              *int32   `protobuf:"varint,1,opt,name=skillID" json:"skillID,omitempty"`
	SkillLevel           *int32   `protobuf:"varint,2,opt,name=skillLevel" json:"skillLevel,omitempty"`
	SpecialStar          *int32   `protobuf:"varint,3,opt,name=specialStar" json:"specialStar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Skill) Reset()         { *m = Skill{} }
func (m *Skill) String() string { return proto.CompactTextString(m) }
func (*Skill) ProtoMessage()    {}
func (*Skill) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c14f55c403fabb0, []int{2}
}

func (m *Skill) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Skill.Unmarshal(m, b)
}
func (m *Skill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Skill.Marshal(b, m, deterministic)
}
func (m *Skill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Skill.Merge(m, src)
}
func (m *Skill) XXX_Size() int {
	return xxx_messageInfo_Skill.Size(m)
}
func (m *Skill) XXX_DiscardUnknown() {
	xxx_messageInfo_Skill.DiscardUnknown(m)
}

var xxx_messageInfo_Skill proto.InternalMessageInfo

func (m *Skill) GetSkillID() int32 {
	if m != nil && m.SkillID != nil {
		return *m.SkillID
	}
	return 0
}

func (m *Skill) GetSkillLevel() int32 {
	if m != nil && m.SkillLevel != nil {
		return *m.SkillLevel
	}
	return 0
}

func (m *Skill) GetSpecialStar() int32 {
	if m != nil && m.SpecialStar != nil {
		return *m.SpecialStar
	}
	return 0
}

type Weapon struct {
	State                *int32       `protobuf:"varint,1,opt,name=state" json:"state,omitempty"`
	WeaponID             *int32       `protobuf:"varint,2,opt,name=weaponID" json:"weaponID,omitempty"`
	BattleAttrs          []*Attribute `protobuf:"bytes,3,rep,name=battleAttrs" json:"battleAttrs,omitempty"`
	Skills               []*Skill     `protobuf:"bytes,4,rep,name=skills" json:"skills,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Weapon) Reset()         { *m = Weapon{} }
func (m *Weapon) String() string { return proto.CompactTextString(m) }
func (*Weapon) ProtoMessage()    {}
func (*Weapon) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c14f55c403fabb0, []int{3}
}

func (m *Weapon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Weapon.Unmarshal(m, b)
}
func (m *Weapon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Weapon.Marshal(b, m, deterministic)
}
func (m *Weapon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Weapon.Merge(m, src)
}
func (m *Weapon) XXX_Size() int {
	return xxx_messageInfo_Weapon.Size(m)
}
func (m *Weapon) XXX_DiscardUnknown() {
	xxx_messageInfo_Weapon.DiscardUnknown(m)
}

var xxx_messageInfo_Weapon proto.InternalMessageInfo

func (m *Weapon) GetState() int32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

func (m *Weapon) GetWeaponID() int32 {
	if m != nil && m.WeaponID != nil {
		return *m.WeaponID
	}
	return 0
}

func (m *Weapon) GetBattleAttrs() []*Attribute {
	if m != nil {
		return m.BattleAttrs
	}
	return nil
}

func (m *Weapon) GetSkills() []*Skill {
	if m != nil {
		return m.Skills
	}
	return nil
}

type TeamRoleInfo struct {
	UserID               *string                 `protobuf:"bytes,1,req,name=userID" json:"userID,omitempty"`
	RoleID               *uint64                 `protobuf:"varint,2,req,name=roleID" json:"roleID,omitempty"`
	Game                 *string                 `protobuf:"bytes,3,req,name=game" json:"game,omitempty"`
	Weapon1              *int32                  `protobuf:"varint,6,opt,name=weapon1" json:"weapon1,omitempty"`
	Weapon2              *int32                  `protobuf:"varint,7,opt,name=weapon2" json:"weapon2,omitempty"`
	Face                 *int32                  `protobuf:"varint,8,opt,name=Face" json:"Face,omitempty"`
	Hair                 *int32                  `protobuf:"varint,9,opt,name=Hair" json:"Hair,omitempty"`
	HairColor            *int32                  `protobuf:"varint,10,opt,name=HairColor" json:"HairColor,omitempty"`
	EyeColor             *int32                  `protobuf:"varint,11,opt,name=EyeColor" json:"EyeColor,omitempty"`
	Outline              *int32                  `protobuf:"varint,12,opt,name=Outline" json:"Outline,omitempty"`
	Cloth                *int32                  `protobuf:"varint,13,opt,name=Cloth" json:"Cloth,omitempty"`
	ClothColor           *int32                  `protobuf:"varint,14,opt,name=ClothColor" json:"ClothColor,omitempty"`
	Portrait             *int32                  `protobuf:"varint,15,opt,name=Portrait" json:"Portrait,omitempty"`
	Name                 *string                 `protobuf:"bytes,16,opt,name=Name" json:"Name,omitempty"`
	Level                *int32                  `protobuf:"varint,17,opt,name=Level" json:"Level,omitempty"`
	GeneralID            *int32                  `protobuf:"varint,18,opt,name=GeneralID" json:"GeneralID,omitempty"`
	CE                   *int64                  `protobuf:"varint,19,opt,name=CE" json:"CE,omitempty"`
	Generals             []*TeamRoleInfo_General `protobuf:"bytes,20,rep,name=generals" json:"generals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *TeamRoleInfo) Reset()         { *m = TeamRoleInfo{} }
func (m *TeamRoleInfo) String() string { return proto.CompactTextString(m) }
func (*TeamRoleInfo) ProtoMessage()    {}
func (*TeamRoleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c14f55c403fabb0, []int{4}
}

func (m *TeamRoleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamRoleInfo.Unmarshal(m, b)
}
func (m *TeamRoleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamRoleInfo.Marshal(b, m, deterministic)
}
func (m *TeamRoleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamRoleInfo.Merge(m, src)
}
func (m *TeamRoleInfo) XXX_Size() int {
	return xxx_messageInfo_TeamRoleInfo.Size(m)
}
func (m *TeamRoleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamRoleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TeamRoleInfo proto.InternalMessageInfo

func (m *TeamRoleInfo) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *TeamRoleInfo) GetRoleID() uint64 {
	if m != nil && m.RoleID != nil {
		return *m.RoleID
	}
	return 0
}

func (m *TeamRoleInfo) GetGame() string {
	if m != nil && m.Game != nil {
		return *m.Game
	}
	return ""
}

func (m *TeamRoleInfo) GetWeapon1() int32 {
	if m != nil && m.Weapon1 != nil {
		return *m.Weapon1
	}
	return 0
}

func (m *TeamRoleInfo) GetWeapon2() int32 {
	if m != nil && m.Weapon2 != nil {
		return *m.Weapon2
	}
	return 0
}

func (m *TeamRoleInfo) GetFace() int32 {
	if m != nil && m.Face != nil {
		return *m.Face
	}
	return 0
}

func (m *TeamRoleInfo) GetHair() int32 {
	if m != nil && m.Hair != nil {
		return *m.Hair
	}
	return 0
}

func (m *TeamRoleInfo) GetHairColor() int32 {
	if m != nil && m.HairColor != nil {
		return *m.HairColor
	}
	return 0
}

func (m *TeamRoleInfo) GetEyeColor() int32 {
	if m != nil && m.EyeColor != nil {
		return *m.EyeColor
	}
	return 0
}

func (m *TeamRoleInfo) GetOutline() int32 {
	if m != nil && m.Outline != nil {
		return *m.Outline
	}
	return 0
}

func (m *TeamRoleInfo) GetCloth() int32 {
	if m != nil && m.Cloth != nil {
		return *m.Cloth
	}
	return 0
}

func (m *TeamRoleInfo) GetClothColor() int32 {
	if m != nil && m.ClothColor != nil {
		return *m.ClothColor
	}
	return 0
}

func (m *TeamRoleInfo) GetPortrait() int32 {
	if m != nil && m.Portrait != nil {
		return *m.Portrait
	}
	return 0
}

func (m *TeamRoleInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *TeamRoleInfo) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *TeamRoleInfo) GetGeneralID() int32 {
	if m != nil && m.GeneralID != nil {
		return *m.GeneralID
	}
	return 0
}

func (m *TeamRoleInfo) GetCE() int64 {
	if m != nil && m.CE != nil {
		return *m.CE
	}
	return 0
}

func (m *TeamRoleInfo) GetGenerals() []*TeamRoleInfo_General {
	if m != nil {
		return m.Generals
	}
	return nil
}

type TeamRoleInfo_General struct {
	ConfigId             *int32   `protobuf:"varint,1,opt,name=configId" json:"configId,omitempty"`
	Status               *int32   `protobuf:"varint,2,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeamRoleInfo_General) Reset()         { *m = TeamRoleInfo_General{} }
func (m *TeamRoleInfo_General) String() string { return proto.CompactTextString(m) }
func (*TeamRoleInfo_General) ProtoMessage()    {}
func (*TeamRoleInfo_General) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c14f55c403fabb0, []int{4, 0}
}

func (m *TeamRoleInfo_General) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamRoleInfo_General.Unmarshal(m, b)
}
func (m *TeamRoleInfo_General) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamRoleInfo_General.Marshal(b, m, deterministic)
}
func (m *TeamRoleInfo_General) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamRoleInfo_General.Merge(m, src)
}
func (m *TeamRoleInfo_General) XXX_Size() int {
	return xxx_messageInfo_TeamRoleInfo_General.Size(m)
}
func (m *TeamRoleInfo_General) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamRoleInfo_General.DiscardUnknown(m)
}

var xxx_messageInfo_TeamRoleInfo_General proto.InternalMessageInfo

func (m *TeamRoleInfo_General) GetConfigId() int32 {
	if m != nil && m.ConfigId != nil {
		return *m.ConfigId
	}
	return 0
}

func (m *TeamRoleInfo_General) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

type Position struct {
	X                    *int32   `protobuf:"varint,1,opt,name=x" json:"x,omitempty"`
	Y                    *int32   `protobuf:"varint,2,opt,name=y" json:"y,omitempty"`
	Z                    *int32   `protobuf:"varint,3,opt,name=z" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c14f55c403fabb0, []int{5}
}

func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Position) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *Position) GetZ() int32 {
	if m != nil && m.Z != nil {
		return *m.Z
	}
	return 0
}

func init() {
	proto.RegisterType((*RoleInfo)(nil), "rpc.RoleInfo")
	proto.RegisterType((*Attribute)(nil), "rpc.Attribute")
	proto.RegisterType((*Skill)(nil), "rpc.Skill")
	proto.RegisterType((*Weapon)(nil), "rpc.Weapon")
	proto.RegisterType((*TeamRoleInfo)(nil), "rpc.TeamRoleInfo")
	proto.RegisterType((*TeamRoleInfo_General)(nil), "rpc.TeamRoleInfo.General")
	proto.RegisterType((*Position)(nil), "rpc.position")
}

func init() { proto.RegisterFile("ss/proto/rpc/common.proto", fileDescriptor_7c14f55c403fabb0) }

var fileDescriptor_7c14f55c403fabb0 = []byte{
	// 649 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0xf3, 0x9d, 0x71, 0x9a, 0xb6, 0x4b, 0x85, 0xb6, 0x55, 0x55, 0x59, 0x96, 0x90, 0x72,
	0x4a, 0x20, 0x02, 0x71, 0xe2, 0x00, 0x69, 0x81, 0x48, 0x08, 0x90, 0x5b, 0x09, 0x89, 0xdb, 0xd6,
	0xdd, 0xb6, 0x16, 0x8e, 0xd7, 0xda, 0xdd, 0x94, 0xa6, 0x3f, 0x02, 0xf1, 0x1b, 0xf8, 0xa5, 0x68,
	0x66, 0x6d, 0xc7, 0x2d, 0x84, 0x13, 0xa7, 0xec, 0x7b, 0x6f, 0x56, 0x99, 0x9d, 0x79, 0xcf, 0xb0,
	0x6f, 0xcc, 0x24, 0xd7, 0xca, 0xaa, 0x89, 0xce, 0xe3, 0x49, 0xac, 0x16, 0x0b, 0x95, 0x8d, 0x89,
	0x60, 0x4d, 0x9d, 0xc7, 0xe1, 0x8f, 0x16, 0xf4, 0x22, 0x95, 0xca, 0x79, 0x76, 0xa9, 0xd8, 0x63,
	0xe8, 0x2c, 0x8d, 0xd4, 0xf3, 0x63, 0xee, 0x05, 0x8d, 0x51, 0x3f, 0x2a, 0x10, 0xf2, 0x1a, 0x6b,
	0x8e, 0x79, 0x23, 0x68, 0x8c, 0x5a, 0x51, 0x81, 0x18, 0x83, 0xd6, 0x95, 0x58, 0x48, 0xde, 0xa4,
	0x6a, 0x3a, 0x23, 0xf7, 0x56, 0xc4, 0x92, 0xb7, 0x02, 0x6f, 0xd4, 0x8e, 0xe8, 0x8c, 0xdc, 0x7b,
	0x91, 0x68, 0xde, 0x76, 0x1c, 0x9e, 0xd9, 0x21, 0xf4, 0xf1, 0x77, 0xa6, 0x52, 0xa5, 0x79, 0x87,
	0x84, 0x35, 0xc1, 0x0e, 0xa0, 0x77, 0xb2, 0x92, 0x4e, 0xec, 0x92, 0x58, 0x61, 0xc6, 0xa1, 0xfb,
	0x69, 0x69, 0xd3, 0x24, 0x93, 0xbc, 0x47, 0x52, 0x09, 0xf1, 0x7f, 0x3e, 0x62, 0x3f, 0xfd, 0xc0,
	0xc3, 0x7e, 0xf0, 0xcc, 0xf6, 0xa0, 0x3d, 0x4b, 0x95, 0xbd, 0xe6, 0x40, 0xb5, 0x0e, 0xb0, 0x23,
	0x00, 0x3a, 0xb8, 0x7f, 0xf0, 0x49, 0xaa, 0x31, 0x78, 0xeb, 0x83, 0xbc, 0x91, 0x29, 0x1f, 0xb8,
	0x5b, 0x04, 0xb0, 0xab, 0xcf, 0x4a, 0x5b, 0x2d, 0x12, 0xcb, 0xb7, 0x5c, 0x57, 0x25, 0x66, 0x21,
	0x74, 0xcc, 0xb7, 0x24, 0x4d, 0x0d, 0x1f, 0x06, 0xcd, 0x91, 0x3f, 0x85, 0xb1, 0xce, 0xe3, 0xf1,
	0x29, 0x52, 0x51, 0xa1, 0xb0, 0x27, 0xd0, 0xfd, 0x2e, 0x45, 0xae, 0xb2, 0x67, 0x7c, 0x3b, 0xf0,
	0x46, 0xfe, 0xd4, 0xa7, 0xa2, 0x2f, 0xc4, 0x45, 0xa5, 0xb6, 0x2e, 0x9b, 0xf2, 0x9d, 0x8d, 0x65,
	0x53, 0xec, 0x06, 0x37, 0x77, 0xb6, 0xca, 0x25, 0xdf, 0x75, 0xdd, 0x94, 0x18, 0xb5, 0x99, 0x58,
	0xe4, 0xa4, 0x31, 0xa7, 0x95, 0x18, 0x27, 0xff, 0x4e, 0x66, 0x52, 0x8b, 0x74, 0x7e, 0xcc, 0x1f,
	0xb9, 0xc9, 0x57, 0x44, 0xf8, 0x12, 0xfa, 0xaf, 0xad, 0xd5, 0xc9, 0xf9, 0xd2, 0xd2, 0xf0, 0x92,
	0xec, 0x42, 0xde, 0x72, 0xcf, 0x8d, 0x81, 0x00, 0xb2, 0x37, 0x22, 0x5d, 0x4a, 0xde, 0x70, 0x2c,
	0x81, 0x30, 0x86, 0x36, 0xbd, 0x16, 0xf7, 0x43, 0xef, 0x25, 0x1b, 0xd1, 0x7e, 0x0a, 0x88, 0x53,
	0xa7, 0xa3, 0x1b, 0xad, 0xbb, 0x5d, 0x63, 0x58, 0x00, 0xbe, 0xc9, 0x65, 0x9c, 0x88, 0xf4, 0xd4,
	0x0a, 0xcd, 0x9b, 0x54, 0x50, 0xa7, 0xc2, 0x9f, 0x1e, 0x74, 0xdc, 0x1c, 0xb0, 0x0b, 0x63, 0x85,
	0x95, 0x65, 0x6f, 0x04, 0xf0, 0xe1, 0x6e, 0x3e, 0x64, 0x56, 0x7a, 0x78, 0x89, 0xd9, 0x53, 0xf0,
	0xcf, 0x85, 0xb5, 0xa9, 0xc4, 0x07, 0x1a, 0xde, 0xa4, 0x3d, 0x0d, 0x69, 0xb6, 0xd5, 0x93, 0xa3,
	0x7a, 0x49, 0x6d, 0xa9, 0xad, 0x4d, 0x4b, 0x0d, 0x7f, 0xb5, 0x60, 0x70, 0x26, 0xc5, 0xe2, 0xbf,
	0xa6, 0x88, 0xaf, 0x9d, 0xe2, 0xb2, 0x51, 0x99, 0x83, 0xaf, 0xcd, 0xd1, 0xad, 0x2b, 0xd3, 0x2a,
	0x79, 0xbd, 0xbf, 0x24, 0xaf, 0xbf, 0x29, 0x79, 0xf0, 0xaf, 0xe4, 0xf9, 0x9b, 0x93, 0x37, 0xb8,
	0x9f, 0xbc, 0x2a, 0x65, 0x5b, 0x9b, 0x53, 0x36, 0xfc, 0x23, 0x65, 0xf5, 0x3c, 0x6d, 0x3f, 0xc8,
	0x53, 0x99, 0xe5, 0x9d, 0xfb, 0x59, 0x76, 0xd6, 0xd9, 0xad, 0xa7, 0xf2, 0x9e, 0x9f, 0xd9, 0x03,
	0x3f, 0xb3, 0x21, 0x34, 0x66, 0x27, 0x64, 0xf3, 0x66, 0xd4, 0x98, 0x9d, 0xb0, 0x17, 0xd0, 0xbb,
	0x72, 0xa2, 0xe1, 0x7b, 0xb4, 0xd4, 0x7d, 0x5a, 0x6a, 0x7d, 0x85, 0xe3, 0xe2, 0x7a, 0x54, 0x95,
	0x1e, 0xbc, 0x82, 0x6e, 0x41, 0x62, 0xd7, 0xb1, 0xca, 0x2e, 0x93, 0xab, 0xf9, 0x45, 0xe1, 0xbd,
	0x0a, 0xe3, 0x8e, 0xd1, 0x87, 0x4b, 0x53, 0x98, 0xaf, 0x40, 0xe1, 0x73, 0xe8, 0xe5, 0xca, 0x24,
	0x36, 0x51, 0x19, 0x1b, 0x80, 0x57, 0x06, 0xca, 0xbb, 0x45, 0xb4, 0x2a, 0x8a, 0xbd, 0x15, 0xa2,
	0xbb, 0xc2, 0xf7, 0xde, 0xdd, 0x9b, 0xa3, 0xaf, 0x87, 0x49, 0x96, 0xd8, 0x44, 0xa4, 0xf6, 0x5a,
	0x4b, 0xe9, 0x3e, 0xe4, 0xb1, 0x4a, 0x27, 0xc6, 0xe0, 0xe7, 0xfc, 0x77, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x8f, 0xec, 0xd5, 0x8e, 0xdd, 0x05, 0x00, 0x00,
}
