// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ss/proto/rpc/move.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MoveReq struct {
	MapID                *int32    `protobuf:"varint,1,opt,name=mapID" json:"mapID,omitempty"`
	SceneIdx             *int32    `protobuf:"varint,2,opt,name=sceneIdx" json:"sceneIdx,omitempty"`
	UserID               *string   `protobuf:"bytes,3,opt,name=userID" json:"userID,omitempty"`
	RoleID               *uint64   `protobuf:"varint,4,opt,name=roleID" json:"roleID,omitempty"`
	Pos                  *Position `protobuf:"bytes,5,opt,name=pos" json:"pos,omitempty"`
	Angle                *int32    `protobuf:"varint,6,opt,name=angle" json:"angle,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MoveReq) Reset()         { *m = MoveReq{} }
func (m *MoveReq) String() string { return proto.CompactTextString(m) }
func (*MoveReq) ProtoMessage()    {}
func (*MoveReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_60fc40db01a3e07d, []int{0}
}

func (m *MoveReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveReq.Unmarshal(m, b)
}
func (m *MoveReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveReq.Marshal(b, m, deterministic)
}
func (m *MoveReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveReq.Merge(m, src)
}
func (m *MoveReq) XXX_Size() int {
	return xxx_messageInfo_MoveReq.Size(m)
}
func (m *MoveReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveReq.DiscardUnknown(m)
}

var xxx_messageInfo_MoveReq proto.InternalMessageInfo

func (m *MoveReq) GetMapID() int32 {
	if m != nil && m.MapID != nil {
		return *m.MapID
	}
	return 0
}

func (m *MoveReq) GetSceneIdx() int32 {
	if m != nil && m.SceneIdx != nil {
		return *m.SceneIdx
	}
	return 0
}

func (m *MoveReq) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *MoveReq) GetRoleID() uint64 {
	if m != nil && m.RoleID != nil {
		return *m.RoleID
	}
	return 0
}

func (m *MoveReq) GetPos() *Position {
	if m != nil {
		return m.Pos
	}
	return nil
}

func (m *MoveReq) GetAngle() int32 {
	if m != nil && m.Angle != nil {
		return *m.Angle
	}
	return 0
}

type MoveResp struct {
	Ok                   *bool     `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Pos                  *Position `protobuf:"bytes,2,opt,name=pos" json:"pos,omitempty"`
	Angle                *int32    `protobuf:"varint,3,opt,name=angle" json:"angle,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MoveResp) Reset()         { *m = MoveResp{} }
func (m *MoveResp) String() string { return proto.CompactTextString(m) }
func (*MoveResp) ProtoMessage()    {}
func (*MoveResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_60fc40db01a3e07d, []int{1}
}

func (m *MoveResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveResp.Unmarshal(m, b)
}
func (m *MoveResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveResp.Marshal(b, m, deterministic)
}
func (m *MoveResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveResp.Merge(m, src)
}
func (m *MoveResp) XXX_Size() int {
	return xxx_messageInfo_MoveResp.Size(m)
}
func (m *MoveResp) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveResp.DiscardUnknown(m)
}

var xxx_messageInfo_MoveResp proto.InternalMessageInfo

func (m *MoveResp) GetOk() bool {
	if m != nil && m.Ok != nil {
		return *m.Ok
	}
	return false
}

func (m *MoveResp) GetPos() *Position {
	if m != nil {
		return m.Pos
	}
	return nil
}

func (m *MoveResp) GetAngle() int32 {
	if m != nil && m.Angle != nil {
		return *m.Angle
	}
	return 0
}

func init() {
	proto.RegisterType((*MoveReq)(nil), "rpc.move_req")
	proto.RegisterType((*MoveResp)(nil), "rpc.move_resp")
}

func init() { proto.RegisterFile("ss/proto/rpc/move.proto", fileDescriptor_60fc40db01a3e07d) }

var fileDescriptor_60fc40db01a3e07d = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x49, 0xbb, 0x5d, 0xba, 0x11, 0x3d, 0x04, 0xd1, 0xb8, 0x88, 0x96, 0x3d, 0xf5, 0xd4,
	0x82, 0x8f, 0x20, 0xbd, 0xf4, 0x9a, 0xa3, 0x17, 0x29, 0x71, 0xd0, 0xb0, 0x6d, 0x26, 0xce, 0x54,
	0xf1, 0x7d, 0x7c, 0x51, 0x49, 0x53, 0x45, 0x4f, 0x1e, 0xbf, 0x7c, 0xe1, 0xe7, 0x63, 0xe4, 0x25,
	0x73, 0x1b, 0x08, 0x67, 0x6c, 0x29, 0xd8, 0x76, 0xc2, 0x77, 0x68, 0x16, 0x54, 0x39, 0x05, 0xbb,
	0xbf, 0xfa, 0x63, 0x2d, 0x4e, 0x13, 0xfa, 0xe4, 0x0f, 0x9f, 0x42, 0x96, 0xf1, 0xfb, 0x23, 0xc1,
	0xab, 0x3a, 0x97, 0xc5, 0x34, 0x84, 0xbe, 0xd3, 0xa2, 0x12, 0x75, 0x61, 0x12, 0xa8, 0xbd, 0x2c,
	0xd9, 0x82, 0x87, 0xfe, 0xe9, 0x43, 0x67, 0x8b, 0xf8, 0x61, 0x75, 0x21, 0xb7, 0x6f, 0x0c, 0xd4,
	0x77, 0x3a, 0xaf, 0x44, 0xbd, 0x33, 0x2b, 0xc5, 0x77, 0xc2, 0x11, 0xfa, 0x4e, 0x6f, 0x2a, 0x51,
	0x6f, 0xcc, 0x4a, 0xea, 0x56, 0xe6, 0x01, 0x59, 0x17, 0x95, 0xa8, 0x4f, 0xee, 0x4e, 0x1b, 0x0a,
	0xb6, 0x09, 0xc8, 0x6e, 0x76, 0xe8, 0x4d, 0x34, 0x31, 0x61, 0xf0, 0xcf, 0x23, 0xe8, 0x6d, 0x4a,
	0x58, 0xe0, 0x60, 0xe4, 0x6e, 0x8d, 0xe4, 0xa0, 0xce, 0x64, 0x86, 0xc7, 0x25, 0xb1, 0x34, 0x19,
	0x1e, 0xbf, 0x37, 0xb3, 0xff, 0x37, 0xf3, 0x5f, 0x9b, 0xf7, 0x37, 0x0f, 0xd7, 0xce, 0xbb, 0xd9,
	0x0d, 0xe3, 0xfc, 0x42, 0x00, 0xe9, 0x40, 0x16, 0xc7, 0x96, 0x39, 0x9e, 0xe9, 0x2b, 0x00, 0x00,
	0xff, 0xff, 0xc5, 0xe3, 0xd6, 0x93, 0x53, 0x01, 0x00, 0x00,
}
