// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ss/proto/rpc/rankSetScore.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	message "initialthree/protocol/cs/message"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RankSetScoreReq struct {
	RoleInfo             *message.RankRoleInfo `protobuf:"bytes,1,opt,name=roleInfo" json:"roleInfo,omitempty"`
	RankID               *int32                `protobuf:"varint,2,req,name=rankID" json:"rankID,omitempty"`
	RoleID               *uint64               `protobuf:"varint,3,req,name=roleID" json:"roleID,omitempty"`
	Score                *int32                `protobuf:"varint,4,req,name=score" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RankSetScoreReq) Reset()         { *m = RankSetScoreReq{} }
func (m *RankSetScoreReq) String() string { return proto.CompactTextString(m) }
func (*RankSetScoreReq) ProtoMessage()    {}
func (*RankSetScoreReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_eea21b7b9d5c864c, []int{0}
}

func (m *RankSetScoreReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RankSetScoreReq.Unmarshal(m, b)
}
func (m *RankSetScoreReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RankSetScoreReq.Marshal(b, m, deterministic)
}
func (m *RankSetScoreReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RankSetScoreReq.Merge(m, src)
}
func (m *RankSetScoreReq) XXX_Size() int {
	return xxx_messageInfo_RankSetScoreReq.Size(m)
}
func (m *RankSetScoreReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RankSetScoreReq.DiscardUnknown(m)
}

var xxx_messageInfo_RankSetScoreReq proto.InternalMessageInfo

func (m *RankSetScoreReq) GetRoleInfo() *message.RankRoleInfo {
	if m != nil {
		return m.RoleInfo
	}
	return nil
}

func (m *RankSetScoreReq) GetRankID() int32 {
	if m != nil && m.RankID != nil {
		return *m.RankID
	}
	return 0
}

func (m *RankSetScoreReq) GetRoleID() uint64 {
	if m != nil && m.RoleID != nil {
		return *m.RoleID
	}
	return 0
}

func (m *RankSetScoreReq) GetScore() int32 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

type RankSetScoreResp struct {
	Code                 *int32   `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Rank                 *int32   `protobuf:"varint,3,opt,name=rank" json:"rank,omitempty"`
	Total                *int32   `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RankSetScoreResp) Reset()         { *m = RankSetScoreResp{} }
func (m *RankSetScoreResp) String() string { return proto.CompactTextString(m) }
func (*RankSetScoreResp) ProtoMessage()    {}
func (*RankSetScoreResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_eea21b7b9d5c864c, []int{1}
}

func (m *RankSetScoreResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RankSetScoreResp.Unmarshal(m, b)
}
func (m *RankSetScoreResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RankSetScoreResp.Marshal(b, m, deterministic)
}
func (m *RankSetScoreResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RankSetScoreResp.Merge(m, src)
}
func (m *RankSetScoreResp) XXX_Size() int {
	return xxx_messageInfo_RankSetScoreResp.Size(m)
}
func (m *RankSetScoreResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RankSetScoreResp.DiscardUnknown(m)
}

var xxx_messageInfo_RankSetScoreResp proto.InternalMessageInfo

func (m *RankSetScoreResp) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *RankSetScoreResp) GetRank() int32 {
	if m != nil && m.Rank != nil {
		return *m.Rank
	}
	return 0
}

func (m *RankSetScoreResp) GetTotal() int32 {
	if m != nil && m.Total != nil {
		return *m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*RankSetScoreReq)(nil), "rpc.rankSetScore_req")
	proto.RegisterType((*RankSetScoreResp)(nil), "rpc.rankSetScore_resp")
}

func init() { proto.RegisterFile("ss/proto/rpc/rankSetScore.proto", fileDescriptor_eea21b7b9d5c864c) }

var fileDescriptor_eea21b7b9d5c864c = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x49, 0xdb, 0x15, 0x89, 0x17, 0x0d, 0x2a, 0x41, 0x44, 0xcb, 0x82, 0xd0, 0x53, 0x8b,
	0x3e, 0x82, 0x2c, 0xc8, 0x82, 0x17, 0xb3, 0x9e, 0xbc, 0x48, 0x88, 0xa3, 0x96, 0xd6, 0x4e, 0xcc,
	0xcc, 0x5b, 0xf8, 0xd2, 0x32, 0x69, 0x15, 0xf1, 0x36, 0xff, 0x97, 0x8f, 0x3f, 0xc3, 0xe8, 0x4b,
	0xa2, 0x2e, 0x26, 0x64, 0xec, 0x52, 0x0c, 0x5d, 0xf2, 0xd3, 0xb0, 0x03, 0xde, 0x05, 0x4c, 0xd0,
	0x66, 0x6c, 0xca, 0x14, 0xc3, 0xd9, 0x55, 0xf8, 0xb1, 0x3e, 0x80, 0xc8, 0xbf, 0x41, 0x36, 0xef,
	0x80, 0x1f, 0x31, 0xde, 0xf7, 0xc4, 0xb3, 0xbb, 0xfe, 0x52, 0xfa, 0xf0, 0x6f, 0xc5, 0x73, 0x82,
	0x4f, 0x73, 0xad, 0xf7, 0x13, 0x8e, 0xb0, 0x9d, 0x5e, 0xd1, 0xaa, 0x5a, 0x35, 0x07, 0x37, 0x27,
	0xed, 0xd2, 0xd2, 0x3a, 0x3f, 0x0d, 0x6e, 0x79, 0x74, 0xbf, 0x9a, 0x39, 0xd5, 0x7b, 0x52, 0xb3,
	0xdd, 0xd8, 0xa2, 0x2e, 0x9a, 0x95, 0x5b, 0x52, 0xe6, 0xe2, 0x6c, 0x6c, 0x59, 0x17, 0x4d, 0xe5,
	0x96, 0x64, 0x8e, 0xf5, 0x8a, 0xe4, 0x3f, 0x5b, 0x65, 0x7d, 0x0e, 0xeb, 0x07, 0x7d, 0xf4, 0x6f,
	0x19, 0x8a, 0xc6, 0xe8, 0x2a, 0xe0, 0x0b, 0x58, 0x95, 0xcd, 0x3c, 0x0b, 0x13, 0xd1, 0x96, 0xb5,
	0x12, 0x26, 0xb3, 0x54, 0x32, 0xb2, 0x1f, 0x6d, 0x91, 0xe1, 0x1c, 0x6e, 0x2f, 0x9e, 0xce, 0xfb,
	0xa9, 0xe7, 0xde, 0x8f, 0xfc, 0x9e, 0x00, 0xe6, 0x9b, 0x04, 0x1c, 0x3b, 0x22, 0xb9, 0xdf, 0x77,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xdd, 0xd7, 0xa6, 0xbb, 0x4e, 0x01, 0x00, 0x00,
}
