// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ss/proto/rpc/rankGetTopList.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	message "initialthree/protocol/cs/message"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RankGetTopListReq struct {
	Tos                  *message.RankGetTopListToS `protobuf:"bytes,1,req,name=tos" json:"tos,omitempty"`
	RoleID               *uint64                    `protobuf:"varint,2,req,name=roleID" json:"roleID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *RankGetTopListReq) Reset()         { *m = RankGetTopListReq{} }
func (m *RankGetTopListReq) String() string { return proto.CompactTextString(m) }
func (*RankGetTopListReq) ProtoMessage()    {}
func (*RankGetTopListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b72873a7b127985, []int{0}
}

func (m *RankGetTopListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RankGetTopListReq.Unmarshal(m, b)
}
func (m *RankGetTopListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RankGetTopListReq.Marshal(b, m, deterministic)
}
func (m *RankGetTopListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RankGetTopListReq.Merge(m, src)
}
func (m *RankGetTopListReq) XXX_Size() int {
	return xxx_messageInfo_RankGetTopListReq.Size(m)
}
func (m *RankGetTopListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RankGetTopListReq.DiscardUnknown(m)
}

var xxx_messageInfo_RankGetTopListReq proto.InternalMessageInfo

func (m *RankGetTopListReq) GetTos() *message.RankGetTopListToS {
	if m != nil {
		return m.Tos
	}
	return nil
}

func (m *RankGetTopListReq) GetRoleID() uint64 {
	if m != nil && m.RoleID != nil {
		return *m.RoleID
	}
	return 0
}

type RankGetTopListResp struct {
	RedirectRankAddr     *string                    `protobuf:"bytes,1,opt,name=redirectRankAddr" json:"redirectRankAddr,omitempty"`
	CurRankID            *int32                     `protobuf:"varint,2,opt,name=curRankID" json:"curRankID,omitempty"`
	Toc                  *message.RankGetTopListToC `protobuf:"bytes,3,opt,name=toc" json:"toc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *RankGetTopListResp) Reset()         { *m = RankGetTopListResp{} }
func (m *RankGetTopListResp) String() string { return proto.CompactTextString(m) }
func (*RankGetTopListResp) ProtoMessage()    {}
func (*RankGetTopListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b72873a7b127985, []int{1}
}

func (m *RankGetTopListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RankGetTopListResp.Unmarshal(m, b)
}
func (m *RankGetTopListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RankGetTopListResp.Marshal(b, m, deterministic)
}
func (m *RankGetTopListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RankGetTopListResp.Merge(m, src)
}
func (m *RankGetTopListResp) XXX_Size() int {
	return xxx_messageInfo_RankGetTopListResp.Size(m)
}
func (m *RankGetTopListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RankGetTopListResp.DiscardUnknown(m)
}

var xxx_messageInfo_RankGetTopListResp proto.InternalMessageInfo

func (m *RankGetTopListResp) GetRedirectRankAddr() string {
	if m != nil && m.RedirectRankAddr != nil {
		return *m.RedirectRankAddr
	}
	return ""
}

func (m *RankGetTopListResp) GetCurRankID() int32 {
	if m != nil && m.CurRankID != nil {
		return *m.CurRankID
	}
	return 0
}

func (m *RankGetTopListResp) GetToc() *message.RankGetTopListToC {
	if m != nil {
		return m.Toc
	}
	return nil
}

func init() {
	proto.RegisterType((*RankGetTopListReq)(nil), "rpc.rankGetTopList_req")
	proto.RegisterType((*RankGetTopListResp)(nil), "rpc.rankGetTopList_resp")
}

func init() { proto.RegisterFile("ss/proto/rpc/rankGetTopList.proto", fileDescriptor_4b72873a7b127985) }

var fileDescriptor_4b72873a7b127985 = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xdd, 0x4a, 0x03, 0x31,
	0x10, 0x85, 0xc9, 0xae, 0x0a, 0x8d, 0x37, 0x12, 0x41, 0x16, 0x2d, 0xb2, 0x16, 0x84, 0x20, 0xb8,
	0x01, 0xdf, 0xc0, 0x1f, 0x10, 0xc1, 0xab, 0xe8, 0x95, 0x5e, 0x48, 0x98, 0x1d, 0x34, 0x74, 0xdd,
	0xc4, 0x99, 0xf1, 0x35, 0x7c, 0x66, 0x49, 0x5b, 0x11, 0xad, 0x78, 0x39, 0x67, 0x3e, 0x0e, 0x1f,
	0x47, 0x1f, 0x31, 0xbb, 0x4c, 0x49, 0x92, 0xa3, 0x0c, 0x8e, 0xc2, 0x38, 0xbf, 0x46, 0xb9, 0x4f,
	0xf9, 0x36, 0xb2, 0x74, 0x8b, 0x87, 0xa9, 0x29, 0xc3, 0xfe, 0x31, 0x7c, 0x71, 0xaf, 0xc8, 0x1c,
	0x9e, 0xf1, 0x4f, 0x76, 0xf6, 0xa8, 0xcd, 0xcf, 0xfc, 0x89, 0xf0, 0xcd, 0x9c, 0xea, 0x5a, 0x12,
	0x37, 0xaa, 0xad, 0xec, 0xf6, 0xd9, 0x41, 0xb7, 0x6a, 0xe8, 0x7e, 0x91, 0x92, 0xee, 0x7c, 0xe1,
	0xcc, 0x9e, 0xde, 0xa2, 0x34, 0xe0, 0xcd, 0x55, 0x53, 0xb5, 0x95, 0xdd, 0xf0, 0xab, 0x6b, 0xf6,
	0xa1, 0xf4, 0xee, 0x5a, 0x3b, 0x67, 0x73, 0xa2, 0x77, 0x08, 0xfb, 0x48, 0x08, 0xe2, 0xc3, 0x38,
	0x3f, 0xef, 0x7b, 0x6a, 0x54, 0xab, 0xec, 0xc4, 0xaf, 0xe5, 0x66, 0xaa, 0x27, 0xf0, 0x4e, 0xe5,
	0x5c, 0xd4, 0x2b, 0xbb, 0xe9, 0xbf, 0x83, 0xa5, 0x28, 0x34, 0x75, 0xab, 0xfe, 0x17, 0xbd, 0x2c,
	0xa2, 0x70, 0x71, 0xf8, 0x30, 0x8d, 0x63, 0x94, 0x18, 0x06, 0x79, 0x21, 0xc4, 0xe5, 0x40, 0x90,
	0x06, 0xc7, 0x5c, 0xe6, 0xfc, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xca, 0xe8, 0x35, 0xd6, 0x5d, 0x01,
	0x00, 0x00,
}
