// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ss/proto/rpc/teamJoinReply.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	message "initialthree/protocol/cs/message"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TeamJoinReplyReq struct {
	Agree                *bool    `protobuf:"varint,1,opt,name=agree" json:"agree,omitempty"`
	AgreeID              *uint64  `protobuf:"varint,2,opt,name=agreeID" json:"agreeID,omitempty"`
	TeamID               *uint32  `protobuf:"varint,3,req,name=teamID" json:"teamID,omitempty"`
	MineID               *uint64  `protobuf:"varint,4,req,name=mineID" json:"mineID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeamJoinReplyReq) Reset()         { *m = TeamJoinReplyReq{} }
func (m *TeamJoinReplyReq) String() string { return proto.CompactTextString(m) }
func (*TeamJoinReplyReq) ProtoMessage()    {}
func (*TeamJoinReplyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_636d0eb833e53b1f, []int{0}
}

func (m *TeamJoinReplyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamJoinReplyReq.Unmarshal(m, b)
}
func (m *TeamJoinReplyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamJoinReplyReq.Marshal(b, m, deterministic)
}
func (m *TeamJoinReplyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamJoinReplyReq.Merge(m, src)
}
func (m *TeamJoinReplyReq) XXX_Size() int {
	return xxx_messageInfo_TeamJoinReplyReq.Size(m)
}
func (m *TeamJoinReplyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamJoinReplyReq.DiscardUnknown(m)
}

var xxx_messageInfo_TeamJoinReplyReq proto.InternalMessageInfo

func (m *TeamJoinReplyReq) GetAgree() bool {
	if m != nil && m.Agree != nil {
		return *m.Agree
	}
	return false
}

func (m *TeamJoinReplyReq) GetAgreeID() uint64 {
	if m != nil && m.AgreeID != nil {
		return *m.AgreeID
	}
	return 0
}

func (m *TeamJoinReplyReq) GetTeamID() uint32 {
	if m != nil && m.TeamID != nil {
		return *m.TeamID
	}
	return 0
}

func (m *TeamJoinReplyReq) GetMineID() uint64 {
	if m != nil && m.MineID != nil {
		return *m.MineID
	}
	return 0
}

type TeamJoinReplyResp struct {
	ErrCode              *message.ErrCode `protobuf:"varint,1,req,name=errCode,enum=message.ErrCode" json:"errCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *TeamJoinReplyResp) Reset()         { *m = TeamJoinReplyResp{} }
func (m *TeamJoinReplyResp) String() string { return proto.CompactTextString(m) }
func (*TeamJoinReplyResp) ProtoMessage()    {}
func (*TeamJoinReplyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_636d0eb833e53b1f, []int{1}
}

func (m *TeamJoinReplyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamJoinReplyResp.Unmarshal(m, b)
}
func (m *TeamJoinReplyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamJoinReplyResp.Marshal(b, m, deterministic)
}
func (m *TeamJoinReplyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamJoinReplyResp.Merge(m, src)
}
func (m *TeamJoinReplyResp) XXX_Size() int {
	return xxx_messageInfo_TeamJoinReplyResp.Size(m)
}
func (m *TeamJoinReplyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamJoinReplyResp.DiscardUnknown(m)
}

var xxx_messageInfo_TeamJoinReplyResp proto.InternalMessageInfo

func (m *TeamJoinReplyResp) GetErrCode() message.ErrCode {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return message.ErrCode_OK
}

func init() {
	proto.RegisterType((*TeamJoinReplyReq)(nil), "rpc.teamJoinReply_req")
	proto.RegisterType((*TeamJoinReplyResp)(nil), "rpc.teamJoinReply_resp")
}

func init() { proto.RegisterFile("ss/proto/rpc/teamJoinReply.proto", fileDescriptor_636d0eb833e53b1f) }

var fileDescriptor_636d0eb833e53b1f = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0x69, 0xb6, 0xba, 0x12, 0x50, 0x34, 0x88, 0x04, 0x11, 0x0d, 0x7b, 0x0a, 0x1e, 0x1a,
	0xf0, 0x17, 0x88, 0xae, 0x87, 0xf5, 0x98, 0xa3, 0x17, 0x09, 0x71, 0xa8, 0x81, 0xb6, 0x89, 0x33,
	0xb9, 0xf8, 0xef, 0x25, 0x4d, 0x7b, 0x70, 0x6f, 0xf9, 0x1e, 0xef, 0xe5, 0xcd, 0x0c, 0x57, 0x44,
	0x26, 0x61, 0xcc, 0xd1, 0x60, 0xf2, 0x26, 0x83, 0x1b, 0xdf, 0x63, 0x98, 0x2c, 0xa4, 0xe1, 0xb7,
	0x9b, 0x75, 0xb1, 0xc1, 0xe4, 0x6f, 0x1f, 0xfc, 0x6a, 0x1b, 0x81, 0xc8, 0xf5, 0x60, 0x00, 0x11,
	0x10, 0x23, 0x56, 0xd7, 0x8e, 0xf8, 0xd5, 0xbf, 0xf0, 0x27, 0xc2, 0x8f, 0xb8, 0xe6, 0x27, 0xae,
	0x47, 0x00, 0xd9, 0xa8, 0x46, 0x9f, 0xd9, 0x0a, 0x42, 0xf2, 0xed, 0xfc, 0x38, 0xec, 0x25, 0x53,
	0x8d, 0x6e, 0xed, 0x8a, 0xe2, 0x86, 0x9f, 0x96, 0x4f, 0x0e, 0x7b, 0xb9, 0x51, 0x4c, 0x9f, 0xdb,
	0x85, 0x8a, 0x3e, 0x86, 0xa9, 0x04, 0x5a, 0xc5, 0x74, 0x6b, 0x17, 0xda, 0x3d, 0x73, 0x71, 0x5c,
	0x4a, 0x49, 0x3c, 0xf2, 0x2d, 0x20, 0xbe, 0xc6, 0xaf, 0xd2, 0xcb, 0xf4, 0xc5, 0xd3, 0x65, 0xb7,
	0x0c, 0xdd, 0xbd, 0x55, 0xdd, 0xae, 0x86, 0x97, 0xfb, 0x8f, 0xbb, 0x30, 0x85, 0x1c, 0xdc, 0x90,
	0xbf, 0x11, 0xa0, 0xee, 0xe8, 0xe3, 0x60, 0x88, 0xca, 0x41, 0xfe, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x51, 0xcc, 0xba, 0xe1, 0x1f, 0x01, 0x00, 0x00,
}
