// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ss/proto/rpc/worldObjPush.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PushType int32

const (
	PushType_EnterMap PushType = 1
	PushType_LeaveMap PushType = 2
	PushType_DoAction PushType = 3
)

var PushType_name = map[int32]string{
	1: "EnterMap",
	2: "LeaveMap",
	3: "DoAction",
}

var PushType_value = map[string]int32{
	"EnterMap": 1,
	"LeaveMap": 2,
	"DoAction": 3,
}

func (x PushType) Enum() *PushType {
	p := new(PushType)
	*p = x
	return p
}

func (x PushType) String() string {
	return proto.EnumName(PushType_name, int32(x))
}

func (x *PushType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PushType_value, data, "PushType")
	if err != nil {
		return err
	}
	*x = PushType(value)
	return nil
}

func (PushType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7daec312a41fdd75, []int{0}
}

type WorldObjPushReq struct {
	T                    *PushType   `protobuf:"varint,1,req,name=t,enum=rpc.PushType" json:"t,omitempty"`
	Enter                *WOEnterMap `protobuf:"bytes,2,opt,name=enter" json:"enter,omitempty"`
	Leave                *WOLeaveMap `protobuf:"bytes,3,opt,name=leave" json:"leave,omitempty"`
	Do                   *WODoAction `protobuf:"bytes,4,opt,name=do" json:"do,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *WorldObjPushReq) Reset()         { *m = WorldObjPushReq{} }
func (m *WorldObjPushReq) String() string { return proto.CompactTextString(m) }
func (*WorldObjPushReq) ProtoMessage()    {}
func (*WorldObjPushReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7daec312a41fdd75, []int{0}
}

func (m *WorldObjPushReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorldObjPushReq.Unmarshal(m, b)
}
func (m *WorldObjPushReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorldObjPushReq.Marshal(b, m, deterministic)
}
func (m *WorldObjPushReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorldObjPushReq.Merge(m, src)
}
func (m *WorldObjPushReq) XXX_Size() int {
	return xxx_messageInfo_WorldObjPushReq.Size(m)
}
func (m *WorldObjPushReq) XXX_DiscardUnknown() {
	xxx_messageInfo_WorldObjPushReq.DiscardUnknown(m)
}

var xxx_messageInfo_WorldObjPushReq proto.InternalMessageInfo

func (m *WorldObjPushReq) GetT() PushType {
	if m != nil && m.T != nil {
		return *m.T
	}
	return PushType_EnterMap
}

func (m *WorldObjPushReq) GetEnter() *WOEnterMap {
	if m != nil {
		return m.Enter
	}
	return nil
}

func (m *WorldObjPushReq) GetLeave() *WOLeaveMap {
	if m != nil {
		return m.Leave
	}
	return nil
}

func (m *WorldObjPushReq) GetDo() *WODoAction {
	if m != nil {
		return m.Do
	}
	return nil
}

type WOEnterMap struct {
	UserID               *string   `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	ID                   *uint64   `protobuf:"varint,2,opt,name=ID" json:"ID,omitempty"`
	Pos                  *Position `protobuf:"bytes,3,opt,name=pos" json:"pos,omitempty"`
	WorldAddr            *string   `protobuf:"bytes,4,opt,name=worldAddr" json:"worldAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *WOEnterMap) Reset()         { *m = WOEnterMap{} }
func (m *WOEnterMap) String() string { return proto.CompactTextString(m) }
func (*WOEnterMap) ProtoMessage()    {}
func (*WOEnterMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_7daec312a41fdd75, []int{1}
}

func (m *WOEnterMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WOEnterMap.Unmarshal(m, b)
}
func (m *WOEnterMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WOEnterMap.Marshal(b, m, deterministic)
}
func (m *WOEnterMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WOEnterMap.Merge(m, src)
}
func (m *WOEnterMap) XXX_Size() int {
	return xxx_messageInfo_WOEnterMap.Size(m)
}
func (m *WOEnterMap) XXX_DiscardUnknown() {
	xxx_messageInfo_WOEnterMap.DiscardUnknown(m)
}

var xxx_messageInfo_WOEnterMap proto.InternalMessageInfo

func (m *WOEnterMap) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *WOEnterMap) GetID() uint64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *WOEnterMap) GetPos() *Position {
	if m != nil {
		return m.Pos
	}
	return nil
}

func (m *WOEnterMap) GetWorldAddr() string {
	if m != nil && m.WorldAddr != nil {
		return *m.WorldAddr
	}
	return ""
}

type WOLeaveMap struct {
	UserID               *string  `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WOLeaveMap) Reset()         { *m = WOLeaveMap{} }
func (m *WOLeaveMap) String() string { return proto.CompactTextString(m) }
func (*WOLeaveMap) ProtoMessage()    {}
func (*WOLeaveMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_7daec312a41fdd75, []int{2}
}

func (m *WOLeaveMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WOLeaveMap.Unmarshal(m, b)
}
func (m *WOLeaveMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WOLeaveMap.Marshal(b, m, deterministic)
}
func (m *WOLeaveMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WOLeaveMap.Merge(m, src)
}
func (m *WOLeaveMap) XXX_Size() int {
	return xxx_messageInfo_WOLeaveMap.Size(m)
}
func (m *WOLeaveMap) XXX_DiscardUnknown() {
	xxx_messageInfo_WOLeaveMap.DiscardUnknown(m)
}

var xxx_messageInfo_WOLeaveMap proto.InternalMessageInfo

func (m *WOLeaveMap) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

type WODoAction struct {
	UserID               *string   `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	UpdatePos            *Position `protobuf:"bytes,2,opt,name=updatePos" json:"updatePos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *WODoAction) Reset()         { *m = WODoAction{} }
func (m *WODoAction) String() string { return proto.CompactTextString(m) }
func (*WODoAction) ProtoMessage()    {}
func (*WODoAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_7daec312a41fdd75, []int{3}
}

func (m *WODoAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WODoAction.Unmarshal(m, b)
}
func (m *WODoAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WODoAction.Marshal(b, m, deterministic)
}
func (m *WODoAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WODoAction.Merge(m, src)
}
func (m *WODoAction) XXX_Size() int {
	return xxx_messageInfo_WODoAction.Size(m)
}
func (m *WODoAction) XXX_DiscardUnknown() {
	xxx_messageInfo_WODoAction.DiscardUnknown(m)
}

var xxx_messageInfo_WODoAction proto.InternalMessageInfo

func (m *WODoAction) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *WODoAction) GetUpdatePos() *Position {
	if m != nil {
		return m.UpdatePos
	}
	return nil
}

type WorldObjPushResp struct {
	Ok                   *bool    `protobuf:"varint,1,req,name=ok" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorldObjPushResp) Reset()         { *m = WorldObjPushResp{} }
func (m *WorldObjPushResp) String() string { return proto.CompactTextString(m) }
func (*WorldObjPushResp) ProtoMessage()    {}
func (*WorldObjPushResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_7daec312a41fdd75, []int{4}
}

func (m *WorldObjPushResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorldObjPushResp.Unmarshal(m, b)
}
func (m *WorldObjPushResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorldObjPushResp.Marshal(b, m, deterministic)
}
func (m *WorldObjPushResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorldObjPushResp.Merge(m, src)
}
func (m *WorldObjPushResp) XXX_Size() int {
	return xxx_messageInfo_WorldObjPushResp.Size(m)
}
func (m *WorldObjPushResp) XXX_DiscardUnknown() {
	xxx_messageInfo_WorldObjPushResp.DiscardUnknown(m)
}

var xxx_messageInfo_WorldObjPushResp proto.InternalMessageInfo

func (m *WorldObjPushResp) GetOk() bool {
	if m != nil && m.Ok != nil {
		return *m.Ok
	}
	return false
}

func init() {
	proto.RegisterEnum("rpc.PushType", PushType_name, PushType_value)
	proto.RegisterType((*WorldObjPushReq)(nil), "rpc.worldObjPush_req")
	proto.RegisterType((*WOEnterMap)(nil), "rpc.WOEnterMap")
	proto.RegisterType((*WOLeaveMap)(nil), "rpc.WOLeaveMap")
	proto.RegisterType((*WODoAction)(nil), "rpc.WODoAction")
	proto.RegisterType((*WorldObjPushResp)(nil), "rpc.worldObjPush_resp")
}

func init() { proto.RegisterFile("ss/proto/rpc/worldObjPush.proto", fileDescriptor_7daec312a41fdd75) }

var fileDescriptor_7daec312a41fdd75 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x5d, 0x4b, 0xeb, 0x40,
	0x14, 0x64, 0x37, 0xbd, 0x97, 0xe6, 0xdc, 0x6b, 0x8d, 0xfb, 0x20, 0x51, 0x8b, 0x2d, 0x51, 0xa1,
	0x28, 0x34, 0x50, 0xfc, 0x03, 0x95, 0xf8, 0x50, 0x50, 0x5a, 0x83, 0x20, 0xf8, 0x22, 0x31, 0x59,
	0x68, 0x6c, 0x9a, 0xb3, 0xee, 0x6e, 0x14, 0xff, 0x8c, 0xbf, 0x55, 0x76, 0x9b, 0x50, 0x5b, 0xe8,
	0xe3, 0x99, 0x99, 0xdd, 0x99, 0xf3, 0x01, 0x3d, 0xa5, 0x42, 0x21, 0x51, 0x63, 0x28, 0x45, 0x1a,
	0x7e, 0xa2, 0x2c, 0xb2, 0xe9, 0xeb, 0xdb, 0xac, 0x52, 0xf3, 0xa1, 0x85, 0x99, 0x23, 0x45, 0x7a,
	0x7c, 0xb4, 0xa1, 0x4a, 0x71, 0xb9, 0xc4, 0x72, 0xc5, 0x07, 0xdf, 0x04, 0xbc, 0xdf, 0xcf, 0x5e,
	0x24, 0x7f, 0x67, 0x27, 0x40, 0xb4, 0x4f, 0xfa, 0x74, 0xd0, 0x19, 0xed, 0x0d, 0xa5, 0x48, 0x87,
	0xa2, 0x52, 0xf3, 0xc7, 0x2f, 0xc1, 0x63, 0xa2, 0xd9, 0x05, 0xfc, 0xe1, 0xa5, 0xe6, 0xd2, 0xa7,
	0x7d, 0x32, 0xf8, 0x37, 0xda, 0xb7, 0x82, 0xa7, 0xe9, 0xad, 0xc1, 0xee, 0x13, 0x11, 0xaf, 0x58,
	0x23, 0x2b, 0x78, 0xf2, 0xc1, 0x7d, 0x67, 0x43, 0x76, 0x67, 0x30, 0x2b, 0xb3, 0x2c, 0xeb, 0x01,
	0xcd, 0xd0, 0x6f, 0x6d, 0x68, 0x22, 0x1c, 0xa7, 0x3a, 0xc7, 0x32, 0xa6, 0x19, 0x06, 0x0a, 0x60,
	0xfd, 0x39, 0x3b, 0x84, 0xbf, 0x95, 0xe2, 0x72, 0x12, 0xf9, 0xa4, 0x4f, 0x06, 0x6e, 0x5c, 0x57,
	0xac, 0x03, 0x74, 0x12, 0xd9, 0x44, 0xad, 0x98, 0x4e, 0x22, 0xd6, 0x03, 0x47, 0xa0, 0xaa, 0xbd,
	0xeb, 0x1e, 0x50, 0xe5, 0xf6, 0x57, 0xc3, 0xb0, 0x2e, 0xb8, 0xb6, 0xed, 0x71, 0x96, 0x49, 0x6b,
	0xef, 0xc6, 0x6b, 0x20, 0x38, 0x37, 0xa6, 0x4d, 0xd4, 0x5d, 0xa6, 0xc1, 0x83, 0x51, 0x35, 0x61,
	0x77, 0x46, 0xbb, 0x02, 0xb7, 0x12, 0x59, 0xa2, 0xf9, 0x0c, 0x55, 0x3d, 0xb3, 0xad, 0x40, 0x6b,
	0x3e, 0x38, 0x83, 0x83, 0xad, 0x6d, 0x28, 0x61, 0x9a, 0xc3, 0x85, 0xdd, 0x47, 0x3b, 0xa6, 0xb8,
	0xb8, 0xbc, 0x86, 0x76, 0xb3, 0x10, 0xf6, 0x1f, 0xda, 0xcd, 0x70, 0x3c, 0x62, 0xaa, 0x26, 0xb5,
	0x47, 0x4d, 0xd5, 0xa4, 0xf3, 0x9c, 0x9b, 0xd3, 0xe7, 0x6e, 0x5e, 0xe6, 0x3a, 0x4f, 0x0a, 0x3d,
	0x97, 0x9c, 0xaf, 0x0e, 0x22, 0xc5, 0x22, 0x54, 0xca, 0x9c, 0xc5, 0x4f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xcd, 0xfb, 0x49, 0x02, 0x4b, 0x02, 0x00, 0x00,
}
