// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs/proto/message/assetSync.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 资源类型枚举值会存放在数据库中，此处不允许更改枚举值对应的类型，避免数据库中存放的数据错乱
type AssetType int32

const (
	AssetType_ShopFirstPay AssetType = 1
	AssetType_Teaching     AssetType = 3
)

var AssetType_name = map[int32]string{
	1: "ShopFirstPay",
	3: "Teaching",
}

var AssetType_value = map[string]int32{
	"ShopFirstPay": 1,
	"Teaching":     3,
}

func (x AssetType) Enum() *AssetType {
	p := new(AssetType)
	*p = x
	return p
}

func (x AssetType) String() string {
	return proto.EnumName(AssetType_name, int32(x))
}

func (x *AssetType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AssetType_value, data, "AssetType")
	if err != nil {
		return err
	}
	*x = AssetType(value)
	return nil
}

func (AssetType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_335b03170dd402af, []int{0}
}

type Asset struct {
	Type                 *int32        `protobuf:"varint,1,opt,name=Type" json:"Type,omitempty"`
	AssetKv              []*AssetValue `protobuf:"bytes,2,rep,name=assetKv" json:"assetKv,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Asset) Reset()         { *m = Asset{} }
func (m *Asset) String() string { return proto.CompactTextString(m) }
func (*Asset) ProtoMessage()    {}
func (*Asset) Descriptor() ([]byte, []int) {
	return fileDescriptor_335b03170dd402af, []int{0}
}

func (m *Asset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Asset.Unmarshal(m, b)
}
func (m *Asset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Asset.Marshal(b, m, deterministic)
}
func (m *Asset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Asset.Merge(m, src)
}
func (m *Asset) XXX_Size() int {
	return xxx_messageInfo_Asset.Size(m)
}
func (m *Asset) XXX_DiscardUnknown() {
	xxx_messageInfo_Asset.DiscardUnknown(m)
}

var xxx_messageInfo_Asset proto.InternalMessageInfo

func (m *Asset) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Asset) GetAssetKv() []*AssetValue {
	if m != nil {
		return m.AssetKv
	}
	return nil
}

type AssetValue struct {
	ID                   *int32   `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Count                *int32   `protobuf:"varint,2,opt,name=Count" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssetValue) Reset()         { *m = AssetValue{} }
func (m *AssetValue) String() string { return proto.CompactTextString(m) }
func (*AssetValue) ProtoMessage()    {}
func (*AssetValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_335b03170dd402af, []int{1}
}

func (m *AssetValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssetValue.Unmarshal(m, b)
}
func (m *AssetValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssetValue.Marshal(b, m, deterministic)
}
func (m *AssetValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetValue.Merge(m, src)
}
func (m *AssetValue) XXX_Size() int {
	return xxx_messageInfo_AssetValue.Size(m)
}
func (m *AssetValue) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetValue.DiscardUnknown(m)
}

var xxx_messageInfo_AssetValue proto.InternalMessageInfo

func (m *AssetValue) GetID() int32 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *AssetValue) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

type AssetSyncToS struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssetSyncToS) Reset()         { *m = AssetSyncToS{} }
func (m *AssetSyncToS) String() string { return proto.CompactTextString(m) }
func (*AssetSyncToS) ProtoMessage()    {}
func (*AssetSyncToS) Descriptor() ([]byte, []int) {
	return fileDescriptor_335b03170dd402af, []int{2}
}

func (m *AssetSyncToS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssetSyncToS.Unmarshal(m, b)
}
func (m *AssetSyncToS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssetSyncToS.Marshal(b, m, deterministic)
}
func (m *AssetSyncToS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetSyncToS.Merge(m, src)
}
func (m *AssetSyncToS) XXX_Size() int {
	return xxx_messageInfo_AssetSyncToS.Size(m)
}
func (m *AssetSyncToS) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetSyncToS.DiscardUnknown(m)
}

var xxx_messageInfo_AssetSyncToS proto.InternalMessageInfo

// 可以由客户端拉取，服务器也会在有变更时主动同步
type AssetSyncToC struct {
	IsAll                *bool    `protobuf:"varint,1,opt,name=isAll" json:"isAll,omitempty"`
	SyncAssets           []*Asset `protobuf:"bytes,2,rep,name=syncAssets" json:"syncAssets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssetSyncToC) Reset()         { *m = AssetSyncToC{} }
func (m *AssetSyncToC) String() string { return proto.CompactTextString(m) }
func (*AssetSyncToC) ProtoMessage()    {}
func (*AssetSyncToC) Descriptor() ([]byte, []int) {
	return fileDescriptor_335b03170dd402af, []int{3}
}

func (m *AssetSyncToC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssetSyncToC.Unmarshal(m, b)
}
func (m *AssetSyncToC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssetSyncToC.Marshal(b, m, deterministic)
}
func (m *AssetSyncToC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetSyncToC.Merge(m, src)
}
func (m *AssetSyncToC) XXX_Size() int {
	return xxx_messageInfo_AssetSyncToC.Size(m)
}
func (m *AssetSyncToC) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetSyncToC.DiscardUnknown(m)
}

var xxx_messageInfo_AssetSyncToC proto.InternalMessageInfo

func (m *AssetSyncToC) GetIsAll() bool {
	if m != nil && m.IsAll != nil {
		return *m.IsAll
	}
	return false
}

func (m *AssetSyncToC) GetSyncAssets() []*Asset {
	if m != nil {
		return m.SyncAssets
	}
	return nil
}

func init() {
	proto.RegisterEnum("message.AssetType", AssetType_name, AssetType_value)
	proto.RegisterType((*Asset)(nil), "message.asset")
	proto.RegisterType((*AssetValue)(nil), "message.assetValue")
	proto.RegisterType((*AssetSyncToS)(nil), "message.assetSync_toS")
	proto.RegisterType((*AssetSyncToC)(nil), "message.assetSync_toC")
}

func init() { proto.RegisterFile("cs/proto/message/assetSync.proto", fileDescriptor_335b03170dd402af) }

var fileDescriptor_335b03170dd402af = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x49, 0x6a, 0x68, 0x1d, 0x6b, 0x0d, 0xab, 0x87, 0x1c, 0xc3, 0x9e, 0x8a, 0x62, 0x02,
	0xfd, 0x07, 0xb5, 0x45, 0xa8, 0x5e, 0x24, 0xa9, 0x1e, 0xbc, 0xc8, 0xb2, 0x2c, 0xcd, 0xc2, 0xba,
	0x1b, 0x32, 0x5b, 0x21, 0xff, 0x5e, 0x3a, 0xd9, 0x6a, 0x7b, 0x9b, 0xf9, 0xde, 0x9b, 0xe1, 0xcd,
	0x40, 0x2e, 0xb1, 0x6c, 0x3b, 0xe7, 0x5d, 0xf9, 0xad, 0x10, 0xc5, 0x4e, 0x95, 0x02, 0x51, 0xf9,
	0xba, 0xb7, 0xb2, 0x20, 0xce, 0xc6, 0x41, 0xe0, 0x2f, 0x90, 0x90, 0xc6, 0x18, 0x5c, 0x6c, 0xfb,
	0x56, 0x65, 0x51, 0x1e, 0xcd, 0x93, 0x8a, 0x6a, 0xf6, 0x08, 0x63, 0x12, 0x5f, 0x7f, 0xb2, 0x38,
	0x1f, 0xcd, 0xaf, 0x16, 0xb7, 0x45, 0x98, 0x2b, 0x88, 0x7f, 0x08, 0xb3, 0x57, 0xd5, 0xd1, 0xc3,
	0x17, 0x00, 0xff, 0x98, 0xcd, 0x20, 0xde, 0xac, 0xc3, 0xba, 0x78, 0xb3, 0x66, 0x77, 0x90, 0xac,
	0xdc, 0xde, 0xfa, 0x2c, 0x26, 0x34, 0x34, 0xfc, 0x06, 0xae, 0xff, 0xb2, 0x7d, 0x79, 0x57, 0xf3,
	0xf7, 0x73, 0xb0, 0x3a, 0xcc, 0x69, 0x5c, 0x1a, 0x43, 0xab, 0x26, 0xd5, 0xd0, 0xb0, 0x02, 0x00,
	0x7b, 0x2b, 0x97, 0x07, 0x2b, 0x86, 0x74, 0xb3, 0xf3, 0x74, 0xd5, 0x89, 0xe3, 0xfe, 0x01, 0x2e,
	0xa9, 0xa2, 0xbb, 0x52, 0x98, 0xd6, 0x8d, 0x6b, 0x9f, 0x75, 0x87, 0xfe, 0x4d, 0xf4, 0x69, 0xc4,
	0xa6, 0x30, 0xd9, 0x2a, 0x21, 0x1b, 0x6d, 0x77, 0xe9, 0xe8, 0x89, 0x7f, 0xe6, 0xda, 0x6a, 0xaf,
	0x85, 0xf1, 0x4d, 0xa7, 0xd4, 0xf0, 0x4b, 0xe9, 0x4c, 0x29, 0xf1, 0xf8, 0xd1, 0xdf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xf0, 0x33, 0x3e, 0x62, 0x64, 0x01, 0x00, 0x00,
}
