// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs/proto/message/backpack.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 背包格子
type BackpackEntity struct {
	Tid                  *int32   `protobuf:"varint,1,opt,name=tid" json:"tid,omitempty"`
	Id                   *uint32  `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Count                *int32   `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
	ExpireTime           *int64   `protobuf:"varint,4,opt,name=expireTime" json:"expireTime,omitempty"`
	AcquireTime          *int64   `protobuf:"varint,5,opt,name=acquireTime" json:"acquireTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackpackEntity) Reset()         { *m = BackpackEntity{} }
func (m *BackpackEntity) String() string { return proto.CompactTextString(m) }
func (*BackpackEntity) ProtoMessage()    {}
func (*BackpackEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_98e203257a7a7e38, []int{0}
}

func (m *BackpackEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackpackEntity.Unmarshal(m, b)
}
func (m *BackpackEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackpackEntity.Marshal(b, m, deterministic)
}
func (m *BackpackEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackpackEntity.Merge(m, src)
}
func (m *BackpackEntity) XXX_Size() int {
	return xxx_messageInfo_BackpackEntity.Size(m)
}
func (m *BackpackEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_BackpackEntity.DiscardUnknown(m)
}

var xxx_messageInfo_BackpackEntity proto.InternalMessageInfo

func (m *BackpackEntity) GetTid() int32 {
	if m != nil && m.Tid != nil {
		return *m.Tid
	}
	return 0
}

func (m *BackpackEntity) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *BackpackEntity) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *BackpackEntity) GetExpireTime() int64 {
	if m != nil && m.ExpireTime != nil {
		return *m.ExpireTime
	}
	return 0
}

func (m *BackpackEntity) GetAcquireTime() int64 {
	if m != nil && m.AcquireTime != nil {
		return *m.AcquireTime
	}
	return 0
}

func init() {
	proto.RegisterType((*BackpackEntity)(nil), "message.backpackEntity")
}

func init() { proto.RegisterFile("cs/proto/message/backpack.proto", fileDescriptor_98e203257a7a7e38) }

var fileDescriptor_98e203257a7a7e38 = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x4f, 0xca, 0xc2, 0x30,
	0x10, 0x47, 0x49, 0xfb, 0x95, 0x0f, 0x46, 0x2c, 0x12, 0x5c, 0x64, 0xa5, 0xa1, 0xab, 0xae, 0xcc,
	0x1d, 0x04, 0x2f, 0x50, 0x5c, 0xb9, 0x8b, 0xe9, 0xa0, 0x43, 0xff, 0xa4, 0x36, 0x53, 0xd0, 0x2b,
	0x78, 0x6a, 0xb1, 0xb5, 0xd0, 0xdd, 0xcc, 0xfb, 0xbd, 0xcd, 0x83, 0xbd, 0x0b, 0xa6, 0xeb, 0x3d,
	0x7b, 0xd3, 0x60, 0x08, 0xf6, 0x86, 0xe6, 0x6a, 0x5d, 0xd5, 0x59, 0x57, 0x1d, 0x46, 0x2c, 0xff,
	0x7f, 0x3c, 0x7b, 0x0b, 0x48, 0xe7, 0xed, 0xd4, 0x32, 0xf1, 0x4b, 0x6e, 0x20, 0x66, 0x2a, 0x95,
	0xd0, 0x22, 0x4f, 0x8a, 0xef, 0x29, 0x53, 0x88, 0xa8, 0x54, 0x91, 0x16, 0xf9, 0xba, 0x88, 0xa8,
	0x94, 0x5b, 0x48, 0x9c, 0x1f, 0x5a, 0x56, 0xf1, 0xe8, 0x4c, 0x8f, 0xdc, 0x01, 0xe0, 0xb3, 0xa3,
	0x1e, 0xcf, 0xd4, 0xa0, 0xfa, 0xd3, 0x22, 0x8f, 0x8b, 0x05, 0x91, 0x1a, 0x56, 0xd6, 0x3d, 0x86,
	0x59, 0x48, 0x46, 0x61, 0x89, 0x8e, 0xd9, 0x45, 0x53, 0x4b, 0x4c, 0xb6, 0xe6, 0x7b, 0x8f, 0x38,
	0x25, 0x38, 0x5f, 0x1b, 0x17, 0xe6, 0x90, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x39, 0xbe,
	0x4d, 0xdb, 0x00, 0x00, 0x00,
}
