// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs/proto/message/baseSetPortraitFrameCard.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BaseSetPortraitFrameCardToS struct {
	Portrait             *int32   `protobuf:"varint,1,opt,name=Portrait" json:"Portrait,omitempty"`
	PortraitFrame        *int32   `protobuf:"varint,2,opt,name=PortraitFrame" json:"PortraitFrame,omitempty"`
	Card                 *int32   `protobuf:"varint,3,opt,name=Card" json:"Card,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseSetPortraitFrameCardToS) Reset()         { *m = BaseSetPortraitFrameCardToS{} }
func (m *BaseSetPortraitFrameCardToS) String() string { return proto.CompactTextString(m) }
func (*BaseSetPortraitFrameCardToS) ProtoMessage()    {}
func (*BaseSetPortraitFrameCardToS) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6c1c99a3acbf74d, []int{0}
}

func (m *BaseSetPortraitFrameCardToS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseSetPortraitFrameCardToS.Unmarshal(m, b)
}
func (m *BaseSetPortraitFrameCardToS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseSetPortraitFrameCardToS.Marshal(b, m, deterministic)
}
func (m *BaseSetPortraitFrameCardToS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseSetPortraitFrameCardToS.Merge(m, src)
}
func (m *BaseSetPortraitFrameCardToS) XXX_Size() int {
	return xxx_messageInfo_BaseSetPortraitFrameCardToS.Size(m)
}
func (m *BaseSetPortraitFrameCardToS) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseSetPortraitFrameCardToS.DiscardUnknown(m)
}

var xxx_messageInfo_BaseSetPortraitFrameCardToS proto.InternalMessageInfo

func (m *BaseSetPortraitFrameCardToS) GetPortrait() int32 {
	if m != nil && m.Portrait != nil {
		return *m.Portrait
	}
	return 0
}

func (m *BaseSetPortraitFrameCardToS) GetPortraitFrame() int32 {
	if m != nil && m.PortraitFrame != nil {
		return *m.PortraitFrame
	}
	return 0
}

func (m *BaseSetPortraitFrameCardToS) GetCard() int32 {
	if m != nil && m.Card != nil {
		return *m.Card
	}
	return 0
}

type BaseSetPortraitFrameCardToC struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseSetPortraitFrameCardToC) Reset()         { *m = BaseSetPortraitFrameCardToC{} }
func (m *BaseSetPortraitFrameCardToC) String() string { return proto.CompactTextString(m) }
func (*BaseSetPortraitFrameCardToC) ProtoMessage()    {}
func (*BaseSetPortraitFrameCardToC) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6c1c99a3acbf74d, []int{1}
}

func (m *BaseSetPortraitFrameCardToC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseSetPortraitFrameCardToC.Unmarshal(m, b)
}
func (m *BaseSetPortraitFrameCardToC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseSetPortraitFrameCardToC.Marshal(b, m, deterministic)
}
func (m *BaseSetPortraitFrameCardToC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseSetPortraitFrameCardToC.Merge(m, src)
}
func (m *BaseSetPortraitFrameCardToC) XXX_Size() int {
	return xxx_messageInfo_BaseSetPortraitFrameCardToC.Size(m)
}
func (m *BaseSetPortraitFrameCardToC) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseSetPortraitFrameCardToC.DiscardUnknown(m)
}

var xxx_messageInfo_BaseSetPortraitFrameCardToC proto.InternalMessageInfo

func init() {
	proto.RegisterType((*BaseSetPortraitFrameCardToS)(nil), "message.baseSetPortraitFrameCard_toS")
	proto.RegisterType((*BaseSetPortraitFrameCardToC)(nil), "message.baseSetPortraitFrameCard_toC")
}

func init() {
	proto.RegisterFile("cs/proto/message/baseSetPortraitFrameCard.proto", fileDescriptor_f6c1c99a3acbf74d)
}

var fileDescriptor_f6c1c99a3acbf74d = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x4f, 0x2e, 0xd6, 0x2f,
	0x28, 0xca, 0x2f, 0xc9, 0xd7, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x4f, 0x4a, 0x2c,
	0x4e, 0x0d, 0x4e, 0x2d, 0x09, 0xc8, 0x2f, 0x2a, 0x29, 0x4a, 0xcc, 0x2c, 0x71, 0x2b, 0x4a, 0xcc,
	0x4d, 0x75, 0x4e, 0x2c, 0x4a, 0xd1, 0x03, 0x2b, 0x13, 0x62, 0x87, 0xaa, 0x53, 0x2a, 0xe1, 0x92,
	0xc1, 0xa5, 0x34, 0xbe, 0x24, 0x3f, 0x58, 0x48, 0x8a, 0x8b, 0x03, 0x26, 0x21, 0xc1, 0xa8, 0xc0,
	0xa8, 0xc1, 0x1a, 0x04, 0xe7, 0x0b, 0xa9, 0x70, 0xf1, 0xa2, 0x68, 0x92, 0x60, 0x02, 0x2b, 0x40,
	0x15, 0x14, 0x12, 0xe2, 0x62, 0x01, 0x99, 0x26, 0xc1, 0x0c, 0x96, 0x04, 0xb3, 0x95, 0xe4, 0xf0,
	0xda, 0xea, 0xec, 0xa4, 0x14, 0xa5, 0x90, 0x99, 0x97, 0x59, 0x92, 0x99, 0x98, 0x53, 0x92, 0x51,
	0x94, 0x9a, 0x0a, 0xf1, 0x5b, 0x72, 0x7e, 0x0e, 0xc8, 0x9f, 0x50, 0x97, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xc4, 0x84, 0x64, 0x5c, 0xf4, 0x00, 0x00, 0x00,
}
