// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs/proto/message/baseSync.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BaseSyncToS struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseSyncToS) Reset()         { *m = BaseSyncToS{} }
func (m *BaseSyncToS) String() string { return proto.CompactTextString(m) }
func (*BaseSyncToS) ProtoMessage()    {}
func (*BaseSyncToS) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8efb5a5252997dc, []int{0}
}

func (m *BaseSyncToS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseSyncToS.Unmarshal(m, b)
}
func (m *BaseSyncToS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseSyncToS.Marshal(b, m, deterministic)
}
func (m *BaseSyncToS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseSyncToS.Merge(m, src)
}
func (m *BaseSyncToS) XXX_Size() int {
	return xxx_messageInfo_BaseSyncToS.Size(m)
}
func (m *BaseSyncToS) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseSyncToS.DiscardUnknown(m)
}

var xxx_messageInfo_BaseSyncToS proto.InternalMessageInfo

type BaseSyncToC struct {
	UserID               *string  `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	GameID               *uint64  `protobuf:"varint,2,opt,name=gameID" json:"gameID,omitempty"`
	Name                 *string  `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Signature            *string  `protobuf:"bytes,4,opt,name=Signature" json:"Signature,omitempty"`
	CharacterList        []int32  `protobuf:"varint,5,rep,name=characterList" json:"characterList,omitempty"`
	Birthday             *string  `protobuf:"bytes,6,opt,name=Birthday" json:"Birthday,omitempty"`
	Portrait             *int32   `protobuf:"varint,7,opt,name=Portrait" json:"Portrait,omitempty"`
	PortraitFrame        *int32   `protobuf:"varint,8,opt,name=PortraitFrame" json:"PortraitFrame,omitempty"`
	Card                 *int32   `protobuf:"varint,9,opt,name=Card" json:"Card,omitempty"`
	Sex                  *int32   `protobuf:"varint,10,opt,name=Sex" json:"Sex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseSyncToC) Reset()         { *m = BaseSyncToC{} }
func (m *BaseSyncToC) String() string { return proto.CompactTextString(m) }
func (*BaseSyncToC) ProtoMessage()    {}
func (*BaseSyncToC) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8efb5a5252997dc, []int{1}
}

func (m *BaseSyncToC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseSyncToC.Unmarshal(m, b)
}
func (m *BaseSyncToC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseSyncToC.Marshal(b, m, deterministic)
}
func (m *BaseSyncToC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseSyncToC.Merge(m, src)
}
func (m *BaseSyncToC) XXX_Size() int {
	return xxx_messageInfo_BaseSyncToC.Size(m)
}
func (m *BaseSyncToC) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseSyncToC.DiscardUnknown(m)
}

var xxx_messageInfo_BaseSyncToC proto.InternalMessageInfo

func (m *BaseSyncToC) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *BaseSyncToC) GetGameID() uint64 {
	if m != nil && m.GameID != nil {
		return *m.GameID
	}
	return 0
}

func (m *BaseSyncToC) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *BaseSyncToC) GetSignature() string {
	if m != nil && m.Signature != nil {
		return *m.Signature
	}
	return ""
}

func (m *BaseSyncToC) GetCharacterList() []int32 {
	if m != nil {
		return m.CharacterList
	}
	return nil
}

func (m *BaseSyncToC) GetBirthday() string {
	if m != nil && m.Birthday != nil {
		return *m.Birthday
	}
	return ""
}

func (m *BaseSyncToC) GetPortrait() int32 {
	if m != nil && m.Portrait != nil {
		return *m.Portrait
	}
	return 0
}

func (m *BaseSyncToC) GetPortraitFrame() int32 {
	if m != nil && m.PortraitFrame != nil {
		return *m.PortraitFrame
	}
	return 0
}

func (m *BaseSyncToC) GetCard() int32 {
	if m != nil && m.Card != nil {
		return *m.Card
	}
	return 0
}

func (m *BaseSyncToC) GetSex() int32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func init() {
	proto.RegisterType((*BaseSyncToS)(nil), "message.baseSync_toS")
	proto.RegisterType((*BaseSyncToC)(nil), "message.baseSync_toC")
}

func init() { proto.RegisterFile("cs/proto/message/baseSync.proto", fileDescriptor_b8efb5a5252997dc) }

var fileDescriptor_b8efb5a5252997dc = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x49, 0x93, 0xb4, 0xcd, 0xa2, 0x22, 0x7b, 0x90, 0x45, 0x04, 0x43, 0xf0, 0x90, 0x93,
	0x79, 0x87, 0xb6, 0x08, 0x05, 0x0f, 0x92, 0xdc, 0xbc, 0xc8, 0xb8, 0x1d, 0x92, 0x85, 0x26, 0x2b,
	0xb3, 0x53, 0xb0, 0xaf, 0xe2, 0xd3, 0xca, 0xae, 0x49, 0x25, 0xb7, 0xff, 0xff, 0xbe, 0x61, 0x18,
	0x46, 0x3c, 0x6a, 0x57, 0x7d, 0x91, 0x65, 0x5b, 0xf5, 0xe8, 0x1c, 0xb4, 0x58, 0x7d, 0x82, 0xc3,
	0xe6, 0x3c, 0xe8, 0xe7, 0x80, 0xe5, 0x6a, 0xe4, 0xc5, 0x8d, 0xb8, 0x9a, 0xd4, 0x07, 0xdb, 0xa6,
	0xf8, 0x59, 0xcc, 0xc0, 0x56, 0xde, 0x89, 0xe5, 0xc9, 0x21, 0xed, 0x77, 0x2a, 0xca, 0xa3, 0x32,
	0xab, 0xc7, 0xe6, 0x79, 0x0b, 0x3d, 0xee, 0x77, 0x6a, 0x91, 0x47, 0x65, 0x52, 0x8f, 0x4d, 0x4a,
	0x91, 0x0c, 0xd0, 0xa3, 0x8a, 0xc3, 0x74, 0xc8, 0xf2, 0x41, 0x64, 0x8d, 0x69, 0x07, 0xe0, 0x13,
	0xa1, 0x4a, 0x82, 0xf8, 0x07, 0xf2, 0x49, 0x5c, 0xeb, 0x0e, 0x08, 0x34, 0x23, 0xbd, 0x1a, 0xc7,
	0x2a, 0xcd, 0xe3, 0x32, 0xad, 0xe7, 0x50, 0xde, 0x8b, 0xf5, 0xc6, 0x10, 0x77, 0x07, 0x38, 0xab,
	0x65, 0x58, 0x71, 0xe9, 0xde, 0xbd, 0x59, 0x62, 0x02, 0xc3, 0x6a, 0x95, 0x47, 0x65, 0x5a, 0x5f,
	0xba, 0xdf, 0x3e, 0xe5, 0x17, 0xf2, 0x87, 0xad, 0xc3, 0xc0, 0x1c, 0xfa, 0xab, 0xb7, 0x40, 0x07,
	0x95, 0x05, 0x19, 0xb2, 0xbc, 0x15, 0x71, 0x83, 0xdf, 0x4a, 0x04, 0xe4, 0xe3, 0xa6, 0x78, 0xcf,
	0xcd, 0x60, 0xd8, 0xc0, 0x91, 0x3b, 0x42, 0xfc, 0x7b, 0xb1, 0xb6, 0xc7, 0x4a, 0xbb, 0xe9, 0xd1,
	0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf7, 0xb3, 0xf3, 0xa6, 0x7b, 0x01, 0x00, 0x00,
}
