// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs/proto/message/baseSetBirthday.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BaseSetBirthdayToS struct {
	Birthday             *string  `protobuf:"bytes,1,opt,name=birthday" json:"birthday,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseSetBirthdayToS) Reset()         { *m = BaseSetBirthdayToS{} }
func (m *BaseSetBirthdayToS) String() string { return proto.CompactTextString(m) }
func (*BaseSetBirthdayToS) ProtoMessage()    {}
func (*BaseSetBirthdayToS) Descriptor() ([]byte, []int) {
	return fileDescriptor_5433a7aded6ae011, []int{0}
}

func (m *BaseSetBirthdayToS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseSetBirthdayToS.Unmarshal(m, b)
}
func (m *BaseSetBirthdayToS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseSetBirthdayToS.Marshal(b, m, deterministic)
}
func (m *BaseSetBirthdayToS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseSetBirthdayToS.Merge(m, src)
}
func (m *BaseSetBirthdayToS) XXX_Size() int {
	return xxx_messageInfo_BaseSetBirthdayToS.Size(m)
}
func (m *BaseSetBirthdayToS) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseSetBirthdayToS.DiscardUnknown(m)
}

var xxx_messageInfo_BaseSetBirthdayToS proto.InternalMessageInfo

func (m *BaseSetBirthdayToS) GetBirthday() string {
	if m != nil && m.Birthday != nil {
		return *m.Birthday
	}
	return ""
}

type BaseSetBirthdayToC struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseSetBirthdayToC) Reset()         { *m = BaseSetBirthdayToC{} }
func (m *BaseSetBirthdayToC) String() string { return proto.CompactTextString(m) }
func (*BaseSetBirthdayToC) ProtoMessage()    {}
func (*BaseSetBirthdayToC) Descriptor() ([]byte, []int) {
	return fileDescriptor_5433a7aded6ae011, []int{1}
}

func (m *BaseSetBirthdayToC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseSetBirthdayToC.Unmarshal(m, b)
}
func (m *BaseSetBirthdayToC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseSetBirthdayToC.Marshal(b, m, deterministic)
}
func (m *BaseSetBirthdayToC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseSetBirthdayToC.Merge(m, src)
}
func (m *BaseSetBirthdayToC) XXX_Size() int {
	return xxx_messageInfo_BaseSetBirthdayToC.Size(m)
}
func (m *BaseSetBirthdayToC) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseSetBirthdayToC.DiscardUnknown(m)
}

var xxx_messageInfo_BaseSetBirthdayToC proto.InternalMessageInfo

func init() {
	proto.RegisterType((*BaseSetBirthdayToS)(nil), "message.baseSetBirthday_toS")
	proto.RegisterType((*BaseSetBirthdayToC)(nil), "message.baseSetBirthday_toC")
}

func init() {
	proto.RegisterFile("cs/proto/message/baseSetBirthday.proto", fileDescriptor_5433a7aded6ae011)
}

var fileDescriptor_5433a7aded6ae011 = []byte{
	// 122 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4b, 0x2e, 0xd6, 0x2f,
	0x28, 0xca, 0x2f, 0xc9, 0xd7, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x4f, 0x4a, 0x2c,
	0x4e, 0x0d, 0x4e, 0x2d, 0x71, 0xca, 0x2c, 0x2a, 0xc9, 0x48, 0x49, 0xac, 0xd4, 0x03, 0xcb, 0x0a,
	0xb1, 0x43, 0xa5, 0x95, 0x0c, 0xb9, 0x84, 0xd1, 0x54, 0xc4, 0x97, 0xe4, 0x07, 0x0b, 0x49, 0x71,
	0x71, 0x24, 0x41, 0xf9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x70, 0xbe, 0x92, 0x28, 0x36,
	0x2d, 0xce, 0x4e, 0x4a, 0x51, 0x0a, 0x99, 0x79, 0x99, 0x25, 0x99, 0x89, 0x39, 0x25, 0x19, 0x45,
	0xa9, 0xa9, 0x10, 0x67, 0x24, 0xe7, 0xe7, 0xe8, 0x27, 0x17, 0xc3, 0x1c, 0x03, 0x08, 0x00, 0x00,
	0xff, 0xff, 0xe0, 0x19, 0xf7, 0xa8, 0x9f, 0x00, 0x00, 0x00,
}
