// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs/proto/message/bigSecretBlessingLvUp.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BigSecretBlessingLvUpToS struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BigSecretBlessingLvUpToS) Reset()         { *m = BigSecretBlessingLvUpToS{} }
func (m *BigSecretBlessingLvUpToS) String() string { return proto.CompactTextString(m) }
func (*BigSecretBlessingLvUpToS) ProtoMessage()    {}
func (*BigSecretBlessingLvUpToS) Descriptor() ([]byte, []int) {
	return fileDescriptor_743d76f28e356f31, []int{0}
}

func (m *BigSecretBlessingLvUpToS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BigSecretBlessingLvUpToS.Unmarshal(m, b)
}
func (m *BigSecretBlessingLvUpToS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BigSecretBlessingLvUpToS.Marshal(b, m, deterministic)
}
func (m *BigSecretBlessingLvUpToS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BigSecretBlessingLvUpToS.Merge(m, src)
}
func (m *BigSecretBlessingLvUpToS) XXX_Size() int {
	return xxx_messageInfo_BigSecretBlessingLvUpToS.Size(m)
}
func (m *BigSecretBlessingLvUpToS) XXX_DiscardUnknown() {
	xxx_messageInfo_BigSecretBlessingLvUpToS.DiscardUnknown(m)
}

var xxx_messageInfo_BigSecretBlessingLvUpToS proto.InternalMessageInfo

type BigSecretBlessingLvUpToC struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BigSecretBlessingLvUpToC) Reset()         { *m = BigSecretBlessingLvUpToC{} }
func (m *BigSecretBlessingLvUpToC) String() string { return proto.CompactTextString(m) }
func (*BigSecretBlessingLvUpToC) ProtoMessage()    {}
func (*BigSecretBlessingLvUpToC) Descriptor() ([]byte, []int) {
	return fileDescriptor_743d76f28e356f31, []int{1}
}

func (m *BigSecretBlessingLvUpToC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BigSecretBlessingLvUpToC.Unmarshal(m, b)
}
func (m *BigSecretBlessingLvUpToC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BigSecretBlessingLvUpToC.Marshal(b, m, deterministic)
}
func (m *BigSecretBlessingLvUpToC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BigSecretBlessingLvUpToC.Merge(m, src)
}
func (m *BigSecretBlessingLvUpToC) XXX_Size() int {
	return xxx_messageInfo_BigSecretBlessingLvUpToC.Size(m)
}
func (m *BigSecretBlessingLvUpToC) XXX_DiscardUnknown() {
	xxx_messageInfo_BigSecretBlessingLvUpToC.DiscardUnknown(m)
}

var xxx_messageInfo_BigSecretBlessingLvUpToC proto.InternalMessageInfo

func init() {
	proto.RegisterType((*BigSecretBlessingLvUpToS)(nil), "message.bigSecretBlessingLvUp_toS")
	proto.RegisterType((*BigSecretBlessingLvUpToC)(nil), "message.bigSecretBlessingLvUp_toC")
}

func init() {
	proto.RegisterFile("cs/proto/message/bigSecretBlessingLvUp.proto", fileDescriptor_743d76f28e356f31)
}

var fileDescriptor_743d76f28e356f31 = []byte{
	// 111 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x49, 0x2e, 0xd6, 0x2f,
	0x28, 0xca, 0x2f, 0xc9, 0xd7, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x4f, 0xca, 0x4c,
	0x0f, 0x4e, 0x4d, 0x2e, 0x4a, 0x2d, 0x71, 0xca, 0x49, 0x2d, 0x2e, 0xce, 0xcc, 0x4b, 0xf7, 0x29,
	0x0b, 0x2d, 0xd0, 0x03, 0xab, 0x11, 0x62, 0x87, 0x2a, 0x52, 0x92, 0xe6, 0x92, 0xc4, 0xaa, 0x2e,
	0xbe, 0x24, 0x3f, 0x18, 0x9f, 0xa4, 0xb3, 0x93, 0x52, 0x94, 0x42, 0x66, 0x5e, 0x66, 0x49, 0x66,
	0x62, 0x4e, 0x49, 0x46, 0x51, 0x6a, 0x2a, 0xc4, 0xf2, 0xe4, 0xfc, 0x1c, 0xfd, 0xe4, 0x62, 0x98,
	0x13, 0x00, 0x01, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x7f, 0x92, 0x9f, 0x95, 0x00, 0x00, 0x00,
}
