// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs/proto/message/bigSecretRandomLevel.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BigSecretRandomLevelToS struct {
	Level                *int32   `protobuf:"varint,1,req,name=level" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BigSecretRandomLevelToS) Reset()         { *m = BigSecretRandomLevelToS{} }
func (m *BigSecretRandomLevelToS) String() string { return proto.CompactTextString(m) }
func (*BigSecretRandomLevelToS) ProtoMessage()    {}
func (*BigSecretRandomLevelToS) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae8fc6e6cea946f5, []int{0}
}

func (m *BigSecretRandomLevelToS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BigSecretRandomLevelToS.Unmarshal(m, b)
}
func (m *BigSecretRandomLevelToS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BigSecretRandomLevelToS.Marshal(b, m, deterministic)
}
func (m *BigSecretRandomLevelToS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BigSecretRandomLevelToS.Merge(m, src)
}
func (m *BigSecretRandomLevelToS) XXX_Size() int {
	return xxx_messageInfo_BigSecretRandomLevelToS.Size(m)
}
func (m *BigSecretRandomLevelToS) XXX_DiscardUnknown() {
	xxx_messageInfo_BigSecretRandomLevelToS.DiscardUnknown(m)
}

var xxx_messageInfo_BigSecretRandomLevelToS proto.InternalMessageInfo

func (m *BigSecretRandomLevelToS) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

type BigSecretRandomLevelToC struct {
	LevelID              *int32   `protobuf:"varint,1,opt,name=levelID" json:"levelID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BigSecretRandomLevelToC) Reset()         { *m = BigSecretRandomLevelToC{} }
func (m *BigSecretRandomLevelToC) String() string { return proto.CompactTextString(m) }
func (*BigSecretRandomLevelToC) ProtoMessage()    {}
func (*BigSecretRandomLevelToC) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae8fc6e6cea946f5, []int{1}
}

func (m *BigSecretRandomLevelToC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BigSecretRandomLevelToC.Unmarshal(m, b)
}
func (m *BigSecretRandomLevelToC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BigSecretRandomLevelToC.Marshal(b, m, deterministic)
}
func (m *BigSecretRandomLevelToC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BigSecretRandomLevelToC.Merge(m, src)
}
func (m *BigSecretRandomLevelToC) XXX_Size() int {
	return xxx_messageInfo_BigSecretRandomLevelToC.Size(m)
}
func (m *BigSecretRandomLevelToC) XXX_DiscardUnknown() {
	xxx_messageInfo_BigSecretRandomLevelToC.DiscardUnknown(m)
}

var xxx_messageInfo_BigSecretRandomLevelToC proto.InternalMessageInfo

func (m *BigSecretRandomLevelToC) GetLevelID() int32 {
	if m != nil && m.LevelID != nil {
		return *m.LevelID
	}
	return 0
}

func init() {
	proto.RegisterType((*BigSecretRandomLevelToS)(nil), "message.bigSecretRandomLevel_toS")
	proto.RegisterType((*BigSecretRandomLevelToC)(nil), "message.bigSecretRandomLevel_toC")
}

func init() {
	proto.RegisterFile("cs/proto/message/bigSecretRandomLevel.proto", fileDescriptor_ae8fc6e6cea946f5)
}

var fileDescriptor_ae8fc6e6cea946f5 = []byte{
	// 144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x4e, 0x2e, 0xd6, 0x2f,
	0x28, 0xca, 0x2f, 0xc9, 0xd7, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x4f, 0xca, 0x4c,
	0x0f, 0x4e, 0x4d, 0x2e, 0x4a, 0x2d, 0x09, 0x4a, 0xcc, 0x4b, 0xc9, 0xcf, 0xf5, 0x49, 0x2d, 0x4b,
	0xcd, 0xd1, 0x03, 0x2b, 0x11, 0x62, 0x87, 0xaa, 0x51, 0x32, 0xe0, 0x92, 0xc0, 0xa6, 0x2c, 0xbe,
	0x24, 0x3f, 0x58, 0x48, 0x84, 0x8b, 0x35, 0x07, 0xc4, 0x91, 0x60, 0x54, 0x60, 0xd2, 0x60, 0x0d,
	0x82, 0x70, 0x94, 0x4c, 0x70, 0xea, 0x70, 0x16, 0x92, 0xe0, 0x62, 0x07, 0x2b, 0xf2, 0x74, 0x91,
	0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x82, 0x71, 0x9d, 0x94, 0xa2, 0x14, 0x32, 0xf3, 0x32, 0x4b,
	0x32, 0x13, 0x73, 0x4a, 0x32, 0x8a, 0x52, 0x53, 0x21, 0x2e, 0x4d, 0xce, 0xcf, 0xd1, 0x4f, 0x2e,
	0x86, 0xb9, 0x17, 0x10, 0x00, 0x00, 0xff, 0xff, 0xa3, 0xea, 0xe6, 0xe3, 0xc2, 0x00, 0x00, 0x00,
}
