// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs/proto/message/bigSecretSync.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BigSecretWeakness struct {
	Level                *int32   `protobuf:"varint,1,opt,name=level" json:"level,omitempty"`
	Weakness             []int32  `protobuf:"varint,2,rep,name=weakness" json:"weakness,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BigSecretWeakness) Reset()         { *m = BigSecretWeakness{} }
func (m *BigSecretWeakness) String() string { return proto.CompactTextString(m) }
func (*BigSecretWeakness) ProtoMessage()    {}
func (*BigSecretWeakness) Descriptor() ([]byte, []int) {
	return fileDescriptor_4976ca9747a764c1, []int{0}
}

func (m *BigSecretWeakness) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BigSecretWeakness.Unmarshal(m, b)
}
func (m *BigSecretWeakness) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BigSecretWeakness.Marshal(b, m, deterministic)
}
func (m *BigSecretWeakness) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BigSecretWeakness.Merge(m, src)
}
func (m *BigSecretWeakness) XXX_Size() int {
	return xxx_messageInfo_BigSecretWeakness.Size(m)
}
func (m *BigSecretWeakness) XXX_DiscardUnknown() {
	xxx_messageInfo_BigSecretWeakness.DiscardUnknown(m)
}

var xxx_messageInfo_BigSecretWeakness proto.InternalMessageInfo

func (m *BigSecretWeakness) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *BigSecretWeakness) GetWeakness() []int32 {
	if m != nil {
		return m.Weakness
	}
	return nil
}

type BigSecretData struct {
	MaxLevel             *int32   `protobuf:"varint,1,opt,name=maxLevel" json:"maxLevel,omitempty"`
	KeyCount             *int32   `protobuf:"varint,2,opt,name=keyCount" json:"keyCount,omitempty"`
	WeaknessRefreshTimes *int32   `protobuf:"varint,3,opt,name=weaknessRefreshTimes" json:"weaknessRefreshTimes,omitempty"`
	BlessingLevel        *int32   `protobuf:"varint,4,opt,name=blessingLevel" json:"blessingLevel,omitempty"`
	BlessingCount        *int32   `protobuf:"varint,5,opt,name=blessingCount" json:"blessingCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BigSecretData) Reset()         { *m = BigSecretData{} }
func (m *BigSecretData) String() string { return proto.CompactTextString(m) }
func (*BigSecretData) ProtoMessage()    {}
func (*BigSecretData) Descriptor() ([]byte, []int) {
	return fileDescriptor_4976ca9747a764c1, []int{1}
}

func (m *BigSecretData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BigSecretData.Unmarshal(m, b)
}
func (m *BigSecretData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BigSecretData.Marshal(b, m, deterministic)
}
func (m *BigSecretData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BigSecretData.Merge(m, src)
}
func (m *BigSecretData) XXX_Size() int {
	return xxx_messageInfo_BigSecretData.Size(m)
}
func (m *BigSecretData) XXX_DiscardUnknown() {
	xxx_messageInfo_BigSecretData.DiscardUnknown(m)
}

var xxx_messageInfo_BigSecretData proto.InternalMessageInfo

func (m *BigSecretData) GetMaxLevel() int32 {
	if m != nil && m.MaxLevel != nil {
		return *m.MaxLevel
	}
	return 0
}

func (m *BigSecretData) GetKeyCount() int32 {
	if m != nil && m.KeyCount != nil {
		return *m.KeyCount
	}
	return 0
}

func (m *BigSecretData) GetWeaknessRefreshTimes() int32 {
	if m != nil && m.WeaknessRefreshTimes != nil {
		return *m.WeaknessRefreshTimes
	}
	return 0
}

func (m *BigSecretData) GetBlessingLevel() int32 {
	if m != nil && m.BlessingLevel != nil {
		return *m.BlessingLevel
	}
	return 0
}

func (m *BigSecretData) GetBlessingCount() int32 {
	if m != nil && m.BlessingCount != nil {
		return *m.BlessingCount
	}
	return 0
}

type BigSecretShop struct {
	Id                   *int32   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	BuyTimes             *int32   `protobuf:"varint,2,opt,name=buyTimes" json:"buyTimes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BigSecretShop) Reset()         { *m = BigSecretShop{} }
func (m *BigSecretShop) String() string { return proto.CompactTextString(m) }
func (*BigSecretShop) ProtoMessage()    {}
func (*BigSecretShop) Descriptor() ([]byte, []int) {
	return fileDescriptor_4976ca9747a764c1, []int{2}
}

func (m *BigSecretShop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BigSecretShop.Unmarshal(m, b)
}
func (m *BigSecretShop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BigSecretShop.Marshal(b, m, deterministic)
}
func (m *BigSecretShop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BigSecretShop.Merge(m, src)
}
func (m *BigSecretShop) XXX_Size() int {
	return xxx_messageInfo_BigSecretShop.Size(m)
}
func (m *BigSecretShop) XXX_DiscardUnknown() {
	xxx_messageInfo_BigSecretShop.DiscardUnknown(m)
}

var xxx_messageInfo_BigSecretShop proto.InternalMessageInfo

func (m *BigSecretShop) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *BigSecretShop) GetBuyTimes() int32 {
	if m != nil && m.BuyTimes != nil {
		return *m.BuyTimes
	}
	return 0
}

type BigSecretSyncToS struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BigSecretSyncToS) Reset()         { *m = BigSecretSyncToS{} }
func (m *BigSecretSyncToS) String() string { return proto.CompactTextString(m) }
func (*BigSecretSyncToS) ProtoMessage()    {}
func (*BigSecretSyncToS) Descriptor() ([]byte, []int) {
	return fileDescriptor_4976ca9747a764c1, []int{3}
}

func (m *BigSecretSyncToS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BigSecretSyncToS.Unmarshal(m, b)
}
func (m *BigSecretSyncToS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BigSecretSyncToS.Marshal(b, m, deterministic)
}
func (m *BigSecretSyncToS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BigSecretSyncToS.Merge(m, src)
}
func (m *BigSecretSyncToS) XXX_Size() int {
	return xxx_messageInfo_BigSecretSyncToS.Size(m)
}
func (m *BigSecretSyncToS) XXX_DiscardUnknown() {
	xxx_messageInfo_BigSecretSyncToS.DiscardUnknown(m)
}

var xxx_messageInfo_BigSecretSyncToS proto.InternalMessageInfo

type BigSecretSyncToC struct {
	IsAll                *bool                `protobuf:"varint,1,opt,name=isAll" json:"isAll,omitempty"`
	Data                 *BigSecretData       `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	Passed               []int32              `protobuf:"varint,3,rep,name=passed" json:"passed,omitempty"`
	Weakness             []*BigSecretWeakness `protobuf:"bytes,4,rep,name=weakness" json:"weakness,omitempty"`
	Shop                 []*BigSecretShop     `protobuf:"bytes,5,rep,name=shop" json:"shop,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BigSecretSyncToC) Reset()         { *m = BigSecretSyncToC{} }
func (m *BigSecretSyncToC) String() string { return proto.CompactTextString(m) }
func (*BigSecretSyncToC) ProtoMessage()    {}
func (*BigSecretSyncToC) Descriptor() ([]byte, []int) {
	return fileDescriptor_4976ca9747a764c1, []int{4}
}

func (m *BigSecretSyncToC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BigSecretSyncToC.Unmarshal(m, b)
}
func (m *BigSecretSyncToC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BigSecretSyncToC.Marshal(b, m, deterministic)
}
func (m *BigSecretSyncToC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BigSecretSyncToC.Merge(m, src)
}
func (m *BigSecretSyncToC) XXX_Size() int {
	return xxx_messageInfo_BigSecretSyncToC.Size(m)
}
func (m *BigSecretSyncToC) XXX_DiscardUnknown() {
	xxx_messageInfo_BigSecretSyncToC.DiscardUnknown(m)
}

var xxx_messageInfo_BigSecretSyncToC proto.InternalMessageInfo

func (m *BigSecretSyncToC) GetIsAll() bool {
	if m != nil && m.IsAll != nil {
		return *m.IsAll
	}
	return false
}

func (m *BigSecretSyncToC) GetData() *BigSecretData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *BigSecretSyncToC) GetPassed() []int32 {
	if m != nil {
		return m.Passed
	}
	return nil
}

func (m *BigSecretSyncToC) GetWeakness() []*BigSecretWeakness {
	if m != nil {
		return m.Weakness
	}
	return nil
}

func (m *BigSecretSyncToC) GetShop() []*BigSecretShop {
	if m != nil {
		return m.Shop
	}
	return nil
}

func init() {
	proto.RegisterType((*BigSecretWeakness)(nil), "message.bigSecretWeakness")
	proto.RegisterType((*BigSecretData)(nil), "message.bigSecretData")
	proto.RegisterType((*BigSecretShop)(nil), "message.bigSecretShop")
	proto.RegisterType((*BigSecretSyncToS)(nil), "message.bigSecretSync_toS")
	proto.RegisterType((*BigSecretSyncToC)(nil), "message.bigSecretSync_toC")
}

func init() {
	proto.RegisterFile("cs/proto/message/bigSecretSync.proto", fileDescriptor_4976ca9747a764c1)
}

var fileDescriptor_4976ca9747a764c1 = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x41, 0x4f, 0xb3, 0x40,
	0x14, 0x0c, 0x50, 0xbe, 0xaf, 0xd9, 0xa6, 0x26, 0xae, 0x4d, 0x43, 0x7a, 0x22, 0xa4, 0x87, 0xc6,
	0x43, 0x49, 0x7a, 0xf0, 0xe2, 0x49, 0xab, 0x37, 0x4f, 0x60, 0x62, 0xe2, 0xc5, 0x6c, 0xe1, 0x59,
	0x36, 0xa5, 0x2c, 0xe1, 0x6d, 0xd5, 0xfe, 0x42, 0xcf, 0xfe, 0x23, 0xb3, 0xbb, 0x80, 0x90, 0xf6,
	0x38, 0x6f, 0x86, 0x79, 0x8f, 0x99, 0x25, 0xf3, 0x04, 0xc3, 0xb2, 0x12, 0x52, 0x84, 0x7b, 0x40,
	0x64, 0x5b, 0x08, 0x37, 0x7c, 0x1b, 0x43, 0x52, 0x81, 0x8c, 0x8f, 0x45, 0xb2, 0xd4, 0x1c, 0xfd,
	0x5f, 0x93, 0xc1, 0x23, 0xb9, 0x6c, 0xf9, 0x17, 0x60, 0xbb, 0x02, 0x10, 0xe9, 0x84, 0xb8, 0x39,
	0x7c, 0x40, 0xee, 0x59, 0xbe, 0xb5, 0x70, 0x23, 0x03, 0xe8, 0x8c, 0x0c, 0x3f, 0x6b, 0x85, 0x67,
	0xfb, 0xce, 0xc2, 0x8d, 0x5a, 0x1c, 0x7c, 0x5b, 0x64, 0xdc, 0xfa, 0x3c, 0x30, 0xc9, 0x94, 0x7a,
	0xcf, 0xbe, 0x9e, 0x3a, 0x36, 0x2d, 0x56, 0xdc, 0x0e, 0x8e, 0x6b, 0x71, 0x28, 0xa4, 0x67, 0x1b,
	0xae, 0xc1, 0x74, 0x45, 0x26, 0x8d, 0x6b, 0x04, 0xef, 0x15, 0x60, 0xf6, 0xcc, 0xf7, 0x80, 0x9e,
	0xa3, 0x75, 0x67, 0x39, 0x3a, 0x27, 0xe3, 0x4d, 0x0e, 0x88, 0xbc, 0xd8, 0x9a, 0x85, 0x03, 0x2d,
	0xee, 0x0f, 0xbb, 0x2a, 0xb3, 0xda, 0xed, 0xab, 0xf4, 0x30, 0xb8, 0xed, 0xfc, 0x48, 0x9c, 0x89,
	0x92, 0x5e, 0x10, 0x9b, 0xa7, 0xf5, 0x2f, 0xd8, 0x3c, 0x55, 0xc7, 0x6f, 0x0e, 0x47, 0x73, 0x54,
	0x7d, 0x7c, 0x83, 0x83, 0xab, 0x4e, 0x9a, 0x2a, 0xed, 0x37, 0x29, 0xe2, 0xe0, 0xc7, 0x3a, 0x9d,
	0xae, 0x55, 0xc6, 0x1c, 0xef, 0x72, 0x13, 0xce, 0x30, 0x32, 0x80, 0x5e, 0x93, 0x41, 0xca, 0x24,
	0xd3, 0xc6, 0xa3, 0xd5, 0x74, 0x59, 0xd7, 0xb4, 0xec, 0x65, 0x1b, 0x69, 0x0d, 0x9d, 0x92, 0x7f,
	0x25, 0x43, 0x84, 0xd4, 0x73, 0x74, 0x1b, 0x35, 0xa2, 0x37, 0x9d, 0x9e, 0x06, 0xbe, 0xb3, 0x18,
	0xad, 0x66, 0xa7, 0x3e, 0x4d, 0xd7, 0x7f, 0x1d, 0xaa, 0xdd, 0x98, 0x89, 0xd2, 0x73, 0xf5, 0x37,
	0x67, 0x76, 0xab, 0x38, 0x22, 0xad, 0xb9, 0x0f, 0x5e, 0x7d, 0x5e, 0x70, 0xc9, 0x59, 0x2e, 0xb3,
	0x0a, 0xc0, 0xbc, 0xb8, 0x44, 0xe4, 0x61, 0x82, 0xcd, 0xbb, 0xfb, 0x0d, 0x00, 0x00, 0xff, 0xff,
	0xfb, 0xf9, 0x4e, 0x34, 0x8a, 0x02, 0x00, 0x00,
}
