// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs/proto/message/bigSecretCompetitionSync.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BigSecretCompetitionSyncToS struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BigSecretCompetitionSyncToS) Reset()         { *m = BigSecretCompetitionSyncToS{} }
func (m *BigSecretCompetitionSyncToS) String() string { return proto.CompactTextString(m) }
func (*BigSecretCompetitionSyncToS) ProtoMessage()    {}
func (*BigSecretCompetitionSyncToS) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd24e4f7a0366f39, []int{0}
}

func (m *BigSecretCompetitionSyncToS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BigSecretCompetitionSyncToS.Unmarshal(m, b)
}
func (m *BigSecretCompetitionSyncToS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BigSecretCompetitionSyncToS.Marshal(b, m, deterministic)
}
func (m *BigSecretCompetitionSyncToS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BigSecretCompetitionSyncToS.Merge(m, src)
}
func (m *BigSecretCompetitionSyncToS) XXX_Size() int {
	return xxx_messageInfo_BigSecretCompetitionSyncToS.Size(m)
}
func (m *BigSecretCompetitionSyncToS) XXX_DiscardUnknown() {
	xxx_messageInfo_BigSecretCompetitionSyncToS.DiscardUnknown(m)
}

var xxx_messageInfo_BigSecretCompetitionSyncToS proto.InternalMessageInfo

type BigSecretCompetitionSyncToC struct {
	BeginTime            *int64   `protobuf:"varint,1,opt,name=beginTime" json:"beginTime,omitempty"`
	EndTime              *int64   `protobuf:"varint,2,opt,name=endTime" json:"endTime,omitempty"`
	RankID               *int32   `protobuf:"varint,3,opt,name=rankID" json:"rankID,omitempty"`
	Config               *int32   `protobuf:"varint,4,opt,name=config" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BigSecretCompetitionSyncToC) Reset()         { *m = BigSecretCompetitionSyncToC{} }
func (m *BigSecretCompetitionSyncToC) String() string { return proto.CompactTextString(m) }
func (*BigSecretCompetitionSyncToC) ProtoMessage()    {}
func (*BigSecretCompetitionSyncToC) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd24e4f7a0366f39, []int{1}
}

func (m *BigSecretCompetitionSyncToC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BigSecretCompetitionSyncToC.Unmarshal(m, b)
}
func (m *BigSecretCompetitionSyncToC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BigSecretCompetitionSyncToC.Marshal(b, m, deterministic)
}
func (m *BigSecretCompetitionSyncToC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BigSecretCompetitionSyncToC.Merge(m, src)
}
func (m *BigSecretCompetitionSyncToC) XXX_Size() int {
	return xxx_messageInfo_BigSecretCompetitionSyncToC.Size(m)
}
func (m *BigSecretCompetitionSyncToC) XXX_DiscardUnknown() {
	xxx_messageInfo_BigSecretCompetitionSyncToC.DiscardUnknown(m)
}

var xxx_messageInfo_BigSecretCompetitionSyncToC proto.InternalMessageInfo

func (m *BigSecretCompetitionSyncToC) GetBeginTime() int64 {
	if m != nil && m.BeginTime != nil {
		return *m.BeginTime
	}
	return 0
}

func (m *BigSecretCompetitionSyncToC) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

func (m *BigSecretCompetitionSyncToC) GetRankID() int32 {
	if m != nil && m.RankID != nil {
		return *m.RankID
	}
	return 0
}

func (m *BigSecretCompetitionSyncToC) GetConfig() int32 {
	if m != nil && m.Config != nil {
		return *m.Config
	}
	return 0
}

func init() {
	proto.RegisterType((*BigSecretCompetitionSyncToS)(nil), "message.bigSecretCompetitionSync_toS")
	proto.RegisterType((*BigSecretCompetitionSyncToC)(nil), "message.bigSecretCompetitionSync_toC")
}

func init() {
	proto.RegisterFile("cs/proto/message/bigSecretCompetitionSync.proto", fileDescriptor_cd24e4f7a0366f39)
}

var fileDescriptor_cd24e4f7a0366f39 = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x4f, 0x2e, 0xd6, 0x2f,
	0x28, 0xca, 0x2f, 0xc9, 0xd7, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x4f, 0xca, 0x4c,
	0x0f, 0x4e, 0x4d, 0x2e, 0x4a, 0x2d, 0x71, 0xce, 0xcf, 0x2d, 0x48, 0x2d, 0xc9, 0x2c, 0xc9, 0xcc,
	0xcf, 0x0b, 0xae, 0xcc, 0x4b, 0xd6, 0x03, 0x2b, 0x13, 0x62, 0x87, 0xaa, 0x53, 0x92, 0xe3, 0x92,
	0xc1, 0xa5, 0x34, 0xbe, 0x24, 0x3f, 0x58, 0xa9, 0x8d, 0x11, 0xaf, 0x02, 0x67, 0x21, 0x19, 0x2e,
	0xce, 0xa4, 0xd4, 0xf4, 0xcc, 0xbc, 0x90, 0xcc, 0xdc, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xe6,
	0x20, 0x84, 0x80, 0x90, 0x04, 0x17, 0x7b, 0x6a, 0x5e, 0x0a, 0x58, 0x8e, 0x09, 0x2c, 0x07, 0xe3,
	0x0a, 0x89, 0x71, 0xb1, 0x15, 0x25, 0xe6, 0x65, 0x7b, 0xba, 0x48, 0x30, 0x2b, 0x30, 0x6a, 0xb0,
	0x06, 0x41, 0x79, 0x20, 0xf1, 0xe4, 0xfc, 0xbc, 0xb4, 0xcc, 0x74, 0x09, 0x16, 0x88, 0x38, 0x84,
	0xe7, 0xa4, 0x14, 0xa5, 0x90, 0x99, 0x97, 0x59, 0x92, 0x99, 0x98, 0x53, 0x92, 0x51, 0x94, 0x9a,
	0x0a, 0xf1, 0x6e, 0x72, 0x7e, 0x0e, 0xc8, 0xeb, 0x50, 0xcf, 0x00, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x75, 0x19, 0x1d, 0xe5, 0x07, 0x01, 0x00, 0x00,
}
