// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs/proto/message/characterTeamPrefabSync.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CharacterTeamPrefabSyncToS struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CharacterTeamPrefabSyncToS) Reset()         { *m = CharacterTeamPrefabSyncToS{} }
func (m *CharacterTeamPrefabSyncToS) String() string { return proto.CompactTextString(m) }
func (*CharacterTeamPrefabSyncToS) ProtoMessage()    {}
func (*CharacterTeamPrefabSyncToS) Descriptor() ([]byte, []int) {
	return fileDescriptor_90365cd48e77b736, []int{0}
}

func (m *CharacterTeamPrefabSyncToS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CharacterTeamPrefabSyncToS.Unmarshal(m, b)
}
func (m *CharacterTeamPrefabSyncToS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CharacterTeamPrefabSyncToS.Marshal(b, m, deterministic)
}
func (m *CharacterTeamPrefabSyncToS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CharacterTeamPrefabSyncToS.Merge(m, src)
}
func (m *CharacterTeamPrefabSyncToS) XXX_Size() int {
	return xxx_messageInfo_CharacterTeamPrefabSyncToS.Size(m)
}
func (m *CharacterTeamPrefabSyncToS) XXX_DiscardUnknown() {
	xxx_messageInfo_CharacterTeamPrefabSyncToS.DiscardUnknown(m)
}

var xxx_messageInfo_CharacterTeamPrefabSyncToS proto.InternalMessageInfo

type CharacterTeamPrefabSyncToC struct {
	CharacterTeamPrefabs []*CharacterTeamPrefab `protobuf:"bytes,1,rep,name=characterTeamPrefabs" json:"characterTeamPrefabs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CharacterTeamPrefabSyncToC) Reset()         { *m = CharacterTeamPrefabSyncToC{} }
func (m *CharacterTeamPrefabSyncToC) String() string { return proto.CompactTextString(m) }
func (*CharacterTeamPrefabSyncToC) ProtoMessage()    {}
func (*CharacterTeamPrefabSyncToC) Descriptor() ([]byte, []int) {
	return fileDescriptor_90365cd48e77b736, []int{1}
}

func (m *CharacterTeamPrefabSyncToC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CharacterTeamPrefabSyncToC.Unmarshal(m, b)
}
func (m *CharacterTeamPrefabSyncToC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CharacterTeamPrefabSyncToC.Marshal(b, m, deterministic)
}
func (m *CharacterTeamPrefabSyncToC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CharacterTeamPrefabSyncToC.Merge(m, src)
}
func (m *CharacterTeamPrefabSyncToC) XXX_Size() int {
	return xxx_messageInfo_CharacterTeamPrefabSyncToC.Size(m)
}
func (m *CharacterTeamPrefabSyncToC) XXX_DiscardUnknown() {
	xxx_messageInfo_CharacterTeamPrefabSyncToC.DiscardUnknown(m)
}

var xxx_messageInfo_CharacterTeamPrefabSyncToC proto.InternalMessageInfo

func (m *CharacterTeamPrefabSyncToC) GetCharacterTeamPrefabs() []*CharacterTeamPrefab {
	if m != nil {
		return m.CharacterTeamPrefabs
	}
	return nil
}

func init() {
	proto.RegisterType((*CharacterTeamPrefabSyncToS)(nil), "message.characterTeamPrefabSync_toS")
	proto.RegisterType((*CharacterTeamPrefabSyncToC)(nil), "message.characterTeamPrefabSync_toC")
}

func init() {
	proto.RegisterFile("cs/proto/message/characterTeamPrefabSync.proto", fileDescriptor_90365cd48e77b736)
}

var fileDescriptor_90365cd48e77b736 = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x4b, 0x2e, 0xd6, 0x2f,
	0x28, 0xca, 0x2f, 0xc9, 0xd7, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x4f, 0xce, 0x48,
	0x2c, 0x4a, 0x4c, 0x2e, 0x49, 0x2d, 0x0a, 0x49, 0x4d, 0xcc, 0x0d, 0x28, 0x4a, 0x4d, 0x4b, 0x4c,
	0x0a, 0xae, 0xcc, 0x4b, 0xd6, 0x03, 0xab, 0x12, 0x62, 0x87, 0x2a, 0x93, 0xd2, 0x25, 0x4a, 0x63,
	0x6a, 0x09, 0x44, 0x9f, 0x92, 0x2c, 0x97, 0x34, 0x0e, 0x83, 0xe3, 0x4b, 0xf2, 0x83, 0x95, 0xf2,
	0xf1, 0x49, 0x3b, 0x0b, 0x05, 0x70, 0x89, 0x60, 0x91, 0x2e, 0x96, 0x60, 0x54, 0x60, 0xd6, 0xe0,
	0x36, 0x92, 0xd1, 0x83, 0x3a, 0x41, 0x0f, 0x8b, 0xa2, 0x20, 0xac, 0x3a, 0x9d, 0x94, 0xa2, 0x14,
	0x32, 0xf3, 0x32, 0x4b, 0x32, 0x13, 0x73, 0x4a, 0x32, 0x8a, 0x52, 0x53, 0x21, 0x5e, 0x49, 0xce,
	0xcf, 0xd1, 0x4f, 0x2e, 0x86, 0x79, 0x08, 0x10, 0x00, 0x00, 0xff, 0xff, 0xf9, 0x49, 0x2f, 0x87,
	0x1c, 0x01, 0x00, 0x00,
}
