// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs/proto/message/characterSync.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CharacterSyncToS struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CharacterSyncToS) Reset()         { *m = CharacterSyncToS{} }
func (m *CharacterSyncToS) String() string { return proto.CompactTextString(m) }
func (*CharacterSyncToS) ProtoMessage()    {}
func (*CharacterSyncToS) Descriptor() ([]byte, []int) {
	return fileDescriptor_5896d908b09f87b9, []int{0}
}

func (m *CharacterSyncToS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CharacterSyncToS.Unmarshal(m, b)
}
func (m *CharacterSyncToS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CharacterSyncToS.Marshal(b, m, deterministic)
}
func (m *CharacterSyncToS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CharacterSyncToS.Merge(m, src)
}
func (m *CharacterSyncToS) XXX_Size() int {
	return xxx_messageInfo_CharacterSyncToS.Size(m)
}
func (m *CharacterSyncToS) XXX_DiscardUnknown() {
	xxx_messageInfo_CharacterSyncToS.DiscardUnknown(m)
}

var xxx_messageInfo_CharacterSyncToS proto.InternalMessageInfo

type CharacterSyncToC struct {
	IsAll                *bool        `protobuf:"varint,1,req,name=isAll" json:"isAll,omitempty"`
	Characters           []*Character `protobuf:"bytes,2,rep,name=characters" json:"characters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CharacterSyncToC) Reset()         { *m = CharacterSyncToC{} }
func (m *CharacterSyncToC) String() string { return proto.CompactTextString(m) }
func (*CharacterSyncToC) ProtoMessage()    {}
func (*CharacterSyncToC) Descriptor() ([]byte, []int) {
	return fileDescriptor_5896d908b09f87b9, []int{1}
}

func (m *CharacterSyncToC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CharacterSyncToC.Unmarshal(m, b)
}
func (m *CharacterSyncToC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CharacterSyncToC.Marshal(b, m, deterministic)
}
func (m *CharacterSyncToC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CharacterSyncToC.Merge(m, src)
}
func (m *CharacterSyncToC) XXX_Size() int {
	return xxx_messageInfo_CharacterSyncToC.Size(m)
}
func (m *CharacterSyncToC) XXX_DiscardUnknown() {
	xxx_messageInfo_CharacterSyncToC.DiscardUnknown(m)
}

var xxx_messageInfo_CharacterSyncToC proto.InternalMessageInfo

func (m *CharacterSyncToC) GetIsAll() bool {
	if m != nil && m.IsAll != nil {
		return *m.IsAll
	}
	return false
}

func (m *CharacterSyncToC) GetCharacters() []*Character {
	if m != nil {
		return m.Characters
	}
	return nil
}

type Character struct {
	CharacterID          *int32   `protobuf:"varint,1,opt,name=CharacterID" json:"CharacterID,omitempty"`
	Level                *int32   `protobuf:"varint,2,opt,name=Level" json:"Level,omitempty"`
	CurrentExp           *int32   `protobuf:"varint,3,opt,name=CurrentExp" json:"CurrentExp,omitempty"`
	BreakLevel           *int32   `protobuf:"varint,4,opt,name=BreakLevel" json:"BreakLevel,omitempty"`
	WeaponID             *uint32  `protobuf:"varint,6,opt,name=WeaponID" json:"WeaponID,omitempty"`
	EquipIDs             []uint32 `protobuf:"varint,7,rep,name=EquipIDs" json:"EquipIDs,omitempty"`
	GetTime              *int64   `protobuf:"varint,8,opt,name=getTime" json:"getTime,omitempty"`
	FavorLevel           *int32   `protobuf:"varint,9,opt,name=favorLevel" json:"favorLevel,omitempty"`
	FavorExp             *int32   `protobuf:"varint,10,opt,name=favorExp" json:"favorExp,omitempty"`
	IsLike               *bool    `protobuf:"varint,11,opt,name=isLike" json:"isLike,omitempty"`
	Skills               []*Skill `protobuf:"bytes,12,rep,name=skills" json:"skills,omitempty"`
	GeneLevel            *int32   `protobuf:"varint,13,opt,name=geneLevel" json:"geneLevel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Character) Reset()         { *m = Character{} }
func (m *Character) String() string { return proto.CompactTextString(m) }
func (*Character) ProtoMessage()    {}
func (*Character) Descriptor() ([]byte, []int) {
	return fileDescriptor_5896d908b09f87b9, []int{2}
}

func (m *Character) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Character.Unmarshal(m, b)
}
func (m *Character) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Character.Marshal(b, m, deterministic)
}
func (m *Character) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Character.Merge(m, src)
}
func (m *Character) XXX_Size() int {
	return xxx_messageInfo_Character.Size(m)
}
func (m *Character) XXX_DiscardUnknown() {
	xxx_messageInfo_Character.DiscardUnknown(m)
}

var xxx_messageInfo_Character proto.InternalMessageInfo

func (m *Character) GetCharacterID() int32 {
	if m != nil && m.CharacterID != nil {
		return *m.CharacterID
	}
	return 0
}

func (m *Character) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *Character) GetCurrentExp() int32 {
	if m != nil && m.CurrentExp != nil {
		return *m.CurrentExp
	}
	return 0
}

func (m *Character) GetBreakLevel() int32 {
	if m != nil && m.BreakLevel != nil {
		return *m.BreakLevel
	}
	return 0
}

func (m *Character) GetWeaponID() uint32 {
	if m != nil && m.WeaponID != nil {
		return *m.WeaponID
	}
	return 0
}

func (m *Character) GetEquipIDs() []uint32 {
	if m != nil {
		return m.EquipIDs
	}
	return nil
}

func (m *Character) GetGetTime() int64 {
	if m != nil && m.GetTime != nil {
		return *m.GetTime
	}
	return 0
}

func (m *Character) GetFavorLevel() int32 {
	if m != nil && m.FavorLevel != nil {
		return *m.FavorLevel
	}
	return 0
}

func (m *Character) GetFavorExp() int32 {
	if m != nil && m.FavorExp != nil {
		return *m.FavorExp
	}
	return 0
}

func (m *Character) GetIsLike() bool {
	if m != nil && m.IsLike != nil {
		return *m.IsLike
	}
	return false
}

func (m *Character) GetSkills() []*Skill {
	if m != nil {
		return m.Skills
	}
	return nil
}

func (m *Character) GetGeneLevel() int32 {
	if m != nil && m.GeneLevel != nil {
		return *m.GeneLevel
	}
	return 0
}

type CharacterTeam struct {
	CharacterList        []int32  `protobuf:"varint,1,rep,name=characterList" json:"characterList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CharacterTeam) Reset()         { *m = CharacterTeam{} }
func (m *CharacterTeam) String() string { return proto.CompactTextString(m) }
func (*CharacterTeam) ProtoMessage()    {}
func (*CharacterTeam) Descriptor() ([]byte, []int) {
	return fileDescriptor_5896d908b09f87b9, []int{3}
}

func (m *CharacterTeam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CharacterTeam.Unmarshal(m, b)
}
func (m *CharacterTeam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CharacterTeam.Marshal(b, m, deterministic)
}
func (m *CharacterTeam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CharacterTeam.Merge(m, src)
}
func (m *CharacterTeam) XXX_Size() int {
	return xxx_messageInfo_CharacterTeam.Size(m)
}
func (m *CharacterTeam) XXX_DiscardUnknown() {
	xxx_messageInfo_CharacterTeam.DiscardUnknown(m)
}

var xxx_messageInfo_CharacterTeam proto.InternalMessageInfo

func (m *CharacterTeam) GetCharacterList() []int32 {
	if m != nil {
		return m.CharacterList
	}
	return nil
}

func init() {
	proto.RegisterType((*CharacterSyncToS)(nil), "message.characterSync_toS")
	proto.RegisterType((*CharacterSyncToC)(nil), "message.characterSync_toC")
	proto.RegisterType((*Character)(nil), "message.character")
	proto.RegisterType((*CharacterTeam)(nil), "message.characterTeam")
}

func init() {
	proto.RegisterFile("cs/proto/message/characterSync.proto", fileDescriptor_5896d908b09f87b9)
}

var fileDescriptor_5896d908b09f87b9 = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0x51, 0xab, 0xd3, 0x30,
	0x14, 0xc7, 0x69, 0xeb, 0xb6, 0xee, 0xcc, 0x09, 0x46, 0x91, 0x70, 0x51, 0x09, 0xe5, 0x22, 0x7d,
	0x5a, 0xe1, 0x82, 0x1f, 0xc0, 0xbb, 0xed, 0x61, 0xb0, 0xa7, 0x6c, 0x20, 0x08, 0x22, 0xa1, 0x1c,
	0xb7, 0xb0, 0xb6, 0xa9, 0x49, 0x36, 0xf4, 0x53, 0xfb, 0x15, 0x2e, 0x69, 0xda, 0xae, 0x63, 0x8f,
	0xbf, 0xff, 0xef, 0x24, 0xff, 0x70, 0x08, 0x3c, 0xe6, 0x26, 0xab, 0xb5, 0xb2, 0x2a, 0x2b, 0xd1,
	0x18, 0x71, 0xc0, 0x2c, 0x3f, 0x0a, 0x2d, 0x72, 0x8b, 0x7a, 0xf7, 0xaf, 0xca, 0x17, 0x8d, 0x23,
	0x93, 0x56, 0x3e, 0x7c, 0xba, 0x1f, 0x57, 0x65, 0xa9, 0x2a, 0x3f, 0x97, 0xbc, 0x83, 0xb7, 0x37,
	0xc7, 0x7f, 0x59, 0xb5, 0x4b, 0x7e, 0xde, 0x87, 0x4b, 0xf2, 0x1e, 0x46, 0xd2, 0x7c, 0x2b, 0x0a,
	0x1a, 0xb0, 0x30, 0x8d, 0xb9, 0x07, 0xf2, 0x04, 0xd0, 0x8f, 0x1a, 0x1a, 0xb2, 0x28, 0x9d, 0x3d,
	0x91, 0x45, 0x5b, 0xb5, 0xe8, 0x15, 0x1f, 0x4c, 0x25, 0xff, 0x43, 0x98, 0xf6, 0x48, 0x18, 0xcc,
	0x96, 0x1d, 0x6c, 0x56, 0x34, 0x60, 0x41, 0x3a, 0xe2, 0xc3, 0xc8, 0x35, 0x6f, 0xf1, 0x82, 0x05,
	0x0d, 0x1b, 0xe7, 0x81, 0x7c, 0x06, 0x58, 0x9e, 0xb5, 0xc6, 0xca, 0xae, 0xff, 0xd6, 0x34, 0x6a,
	0xd4, 0x20, 0x71, 0xfe, 0x59, 0xa3, 0x38, 0xf9, 0xa3, 0xaf, 0xbc, 0xbf, 0x26, 0xe4, 0x01, 0xe2,
	0xef, 0x28, 0x6a, 0x55, 0x6d, 0x56, 0x74, 0xcc, 0x82, 0x74, 0xce, 0x7b, 0x76, 0x6e, 0xfd, 0xe7,
	0x2c, 0xeb, 0xcd, 0xca, 0xd0, 0x09, 0x8b, 0x9c, 0xeb, 0x98, 0x50, 0x98, 0x1c, 0xd0, 0xee, 0x65,
	0x89, 0x34, 0x66, 0x41, 0x1a, 0xf1, 0x0e, 0x5d, 0xe3, 0x6f, 0x71, 0x51, 0xda, 0x37, 0x4e, 0x7d,
	0xe3, 0x35, 0x71, 0xb7, 0x36, 0xe4, 0xde, 0x0b, 0x8d, 0xed, 0x99, 0x7c, 0x80, 0xb1, 0x34, 0x5b,
	0x79, 0x42, 0x3a, 0x63, 0x41, 0x1a, 0xf3, 0x96, 0xc8, 0x17, 0x18, 0x9b, 0x93, 0x2c, 0x0a, 0x43,
	0x5f, 0x37, 0xbb, 0x7d, 0xd3, 0xef, 0x76, 0xe7, 0x62, 0xde, 0x5a, 0xf2, 0x11, 0xa6, 0x07, 0xac,
	0xd0, 0x57, 0xcf, 0x9b, 0xcb, 0xaf, 0x41, 0xf2, 0x15, 0xe6, 0xfd, 0xc2, 0xf7, 0x28, 0x4a, 0xf2,
	0x38, 0x08, 0xb6, 0xd2, 0x58, 0x1a, 0xb0, 0x28, 0x1d, 0xf1, 0xdb, 0xf0, 0x39, 0xf9, 0xc1, 0x64,
	0x25, 0xad, 0x14, 0x85, 0x3d, 0x6a, 0x44, 0xff, 0x8f, 0x72, 0x55, 0x64, 0xb9, 0xe9, 0x7e, 0xd3,
	0x4b, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd1, 0x74, 0x72, 0x50, 0x8f, 0x02, 0x00, 0x00,
}
