// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs/proto/message/common.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TeamEnum int32

const (
	TeamEnum_NO_TEAM       TeamEnum = 1
	TeamEnum_MAXROLECOUNT  TeamEnum = 2
	TeamEnum_AGREED        TeamEnum = 3
	TeamEnum_DISAGREE      TeamEnum = 4
	TeamEnum_JOINOTHERTEAM TeamEnum = 5
	TeamEnum_OFF_LINE      TeamEnum = 6
	TeamEnum_IN_BATTLE     TeamEnum = 7
)

var TeamEnum_name = map[int32]string{
	1: "NO_TEAM",
	2: "MAXROLECOUNT",
	3: "AGREED",
	4: "DISAGREE",
	5: "JOINOTHERTEAM",
	6: "OFF_LINE",
	7: "IN_BATTLE",
}

var TeamEnum_value = map[string]int32{
	"NO_TEAM":       1,
	"MAXROLECOUNT":  2,
	"AGREED":        3,
	"DISAGREE":      4,
	"JOINOTHERTEAM": 5,
	"OFF_LINE":      6,
	"IN_BATTLE":     7,
}

func (x TeamEnum) Enum() *TeamEnum {
	p := new(TeamEnum)
	*p = x
	return p
}

func (x TeamEnum) String() string {
	return proto.EnumName(TeamEnum_name, int32(x))
}

func (x *TeamEnum) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TeamEnum_value, data, "TeamEnum")
	if err != nil {
		return err
	}
	*x = TeamEnum(value)
	return nil
}

func (TeamEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9b5fd84d4f72fe50, []int{0}
}

type ViewObj struct {
	UserID               *string   `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	RoleID               *uint64   `protobuf:"varint,2,opt,name=roleID" json:"roleID,omitempty"`
	Name                 *string   `protobuf:"bytes,3,opt,name=Name" json:"Name,omitempty"`
	Level                *int32    `protobuf:"varint,4,opt,name=Level" json:"Level,omitempty"`
	Pos                  *Position `protobuf:"bytes,5,opt,name=pos" json:"pos,omitempty"`
	Angle                *int32    `protobuf:"varint,6,opt,name=Angle" json:"Angle,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ViewObj) Reset()         { *m = ViewObj{} }
func (m *ViewObj) String() string { return proto.CompactTextString(m) }
func (*ViewObj) ProtoMessage()    {}
func (*ViewObj) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b5fd84d4f72fe50, []int{0}
}

func (m *ViewObj) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewObj.Unmarshal(m, b)
}
func (m *ViewObj) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewObj.Marshal(b, m, deterministic)
}
func (m *ViewObj) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewObj.Merge(m, src)
}
func (m *ViewObj) XXX_Size() int {
	return xxx_messageInfo_ViewObj.Size(m)
}
func (m *ViewObj) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewObj.DiscardUnknown(m)
}

var xxx_messageInfo_ViewObj proto.InternalMessageInfo

func (m *ViewObj) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *ViewObj) GetRoleID() uint64 {
	if m != nil && m.RoleID != nil {
		return *m.RoleID
	}
	return 0
}

func (m *ViewObj) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ViewObj) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *ViewObj) GetPos() *Position {
	if m != nil {
		return m.Pos
	}
	return nil
}

func (m *ViewObj) GetAngle() int32 {
	if m != nil && m.Angle != nil {
		return *m.Angle
	}
	return 0
}

type Attr struct {
	Id                   *int32   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Val                  *int64   `protobuf:"varint,2,opt,name=val" json:"val,omitempty"`
	NextRefreshTime      *int64   `protobuf:"varint,3,opt,name=NextRefreshTime" json:"NextRefreshTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Attr) Reset()         { *m = Attr{} }
func (m *Attr) String() string { return proto.CompactTextString(m) }
func (*Attr) ProtoMessage()    {}
func (*Attr) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b5fd84d4f72fe50, []int{1}
}

func (m *Attr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attr.Unmarshal(m, b)
}
func (m *Attr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attr.Marshal(b, m, deterministic)
}
func (m *Attr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attr.Merge(m, src)
}
func (m *Attr) XXX_Size() int {
	return xxx_messageInfo_Attr.Size(m)
}
func (m *Attr) XXX_DiscardUnknown() {
	xxx_messageInfo_Attr.DiscardUnknown(m)
}

var xxx_messageInfo_Attr proto.InternalMessageInfo

func (m *Attr) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Attr) GetVal() int64 {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return 0
}

func (m *Attr) GetNextRefreshTime() int64 {
	if m != nil && m.NextRefreshTime != nil {
		return *m.NextRefreshTime
	}
	return 0
}

type BattleAttr struct {
	Id                   *int32   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Val                  *float64 `protobuf:"fixed64,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BattleAttr) Reset()         { *m = BattleAttr{} }
func (m *BattleAttr) String() string { return proto.CompactTextString(m) }
func (*BattleAttr) ProtoMessage()    {}
func (*BattleAttr) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b5fd84d4f72fe50, []int{2}
}

func (m *BattleAttr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BattleAttr.Unmarshal(m, b)
}
func (m *BattleAttr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BattleAttr.Marshal(b, m, deterministic)
}
func (m *BattleAttr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BattleAttr.Merge(m, src)
}
func (m *BattleAttr) XXX_Size() int {
	return xxx_messageInfo_BattleAttr.Size(m)
}
func (m *BattleAttr) XXX_DiscardUnknown() {
	xxx_messageInfo_BattleAttr.DiscardUnknown(m)
}

var xxx_messageInfo_BattleAttr proto.InternalMessageInfo

func (m *BattleAttr) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *BattleAttr) GetVal() float64 {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return 0
}

type Position struct {
	X                    *int32   `protobuf:"varint,1,opt,name=x" json:"x,omitempty"`
	Y                    *int32   `protobuf:"varint,2,opt,name=y" json:"y,omitempty"`
	Z                    *int32   `protobuf:"varint,3,opt,name=z" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b5fd84d4f72fe50, []int{3}
}

func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Position) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *Position) GetZ() int32 {
	if m != nil && m.Z != nil {
		return *m.Z
	}
	return 0
}

type Vector3D struct {
	X                    *int32   `protobuf:"varint,1,opt,name=x" json:"x,omitempty"`
	Y                    *int32   `protobuf:"varint,2,opt,name=y" json:"y,omitempty"`
	Z                    *int32   `protobuf:"varint,3,opt,name=z" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vector3D) Reset()         { *m = Vector3D{} }
func (m *Vector3D) String() string { return proto.CompactTextString(m) }
func (*Vector3D) ProtoMessage()    {}
func (*Vector3D) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b5fd84d4f72fe50, []int{4}
}

func (m *Vector3D) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vector3D.Unmarshal(m, b)
}
func (m *Vector3D) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vector3D.Marshal(b, m, deterministic)
}
func (m *Vector3D) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vector3D.Merge(m, src)
}
func (m *Vector3D) XXX_Size() int {
	return xxx_messageInfo_Vector3D.Size(m)
}
func (m *Vector3D) XXX_DiscardUnknown() {
	xxx_messageInfo_Vector3D.DiscardUnknown(m)
}

var xxx_messageInfo_Vector3D proto.InternalMessageInfo

func (m *Vector3D) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Vector3D) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *Vector3D) GetZ() int32 {
	if m != nil && m.Z != nil {
		return *m.Z
	}
	return 0
}

type AwardInfo struct {
	Type                 *int32   `protobuf:"varint,1,opt,name=Type" json:"Type,omitempty"`
	ID                   *int32   `protobuf:"varint,2,opt,name=ID" json:"ID,omitempty"`
	Count                *int32   `protobuf:"varint,3,opt,name=Count" json:"Count,omitempty"`
	InsID                *uint32  `protobuf:"varint,4,opt,name=InsID" json:"InsID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AwardInfo) Reset()         { *m = AwardInfo{} }
func (m *AwardInfo) String() string { return proto.CompactTextString(m) }
func (*AwardInfo) ProtoMessage()    {}
func (*AwardInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b5fd84d4f72fe50, []int{5}
}

func (m *AwardInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AwardInfo.Unmarshal(m, b)
}
func (m *AwardInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AwardInfo.Marshal(b, m, deterministic)
}
func (m *AwardInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AwardInfo.Merge(m, src)
}
func (m *AwardInfo) XXX_Size() int {
	return xxx_messageInfo_AwardInfo.Size(m)
}
func (m *AwardInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AwardInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AwardInfo proto.InternalMessageInfo

func (m *AwardInfo) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *AwardInfo) GetID() int32 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *AwardInfo) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *AwardInfo) GetInsID() uint32 {
	if m != nil && m.InsID != nil {
		return *m.InsID
	}
	return 0
}

type Award struct {
	AwardInfos           []*AwardInfo `protobuf:"bytes,1,rep,name=AwardInfos" json:"AwardInfos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Award) Reset()         { *m = Award{} }
func (m *Award) String() string { return proto.CompactTextString(m) }
func (*Award) ProtoMessage()    {}
func (*Award) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b5fd84d4f72fe50, []int{6}
}

func (m *Award) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Award.Unmarshal(m, b)
}
func (m *Award) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Award.Marshal(b, m, deterministic)
}
func (m *Award) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Award.Merge(m, src)
}
func (m *Award) XXX_Size() int {
	return xxx_messageInfo_Award.Size(m)
}
func (m *Award) XXX_DiscardUnknown() {
	xxx_messageInfo_Award.DiscardUnknown(m)
}

var xxx_messageInfo_Award proto.InternalMessageInfo

func (m *Award) GetAwardInfos() []*AwardInfo {
	if m != nil {
		return m.AwardInfos
	}
	return nil
}

type CostItem struct {
	ItemID               *int32   `protobuf:"varint,1,opt,name=ItemID" json:"ItemID,omitempty"`
	Count                *int32   `protobuf:"varint,2,opt,name=Count" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CostItem) Reset()         { *m = CostItem{} }
func (m *CostItem) String() string { return proto.CompactTextString(m) }
func (*CostItem) ProtoMessage()    {}
func (*CostItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b5fd84d4f72fe50, []int{7}
}

func (m *CostItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CostItem.Unmarshal(m, b)
}
func (m *CostItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CostItem.Marshal(b, m, deterministic)
}
func (m *CostItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CostItem.Merge(m, src)
}
func (m *CostItem) XXX_Size() int {
	return xxx_messageInfo_CostItem.Size(m)
}
func (m *CostItem) XXX_DiscardUnknown() {
	xxx_messageInfo_CostItem.DiscardUnknown(m)
}

var xxx_messageInfo_CostItem proto.InternalMessageInfo

func (m *CostItem) GetItemID() int32 {
	if m != nil && m.ItemID != nil {
		return *m.ItemID
	}
	return 0
}

func (m *CostItem) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

type Skill struct {
	SkillID              *int32   `protobuf:"varint,1,opt,name=skillID" json:"skillID,omitempty"`
	Level                *int32   `protobuf:"varint,2,opt,name=level" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Skill) Reset()         { *m = Skill{} }
func (m *Skill) String() string { return proto.CompactTextString(m) }
func (*Skill) ProtoMessage()    {}
func (*Skill) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b5fd84d4f72fe50, []int{8}
}

func (m *Skill) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Skill.Unmarshal(m, b)
}
func (m *Skill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Skill.Marshal(b, m, deterministic)
}
func (m *Skill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Skill.Merge(m, src)
}
func (m *Skill) XXX_Size() int {
	return xxx_messageInfo_Skill.Size(m)
}
func (m *Skill) XXX_DiscardUnknown() {
	xxx_messageInfo_Skill.DiscardUnknown(m)
}

var xxx_messageInfo_Skill proto.InternalMessageInfo

func (m *Skill) GetSkillID() int32 {
	if m != nil && m.SkillID != nil {
		return *m.SkillID
	}
	return 0
}

func (m *Skill) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

type Mail struct {
	Title                *string  `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Sender               *string  `protobuf:"bytes,2,opt,name=sender" json:"sender,omitempty"`
	CreateTime           *int64   `protobuf:"varint,3,opt,name=createTime" json:"createTime,omitempty"`
	ExpireTime           *int64   `protobuf:"varint,4,opt,name=expireTime" json:"expireTime,omitempty"`
	Content              *string  `protobuf:"bytes,5,opt,name=content" json:"content,omitempty"`
	Awards               *Award   `protobuf:"bytes,6,opt,name=awards" json:"awards,omitempty"`
	Read                 *bool    `protobuf:"varint,7,opt,name=read" json:"read,omitempty"`
	Id                   *uint32  `protobuf:"varint,8,req,name=id" json:"id,omitempty"`
	Deleted              *bool    `protobuf:"varint,9,opt,name=deleted" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mail) Reset()         { *m = Mail{} }
func (m *Mail) String() string { return proto.CompactTextString(m) }
func (*Mail) ProtoMessage()    {}
func (*Mail) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b5fd84d4f72fe50, []int{9}
}

func (m *Mail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mail.Unmarshal(m, b)
}
func (m *Mail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mail.Marshal(b, m, deterministic)
}
func (m *Mail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mail.Merge(m, src)
}
func (m *Mail) XXX_Size() int {
	return xxx_messageInfo_Mail.Size(m)
}
func (m *Mail) XXX_DiscardUnknown() {
	xxx_messageInfo_Mail.DiscardUnknown(m)
}

var xxx_messageInfo_Mail proto.InternalMessageInfo

func (m *Mail) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *Mail) GetSender() string {
	if m != nil && m.Sender != nil {
		return *m.Sender
	}
	return ""
}

func (m *Mail) GetCreateTime() int64 {
	if m != nil && m.CreateTime != nil {
		return *m.CreateTime
	}
	return 0
}

func (m *Mail) GetExpireTime() int64 {
	if m != nil && m.ExpireTime != nil {
		return *m.ExpireTime
	}
	return 0
}

func (m *Mail) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *Mail) GetAwards() *Award {
	if m != nil {
		return m.Awards
	}
	return nil
}

func (m *Mail) GetRead() bool {
	if m != nil && m.Read != nil {
		return *m.Read
	}
	return false
}

func (m *Mail) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Mail) GetDeleted() bool {
	if m != nil && m.Deleted != nil {
		return *m.Deleted
	}
	return false
}

func init() {
	proto.RegisterEnum("message.TeamEnum", TeamEnum_name, TeamEnum_value)
	proto.RegisterType((*ViewObj)(nil), "message.viewObj")
	proto.RegisterType((*Attr)(nil), "message.Attr")
	proto.RegisterType((*BattleAttr)(nil), "message.BattleAttr")
	proto.RegisterType((*Position)(nil), "message.Position")
	proto.RegisterType((*Vector3D)(nil), "message.Vector3D")
	proto.RegisterType((*AwardInfo)(nil), "message.AwardInfo")
	proto.RegisterType((*Award)(nil), "message.Award")
	proto.RegisterType((*CostItem)(nil), "message.CostItem")
	proto.RegisterType((*Skill)(nil), "message.Skill")
	proto.RegisterType((*Mail)(nil), "message.Mail")
}

func init() { proto.RegisterFile("cs/proto/message/common.proto", fileDescriptor_9b5fd84d4f72fe50) }

var fileDescriptor_9b5fd84d4f72fe50 = []byte{
	// 627 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xd5, 0x26, 0x71, 0x3e, 0x26, 0x4d, 0x71, 0x57, 0x08, 0xf9, 0x02, 0xb2, 0x8c, 0x84, 0x2c,
	0x0e, 0x89, 0x14, 0x90, 0x40, 0xe2, 0x94, 0x36, 0x2e, 0x18, 0xa5, 0x31, 0xda, 0x1a, 0x84, 0xe0,
	0x50, 0x19, 0x7b, 0xda, 0x1a, 0x6c, 0x6f, 0xe4, 0xdd, 0xb6, 0x69, 0x7f, 0x0c, 0xbf, 0x92, 0x1f,
	0x80, 0x76, 0xbd, 0x49, 0x03, 0x17, 0xc4, 0xc9, 0xf3, 0x66, 0xe6, 0xcd, 0x3e, 0xcd, 0x3c, 0x19,
	0x1e, 0xa7, 0x62, 0xb2, 0xaa, 0xb9, 0xe4, 0x93, 0x12, 0x85, 0x48, 0x2e, 0x70, 0x92, 0xf2, 0xb2,
	0xe4, 0xd5, 0x58, 0x27, 0x69, 0xcf, 0x64, 0xbd, 0x9f, 0x04, 0x7a, 0xd7, 0x39, 0xde, 0x44, 0xdf,
	0xbe, 0xd3, 0x47, 0xd0, 0xbd, 0x12, 0x58, 0x87, 0x73, 0x87, 0xb8, 0xc4, 0x1f, 0x30, 0x83, 0x54,
	0xbe, 0xe6, 0x05, 0x86, 0x73, 0xa7, 0xe5, 0x12, 0xbf, 0xc3, 0x0c, 0xa2, 0x14, 0x3a, 0xcb, 0xa4,
	0x44, 0xa7, 0xad, 0xbb, 0x75, 0x4c, 0x1f, 0x82, 0xb5, 0xc0, 0x6b, 0x2c, 0x9c, 0x8e, 0x4b, 0x7c,
	0x8b, 0x35, 0x80, 0x3e, 0x85, 0xf6, 0x8a, 0x0b, 0xc7, 0x72, 0x89, 0x3f, 0x9c, 0x1e, 0x8c, 0xcd,
	0xe3, 0xe3, 0x0f, 0x5c, 0xe4, 0x32, 0xe7, 0x15, 0x53, 0x55, 0x45, 0x9d, 0x55, 0x17, 0x05, 0x3a,
	0xdd, 0x86, 0xaa, 0x81, 0xc7, 0xa0, 0x33, 0x93, 0xb2, 0xa6, 0xfb, 0xd0, 0xca, 0x33, 0x2d, 0xcc,
	0x62, 0xad, 0x3c, 0xa3, 0x36, 0xb4, 0xaf, 0x93, 0x42, 0x2b, 0x6a, 0x33, 0x15, 0x52, 0x1f, 0x1e,
	0x2c, 0x71, 0x2d, 0x19, 0x9e, 0xd7, 0x28, 0x2e, 0xe3, 0xdc, 0x28, 0x6b, 0xb3, 0xbf, 0xd3, 0xde,
	0x18, 0xe0, 0x30, 0x91, 0xb2, 0xc0, 0x7f, 0x4d, 0x26, 0x7a, 0xb2, 0xf7, 0x12, 0xfa, 0x1b, 0xa9,
	0x74, 0x0f, 0xc8, 0xda, 0x34, 0x93, 0xb5, 0x42, 0xb7, 0xba, 0xd3, 0x62, 0xe4, 0x56, 0xa1, 0x3b,
	0xfd, 0xa6, 0xc5, 0xc8, 0x9d, 0x62, 0x7d, 0xc2, 0x54, 0xf2, 0xfa, 0xc5, 0xfc, 0x3f, 0x58, 0x5f,
	0x61, 0x30, 0xbb, 0x49, 0xea, 0x2c, 0xac, 0xce, 0xb9, 0xda, 0x70, 0x7c, 0xbb, 0x42, 0xc3, 0xd4,
	0xb1, 0x92, 0x6b, 0x2e, 0x61, 0xb1, 0x56, 0x38, 0x57, 0x6b, 0x3b, 0xe2, 0x57, 0x95, 0x34, 0x23,
	0x1a, 0xa0, 0xb2, 0x61, 0x25, 0xc2, 0xb9, 0xbe, 0xc3, 0x88, 0x35, 0xc0, 0x7b, 0x03, 0x96, 0x1e,
	0x4e, 0xa7, 0x00, 0xdb, 0x57, 0x84, 0x43, 0xdc, 0xb6, 0x3f, 0x9c, 0xd2, 0xed, 0x5d, 0xb6, 0x25,
	0xb6, 0xd3, 0xe5, 0xbd, 0x86, 0xfe, 0x11, 0x17, 0x32, 0x94, 0x58, 0x2a, 0x4b, 0xa8, 0xaf, 0xb1,
	0x8a, 0xc5, 0x0c, 0xba, 0x17, 0xd3, 0xda, 0x11, 0xe3, 0xbd, 0x02, 0xeb, 0xf4, 0x47, 0x5e, 0x14,
	0xd4, 0x81, 0x9e, 0x50, 0xc1, 0x96, 0xb7, 0x81, 0x8a, 0x58, 0x68, 0xdf, 0x18, 0xa2, 0x06, 0xde,
	0x2f, 0x02, 0x9d, 0x93, 0x24, 0x2f, 0x54, 0x59, 0xe6, 0xb2, 0x40, 0xe3, 0xcc, 0x06, 0x28, 0x15,
	0x02, 0xab, 0x0c, 0x6b, 0xcd, 0x1a, 0x30, 0x83, 0xe8, 0x13, 0x80, 0xb4, 0xc6, 0x44, 0xe2, 0x8e,
	0x09, 0x76, 0x32, 0xaa, 0x8e, 0xeb, 0x55, 0x5e, 0x37, 0xf5, 0x4e, 0x53, 0xbf, 0xcf, 0x28, 0x99,
	0x29, 0xaf, 0x24, 0x56, 0x52, 0x5b, 0x76, 0xc0, 0x36, 0x90, 0x3e, 0x83, 0x6e, 0xa2, 0x36, 0x22,
	0xb4, 0x49, 0x87, 0xd3, 0xfd, 0x3f, 0x77, 0xc6, 0x4c, 0x55, 0x1d, 0xae, 0xc6, 0x24, 0x73, 0x7a,
	0x2e, 0xf1, 0xfb, 0x4c, 0xc7, 0xc6, 0x67, 0x7d, 0xb7, 0xe5, 0x8f, 0xb4, 0xcf, 0x1c, 0xe8, 0x65,
	0x58, 0xa0, 0xc4, 0xcc, 0x19, 0xe8, 0xb6, 0x0d, 0x7c, 0x2e, 0xa0, 0x1f, 0x63, 0x52, 0x06, 0xd5,
	0x55, 0x49, 0x87, 0xd0, 0x5b, 0x46, 0x67, 0x71, 0x30, 0x3b, 0xb1, 0x09, 0xb5, 0x61, 0xef, 0x64,
	0xf6, 0x99, 0x45, 0x8b, 0xe0, 0x28, 0xfa, 0xb8, 0x8c, 0xed, 0x16, 0x05, 0xe8, 0xce, 0xde, 0xb2,
	0x20, 0x98, 0xdb, 0x6d, 0xba, 0x07, 0xfd, 0x79, 0x78, 0xaa, 0xa1, 0xdd, 0xa1, 0x07, 0x30, 0x7a,
	0x1f, 0x85, 0xcb, 0x28, 0x7e, 0x17, 0x30, 0x4d, 0xb7, 0x54, 0x43, 0x74, 0x7c, 0x7c, 0xb6, 0x08,
	0x97, 0x81, 0xdd, 0xa5, 0x23, 0x18, 0x84, 0xcb, 0xb3, 0xc3, 0x59, 0x1c, 0x2f, 0x02, 0xbb, 0x77,
	0xe8, 0x7d, 0x71, 0xf3, 0x2a, 0x97, 0x79, 0x52, 0xc8, 0xcb, 0x1a, 0xb1, 0xf9, 0x7b, 0xa4, 0xbc,
	0x98, 0xa4, 0x62, 0xf3, 0x0f, 0xf9, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x5c, 0x73, 0xdf, 0x64, 0x56,
	0x04, 0x00, 0x00,
}
