// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs/proto/message/drawCardDraw.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DrawCardDrawToS struct {
	LibID                *int32   `protobuf:"varint,1,opt,name=libID" json:"libID,omitempty"`
	DrawCount            *int32   `protobuf:"varint,2,opt,name=drawCount" json:"drawCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DrawCardDrawToS) Reset()         { *m = DrawCardDrawToS{} }
func (m *DrawCardDrawToS) String() string { return proto.CompactTextString(m) }
func (*DrawCardDrawToS) ProtoMessage()    {}
func (*DrawCardDrawToS) Descriptor() ([]byte, []int) {
	return fileDescriptor_19d0369704b60d31, []int{0}
}

func (m *DrawCardDrawToS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrawCardDrawToS.Unmarshal(m, b)
}
func (m *DrawCardDrawToS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrawCardDrawToS.Marshal(b, m, deterministic)
}
func (m *DrawCardDrawToS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrawCardDrawToS.Merge(m, src)
}
func (m *DrawCardDrawToS) XXX_Size() int {
	return xxx_messageInfo_DrawCardDrawToS.Size(m)
}
func (m *DrawCardDrawToS) XXX_DiscardUnknown() {
	xxx_messageInfo_DrawCardDrawToS.DiscardUnknown(m)
}

var xxx_messageInfo_DrawCardDrawToS proto.InternalMessageInfo

func (m *DrawCardDrawToS) GetLibID() int32 {
	if m != nil && m.LibID != nil {
		return *m.LibID
	}
	return 0
}

func (m *DrawCardDrawToS) GetDrawCount() int32 {
	if m != nil && m.DrawCount != nil {
		return *m.DrawCount
	}
	return 0
}

type DrawCardDrawToC struct {
	LibID                *int32           `protobuf:"varint,1,opt,name=libID" json:"libID,omitempty"`
	GuaranteeID          *int32           `protobuf:"varint,2,opt,name=guaranteeID" json:"guaranteeID,omitempty"`
	GuaranteeCount       *int32           `protobuf:"varint,3,opt,name=guaranteeCount" json:"guaranteeCount,omitempty"`
	AwardList            []*DrawCardAward `protobuf:"bytes,4,rep,name=awardList" json:"awardList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DrawCardDrawToC) Reset()         { *m = DrawCardDrawToC{} }
func (m *DrawCardDrawToC) String() string { return proto.CompactTextString(m) }
func (*DrawCardDrawToC) ProtoMessage()    {}
func (*DrawCardDrawToC) Descriptor() ([]byte, []int) {
	return fileDescriptor_19d0369704b60d31, []int{1}
}

func (m *DrawCardDrawToC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrawCardDrawToC.Unmarshal(m, b)
}
func (m *DrawCardDrawToC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrawCardDrawToC.Marshal(b, m, deterministic)
}
func (m *DrawCardDrawToC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrawCardDrawToC.Merge(m, src)
}
func (m *DrawCardDrawToC) XXX_Size() int {
	return xxx_messageInfo_DrawCardDrawToC.Size(m)
}
func (m *DrawCardDrawToC) XXX_DiscardUnknown() {
	xxx_messageInfo_DrawCardDrawToC.DiscardUnknown(m)
}

var xxx_messageInfo_DrawCardDrawToC proto.InternalMessageInfo

func (m *DrawCardDrawToC) GetLibID() int32 {
	if m != nil && m.LibID != nil {
		return *m.LibID
	}
	return 0
}

func (m *DrawCardDrawToC) GetGuaranteeID() int32 {
	if m != nil && m.GuaranteeID != nil {
		return *m.GuaranteeID
	}
	return 0
}

func (m *DrawCardDrawToC) GetGuaranteeCount() int32 {
	if m != nil && m.GuaranteeCount != nil {
		return *m.GuaranteeCount
	}
	return 0
}

func (m *DrawCardDrawToC) GetAwardList() []*DrawCardAward {
	if m != nil {
		return m.AwardList
	}
	return nil
}

type DrawCardAward struct {
	AwardInfo            *AwardInfo `protobuf:"bytes,1,opt,name=awardInfo" json:"awardInfo,omitempty"`
	State                *int32     `protobuf:"varint,2,opt,name=state" json:"state,omitempty"`
	Timestamp            *int64     `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DrawCardAward) Reset()         { *m = DrawCardAward{} }
func (m *DrawCardAward) String() string { return proto.CompactTextString(m) }
func (*DrawCardAward) ProtoMessage()    {}
func (*DrawCardAward) Descriptor() ([]byte, []int) {
	return fileDescriptor_19d0369704b60d31, []int{2}
}

func (m *DrawCardAward) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrawCardAward.Unmarshal(m, b)
}
func (m *DrawCardAward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrawCardAward.Marshal(b, m, deterministic)
}
func (m *DrawCardAward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrawCardAward.Merge(m, src)
}
func (m *DrawCardAward) XXX_Size() int {
	return xxx_messageInfo_DrawCardAward.Size(m)
}
func (m *DrawCardAward) XXX_DiscardUnknown() {
	xxx_messageInfo_DrawCardAward.DiscardUnknown(m)
}

var xxx_messageInfo_DrawCardAward proto.InternalMessageInfo

func (m *DrawCardAward) GetAwardInfo() *AwardInfo {
	if m != nil {
		return m.AwardInfo
	}
	return nil
}

func (m *DrawCardAward) GetState() int32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

func (m *DrawCardAward) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*DrawCardDrawToS)(nil), "message.drawCardDraw_toS")
	proto.RegisterType((*DrawCardDrawToC)(nil), "message.drawCardDraw_toC")
	proto.RegisterType((*DrawCardAward)(nil), "message.drawCardAward")
}

func init() {
	proto.RegisterFile("cs/proto/message/drawCardDraw.proto", fileDescriptor_19d0369704b60d31)
}

var fileDescriptor_19d0369704b60d31 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x51, 0x4b, 0xc3, 0x30,
	0x14, 0x85, 0xa9, 0x75, 0xc8, 0x52, 0x14, 0x09, 0x22, 0x45, 0x14, 0x4a, 0x05, 0xd9, 0x53, 0x2b,
	0xc3, 0x3f, 0x30, 0x57, 0x84, 0x82, 0x4f, 0xf5, 0xcd, 0x17, 0xb9, 0xb6, 0x71, 0x06, 0x9a, 0x64,
	0x24, 0xb7, 0xf4, 0x2f, 0xf9, 0x33, 0xa5, 0x49, 0xba, 0x4e, 0xc7, 0x1e, 0xef, 0x39, 0x5f, 0x4f,
	0xcf, 0xcd, 0x25, 0xf7, 0xb5, 0xc9, 0xb7, 0x5a, 0xa1, 0xca, 0x05, 0x33, 0x06, 0x36, 0x2c, 0x6f,
	0x34, 0xf4, 0x6b, 0xd0, 0x4d, 0xa1, 0xa1, 0xcf, 0xac, 0x45, 0xcf, 0xbc, 0x77, 0x73, 0x77, 0x40,
	0xd7, 0x4a, 0x08, 0x25, 0x1d, 0x97, 0xbe, 0x90, 0xcb, 0xfd, 0xaf, 0x3f, 0x50, 0xbd, 0xd1, 0x2b,
	0x32, 0x6b, 0xf9, 0x67, 0x59, 0xc4, 0x41, 0x12, 0x2c, 0x66, 0x95, 0x1b, 0xe8, 0x2d, 0x99, 0x5b,
	0x52, 0x75, 0x12, 0xe3, 0x13, 0xeb, 0x4c, 0x42, 0xfa, 0x13, 0x1c, 0x04, 0xad, 0x8f, 0x04, 0x25,
	0x24, 0xda, 0x74, 0xa0, 0x41, 0x22, 0x63, 0x65, 0xe1, 0xa3, 0xf6, 0x25, 0xfa, 0x40, 0x2e, 0x76,
	0xa3, 0xfb, 0x5f, 0x68, 0xa1, 0x7f, 0x2a, 0x7d, 0x22, 0x73, 0xe8, 0x41, 0x37, 0xaf, 0xdc, 0x60,
	0x7c, 0x9a, 0x84, 0x8b, 0x68, 0x79, 0x9d, 0xf9, 0x35, 0xb3, 0xb1, 0xcd, 0x6a, 0x20, 0xaa, 0x09,
	0x4c, 0x3b, 0x72, 0xfe, 0xc7, 0xa3, 0x8f, 0x3e, 0xa6, 0x94, 0x5f, 0xca, 0x56, 0x8d, 0x96, 0x74,
	0x17, 0xb3, 0x1a, 0x9d, 0x6a, 0x82, 0x86, 0xc5, 0x0c, 0x02, 0x32, 0x5f, 0xde, 0x0d, 0xc3, 0x0b,
	0x21, 0x17, 0xcc, 0x20, 0x88, 0xad, 0x6d, 0x1c, 0x56, 0x93, 0xf0, 0x9c, 0xbe, 0x27, 0x5c, 0x72,
	0xe4, 0xd0, 0xe2, 0xb7, 0x66, 0xcc, 0x1d, 0xa5, 0x56, 0x6d, 0x5e, 0x9b, 0xf1, 0x34, 0xbf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x67, 0xac, 0x65, 0x2b, 0xdb, 0x01, 0x00, 0x00,
}
