// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs/proto/message/drawCardPoolChoose.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DrawCardPoolChooseToS struct {
	LibID                *int32   `protobuf:"varint,1,opt,name=libID" json:"libID,omitempty"`
	PoolIndex            *int32   `protobuf:"varint,2,opt,name=poolIndex" json:"poolIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DrawCardPoolChooseToS) Reset()         { *m = DrawCardPoolChooseToS{} }
func (m *DrawCardPoolChooseToS) String() string { return proto.CompactTextString(m) }
func (*DrawCardPoolChooseToS) ProtoMessage()    {}
func (*DrawCardPoolChooseToS) Descriptor() ([]byte, []int) {
	return fileDescriptor_d166201d9f42aaa4, []int{0}
}

func (m *DrawCardPoolChooseToS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrawCardPoolChooseToS.Unmarshal(m, b)
}
func (m *DrawCardPoolChooseToS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrawCardPoolChooseToS.Marshal(b, m, deterministic)
}
func (m *DrawCardPoolChooseToS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrawCardPoolChooseToS.Merge(m, src)
}
func (m *DrawCardPoolChooseToS) XXX_Size() int {
	return xxx_messageInfo_DrawCardPoolChooseToS.Size(m)
}
func (m *DrawCardPoolChooseToS) XXX_DiscardUnknown() {
	xxx_messageInfo_DrawCardPoolChooseToS.DiscardUnknown(m)
}

var xxx_messageInfo_DrawCardPoolChooseToS proto.InternalMessageInfo

func (m *DrawCardPoolChooseToS) GetLibID() int32 {
	if m != nil && m.LibID != nil {
		return *m.LibID
	}
	return 0
}

func (m *DrawCardPoolChooseToS) GetPoolIndex() int32 {
	if m != nil && m.PoolIndex != nil {
		return *m.PoolIndex
	}
	return 0
}

type DrawCardPoolChooseToC struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DrawCardPoolChooseToC) Reset()         { *m = DrawCardPoolChooseToC{} }
func (m *DrawCardPoolChooseToC) String() string { return proto.CompactTextString(m) }
func (*DrawCardPoolChooseToC) ProtoMessage()    {}
func (*DrawCardPoolChooseToC) Descriptor() ([]byte, []int) {
	return fileDescriptor_d166201d9f42aaa4, []int{1}
}

func (m *DrawCardPoolChooseToC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrawCardPoolChooseToC.Unmarshal(m, b)
}
func (m *DrawCardPoolChooseToC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrawCardPoolChooseToC.Marshal(b, m, deterministic)
}
func (m *DrawCardPoolChooseToC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrawCardPoolChooseToC.Merge(m, src)
}
func (m *DrawCardPoolChooseToC) XXX_Size() int {
	return xxx_messageInfo_DrawCardPoolChooseToC.Size(m)
}
func (m *DrawCardPoolChooseToC) XXX_DiscardUnknown() {
	xxx_messageInfo_DrawCardPoolChooseToC.DiscardUnknown(m)
}

var xxx_messageInfo_DrawCardPoolChooseToC proto.InternalMessageInfo

func init() {
	proto.RegisterType((*DrawCardPoolChooseToS)(nil), "message.drawCardPoolChoose_toS")
	proto.RegisterType((*DrawCardPoolChooseToC)(nil), "message.drawCardPoolChoose_toC")
}

func init() {
	proto.RegisterFile("cs/proto/message/drawCardPoolChoose.proto", fileDescriptor_d166201d9f42aaa4)
}

var fileDescriptor_d166201d9f42aaa4 = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x4c, 0x2e, 0xd6, 0x2f,
	0x28, 0xca, 0x2f, 0xc9, 0xd7, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x4f, 0x29, 0x4a,
	0x2c, 0x77, 0x4e, 0x2c, 0x4a, 0x09, 0xc8, 0xcf, 0xcf, 0x71, 0xce, 0xc8, 0xcf, 0x2f, 0x4e, 0xd5,
	0x03, 0x2b, 0x10, 0x62, 0x87, 0xaa, 0x50, 0xf2, 0xe1, 0x12, 0xc3, 0x54, 0x14, 0x5f, 0x92, 0x1f,
	0x2c, 0x24, 0xc2, 0xc5, 0x9a, 0x93, 0x99, 0xe4, 0xe9, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x1a,
	0x04, 0xe1, 0x08, 0xc9, 0x70, 0x71, 0x16, 0xe4, 0xe7, 0xe7, 0x78, 0xe6, 0xa5, 0xa4, 0x56, 0x48,
	0x30, 0x81, 0x65, 0x10, 0x02, 0x4a, 0x12, 0x38, 0x4c, 0x73, 0x76, 0x52, 0x8a, 0x52, 0xc8, 0xcc,
	0xcb, 0x2c, 0xc9, 0x4c, 0xcc, 0x29, 0xc9, 0x28, 0x4a, 0x4d, 0x85, 0xb8, 0x33, 0x39, 0x3f, 0x47,
	0x3f, 0xb9, 0x18, 0xe6, 0x5a, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf1, 0x01, 0x1b, 0x4d, 0xc0,
	0x00, 0x00, 0x00,
}
