// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs/proto/message/drawCardSync.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DrawCardSyncToS struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DrawCardSyncToS) Reset()         { *m = DrawCardSyncToS{} }
func (m *DrawCardSyncToS) String() string { return proto.CompactTextString(m) }
func (*DrawCardSyncToS) ProtoMessage()    {}
func (*DrawCardSyncToS) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f6dc2c45187c498, []int{0}
}

func (m *DrawCardSyncToS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrawCardSyncToS.Unmarshal(m, b)
}
func (m *DrawCardSyncToS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrawCardSyncToS.Marshal(b, m, deterministic)
}
func (m *DrawCardSyncToS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrawCardSyncToS.Merge(m, src)
}
func (m *DrawCardSyncToS) XXX_Size() int {
	return xxx_messageInfo_DrawCardSyncToS.Size(m)
}
func (m *DrawCardSyncToS) XXX_DiscardUnknown() {
	xxx_messageInfo_DrawCardSyncToS.DiscardUnknown(m)
}

var xxx_messageInfo_DrawCardSyncToS proto.InternalMessageInfo

type DrawCardSyncToC struct {
	IsAll                *bool                 `protobuf:"varint,1,req,name=isAll" json:"isAll,omitempty"`
	PoolIndex            []*DrawCardPool       `protobuf:"bytes,2,rep,name=poolIndex" json:"poolIndex,omitempty"`
	Guarantee            []*DrawCardGuarantee  `protobuf:"bytes,3,rep,name=guarantee" json:"guarantee,omitempty"`
	DailyTimes           []*DrawCardDailyTimes `protobuf:"bytes,4,rep,name=dailyTimes" json:"dailyTimes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DrawCardSyncToC) Reset()         { *m = DrawCardSyncToC{} }
func (m *DrawCardSyncToC) String() string { return proto.CompactTextString(m) }
func (*DrawCardSyncToC) ProtoMessage()    {}
func (*DrawCardSyncToC) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f6dc2c45187c498, []int{1}
}

func (m *DrawCardSyncToC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrawCardSyncToC.Unmarshal(m, b)
}
func (m *DrawCardSyncToC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrawCardSyncToC.Marshal(b, m, deterministic)
}
func (m *DrawCardSyncToC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrawCardSyncToC.Merge(m, src)
}
func (m *DrawCardSyncToC) XXX_Size() int {
	return xxx_messageInfo_DrawCardSyncToC.Size(m)
}
func (m *DrawCardSyncToC) XXX_DiscardUnknown() {
	xxx_messageInfo_DrawCardSyncToC.DiscardUnknown(m)
}

var xxx_messageInfo_DrawCardSyncToC proto.InternalMessageInfo

func (m *DrawCardSyncToC) GetIsAll() bool {
	if m != nil && m.IsAll != nil {
		return *m.IsAll
	}
	return false
}

func (m *DrawCardSyncToC) GetPoolIndex() []*DrawCardPool {
	if m != nil {
		return m.PoolIndex
	}
	return nil
}

func (m *DrawCardSyncToC) GetGuarantee() []*DrawCardGuarantee {
	if m != nil {
		return m.Guarantee
	}
	return nil
}

func (m *DrawCardSyncToC) GetDailyTimes() []*DrawCardDailyTimes {
	if m != nil {
		return m.DailyTimes
	}
	return nil
}

type DrawCardPool struct {
	LibID                *int32   `protobuf:"varint,1,opt,name=libID" json:"libID,omitempty"`
	PoolIndex            *int32   `protobuf:"varint,2,opt,name=poolIndex" json:"poolIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DrawCardPool) Reset()         { *m = DrawCardPool{} }
func (m *DrawCardPool) String() string { return proto.CompactTextString(m) }
func (*DrawCardPool) ProtoMessage()    {}
func (*DrawCardPool) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f6dc2c45187c498, []int{2}
}

func (m *DrawCardPool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrawCardPool.Unmarshal(m, b)
}
func (m *DrawCardPool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrawCardPool.Marshal(b, m, deterministic)
}
func (m *DrawCardPool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrawCardPool.Merge(m, src)
}
func (m *DrawCardPool) XXX_Size() int {
	return xxx_messageInfo_DrawCardPool.Size(m)
}
func (m *DrawCardPool) XXX_DiscardUnknown() {
	xxx_messageInfo_DrawCardPool.DiscardUnknown(m)
}

var xxx_messageInfo_DrawCardPool proto.InternalMessageInfo

func (m *DrawCardPool) GetLibID() int32 {
	if m != nil && m.LibID != nil {
		return *m.LibID
	}
	return 0
}

func (m *DrawCardPool) GetPoolIndex() int32 {
	if m != nil && m.PoolIndex != nil {
		return *m.PoolIndex
	}
	return 0
}

type DrawCardDailyTimes struct {
	LibID                *int32   `protobuf:"varint,1,opt,name=libID" json:"libID,omitempty"`
	Times                *int32   `protobuf:"varint,2,opt,name=times" json:"times,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DrawCardDailyTimes) Reset()         { *m = DrawCardDailyTimes{} }
func (m *DrawCardDailyTimes) String() string { return proto.CompactTextString(m) }
func (*DrawCardDailyTimes) ProtoMessage()    {}
func (*DrawCardDailyTimes) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f6dc2c45187c498, []int{3}
}

func (m *DrawCardDailyTimes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrawCardDailyTimes.Unmarshal(m, b)
}
func (m *DrawCardDailyTimes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrawCardDailyTimes.Marshal(b, m, deterministic)
}
func (m *DrawCardDailyTimes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrawCardDailyTimes.Merge(m, src)
}
func (m *DrawCardDailyTimes) XXX_Size() int {
	return xxx_messageInfo_DrawCardDailyTimes.Size(m)
}
func (m *DrawCardDailyTimes) XXX_DiscardUnknown() {
	xxx_messageInfo_DrawCardDailyTimes.DiscardUnknown(m)
}

var xxx_messageInfo_DrawCardDailyTimes proto.InternalMessageInfo

func (m *DrawCardDailyTimes) GetLibID() int32 {
	if m != nil && m.LibID != nil {
		return *m.LibID
	}
	return 0
}

func (m *DrawCardDailyTimes) GetTimes() int32 {
	if m != nil && m.Times != nil {
		return *m.Times
	}
	return 0
}

type DrawCardGuarantee struct {
	GuaranteeID          *int32   `protobuf:"varint,1,opt,name=guaranteeID" json:"guaranteeID,omitempty"`
	GuaranteeCount       *int32   `protobuf:"varint,2,opt,name=guaranteeCount" json:"guaranteeCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DrawCardGuarantee) Reset()         { *m = DrawCardGuarantee{} }
func (m *DrawCardGuarantee) String() string { return proto.CompactTextString(m) }
func (*DrawCardGuarantee) ProtoMessage()    {}
func (*DrawCardGuarantee) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f6dc2c45187c498, []int{4}
}

func (m *DrawCardGuarantee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrawCardGuarantee.Unmarshal(m, b)
}
func (m *DrawCardGuarantee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrawCardGuarantee.Marshal(b, m, deterministic)
}
func (m *DrawCardGuarantee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrawCardGuarantee.Merge(m, src)
}
func (m *DrawCardGuarantee) XXX_Size() int {
	return xxx_messageInfo_DrawCardGuarantee.Size(m)
}
func (m *DrawCardGuarantee) XXX_DiscardUnknown() {
	xxx_messageInfo_DrawCardGuarantee.DiscardUnknown(m)
}

var xxx_messageInfo_DrawCardGuarantee proto.InternalMessageInfo

func (m *DrawCardGuarantee) GetGuaranteeID() int32 {
	if m != nil && m.GuaranteeID != nil {
		return *m.GuaranteeID
	}
	return 0
}

func (m *DrawCardGuarantee) GetGuaranteeCount() int32 {
	if m != nil && m.GuaranteeCount != nil {
		return *m.GuaranteeCount
	}
	return 0
}

func init() {
	proto.RegisterType((*DrawCardSyncToS)(nil), "message.drawCardSync_toS")
	proto.RegisterType((*DrawCardSyncToC)(nil), "message.drawCardSync_toC")
	proto.RegisterType((*DrawCardPool)(nil), "message.drawCardPool")
	proto.RegisterType((*DrawCardDailyTimes)(nil), "message.drawCardDailyTimes")
	proto.RegisterType((*DrawCardGuarantee)(nil), "message.drawCardGuarantee")
}

func init() {
	proto.RegisterFile("cs/proto/message/drawCardSync.proto", fileDescriptor_8f6dc2c45187c498)
}

var fileDescriptor_8f6dc2c45187c498 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4d, 0x4b, 0xc3, 0x30,
	0x18, 0xa6, 0x9b, 0x45, 0xf7, 0x4e, 0x44, 0x5f, 0x26, 0x14, 0xf5, 0x50, 0x22, 0x48, 0x4f, 0x2d,
	0xe8, 0x45, 0xf0, 0xa2, 0xeb, 0x40, 0x76, 0x93, 0xce, 0x93, 0x20, 0x12, 0xdb, 0x30, 0x03, 0x59,
	0x33, 0x92, 0x0c, 0xdd, 0xff, 0xf4, 0x07, 0xc9, 0x9a, 0x7e, 0x69, 0xf0, 0xf8, 0x7c, 0x26, 0x0f,
	0xbc, 0x70, 0x99, 0xeb, 0x64, 0xad, 0xa4, 0x91, 0xc9, 0x8a, 0x69, 0x4d, 0x97, 0x2c, 0x29, 0x14,
	0xfd, 0x4c, 0xa9, 0x2a, 0x16, 0xdb, 0x32, 0x8f, 0x2b, 0x09, 0xf7, 0x6b, 0x8d, 0x20, 0x1c, 0xf7,
	0xe5, 0x37, 0x23, 0x17, 0xe4, 0xdb, 0x73, 0xc8, 0x14, 0x27, 0xe0, 0x73, 0xfd, 0x20, 0x44, 0xe0,
	0x85, 0x83, 0xe8, 0x20, 0xb3, 0x00, 0x6f, 0x60, 0xb4, 0x96, 0x52, 0xcc, 0xcb, 0x82, 0x7d, 0x05,
	0x83, 0x70, 0x18, 0x8d, 0xaf, 0x4f, 0xe3, 0xba, 0x3b, 0x6e, 0x3a, 0x9e, 0xa4, 0x14, 0x59, 0xe7,
	0xc3, 0x5b, 0x18, 0x2d, 0x37, 0x54, 0xd1, 0xd2, 0x30, 0x16, 0x0c, 0xab, 0xd0, 0x99, 0x13, 0x7a,
	0x6c, 0x1c, 0x59, 0x67, 0xc6, 0x3b, 0x80, 0x82, 0x72, 0xb1, 0x7d, 0xe6, 0x2b, 0xa6, 0x83, 0xbd,
	0x2a, 0x7a, 0xee, 0x44, 0x67, 0xad, 0x25, 0xeb, 0xd9, 0xc9, 0x14, 0x0e, 0xfb, 0x3f, 0xda, 0x2d,
	0x12, 0xfc, 0x7d, 0x3e, 0x0b, 0xbc, 0xd0, 0x8b, 0xfc, 0xcc, 0x02, 0xbc, 0xf8, 0xbd, 0x68, 0xa7,
	0x74, 0x04, 0xb9, 0x07, 0x74, 0x5f, 0xf9, 0xa7, 0x69, 0x02, 0xbe, 0xa9, 0xfe, 0x69, 0x5b, 0x2c,
	0x20, 0xaf, 0x70, 0xe2, 0x4c, 0xc4, 0x10, 0xc6, 0xed, 0xc8, 0xb6, 0xa6, 0x4f, 0xe1, 0x15, 0x1c,
	0xb5, 0x30, 0x95, 0x9b, 0xd2, 0xd4, 0xad, 0x7f, 0xd8, 0x29, 0x79, 0x09, 0x79, 0xc9, 0x0d, 0xa7,
	0xc2, 0x7c, 0x28, 0xc6, 0xec, 0x25, 0xe4, 0x52, 0x24, 0xb9, 0x6e, 0xee, 0xe1, 0x27, 0x00, 0x00,
	0xff, 0xff, 0xb1, 0x53, 0xb0, 0x19, 0x22, 0x02, 0x00, 0x00,
}
