// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs/proto/message/equipSync.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EquipSyncToS struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EquipSyncToS) Reset()         { *m = EquipSyncToS{} }
func (m *EquipSyncToS) String() string { return proto.CompactTextString(m) }
func (*EquipSyncToS) ProtoMessage()    {}
func (*EquipSyncToS) Descriptor() ([]byte, []int) {
	return fileDescriptor_3793271f2ab7fe8f, []int{0}
}

func (m *EquipSyncToS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EquipSyncToS.Unmarshal(m, b)
}
func (m *EquipSyncToS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EquipSyncToS.Marshal(b, m, deterministic)
}
func (m *EquipSyncToS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EquipSyncToS.Merge(m, src)
}
func (m *EquipSyncToS) XXX_Size() int {
	return xxx_messageInfo_EquipSyncToS.Size(m)
}
func (m *EquipSyncToS) XXX_DiscardUnknown() {
	xxx_messageInfo_EquipSyncToS.DiscardUnknown(m)
}

var xxx_messageInfo_EquipSyncToS proto.InternalMessageInfo

type EquipSyncToC struct {
	IsAll                *bool    `protobuf:"varint,1,req,name=isAll" json:"isAll,omitempty"`
	Equips               []*Equip `protobuf:"bytes,2,rep,name=equips" json:"equips,omitempty"`
	UseCap               *int32   `protobuf:"varint,3,req,name=useCap" json:"useCap,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EquipSyncToC) Reset()         { *m = EquipSyncToC{} }
func (m *EquipSyncToC) String() string { return proto.CompactTextString(m) }
func (*EquipSyncToC) ProtoMessage()    {}
func (*EquipSyncToC) Descriptor() ([]byte, []int) {
	return fileDescriptor_3793271f2ab7fe8f, []int{1}
}

func (m *EquipSyncToC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EquipSyncToC.Unmarshal(m, b)
}
func (m *EquipSyncToC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EquipSyncToC.Marshal(b, m, deterministic)
}
func (m *EquipSyncToC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EquipSyncToC.Merge(m, src)
}
func (m *EquipSyncToC) XXX_Size() int {
	return xxx_messageInfo_EquipSyncToC.Size(m)
}
func (m *EquipSyncToC) XXX_DiscardUnknown() {
	xxx_messageInfo_EquipSyncToC.DiscardUnknown(m)
}

var xxx_messageInfo_EquipSyncToC proto.InternalMessageInfo

func (m *EquipSyncToC) GetIsAll() bool {
	if m != nil && m.IsAll != nil {
		return *m.IsAll
	}
	return false
}

func (m *EquipSyncToC) GetEquips() []*Equip {
	if m != nil {
		return m.Equips
	}
	return nil
}

func (m *EquipSyncToC) GetUseCap() int32 {
	if m != nil && m.UseCap != nil {
		return *m.UseCap
	}
	return 0
}

type Equip struct {
	ID                   *uint32  `protobuf:"varint,1,req,name=ID" json:"ID,omitempty"`
	ConfigID             *int32   `protobuf:"varint,2,opt,name=ConfigID" json:"ConfigID,omitempty"`
	Level                *int32   `protobuf:"varint,3,opt,name=level" json:"level,omitempty"`
	Exp                  *int32   `protobuf:"varint,4,opt,name=exp" json:"exp,omitempty"`
	RandomAttribId       *int32   `protobuf:"varint,11,opt,name=randomAttribId" json:"randomAttribId,omitempty"`
	RefineLevel          []int32  `protobuf:"varint,5,rep,name=refineLevel" json:"refineLevel,omitempty"`
	EquipCharacterID     *int32   `protobuf:"varint,6,opt,name=equipCharacterID" json:"equipCharacterID,omitempty"`
	IsLock               *bool    `protobuf:"varint,8,opt,name=isLock" json:"isLock,omitempty"`
	IsRemove             *bool    `protobuf:"varint,9,opt,name=isRemove" json:"isRemove,omitempty"`
	GetTime              *int64   `protobuf:"varint,10,opt,name=getTime" json:"getTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Equip) Reset()         { *m = Equip{} }
func (m *Equip) String() string { return proto.CompactTextString(m) }
func (*Equip) ProtoMessage()    {}
func (*Equip) Descriptor() ([]byte, []int) {
	return fileDescriptor_3793271f2ab7fe8f, []int{2}
}

func (m *Equip) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Equip.Unmarshal(m, b)
}
func (m *Equip) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Equip.Marshal(b, m, deterministic)
}
func (m *Equip) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Equip.Merge(m, src)
}
func (m *Equip) XXX_Size() int {
	return xxx_messageInfo_Equip.Size(m)
}
func (m *Equip) XXX_DiscardUnknown() {
	xxx_messageInfo_Equip.DiscardUnknown(m)
}

var xxx_messageInfo_Equip proto.InternalMessageInfo

func (m *Equip) GetID() uint32 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *Equip) GetConfigID() int32 {
	if m != nil && m.ConfigID != nil {
		return *m.ConfigID
	}
	return 0
}

func (m *Equip) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *Equip) GetExp() int32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

func (m *Equip) GetRandomAttribId() int32 {
	if m != nil && m.RandomAttribId != nil {
		return *m.RandomAttribId
	}
	return 0
}

func (m *Equip) GetRefineLevel() []int32 {
	if m != nil {
		return m.RefineLevel
	}
	return nil
}

func (m *Equip) GetEquipCharacterID() int32 {
	if m != nil && m.EquipCharacterID != nil {
		return *m.EquipCharacterID
	}
	return 0
}

func (m *Equip) GetIsLock() bool {
	if m != nil && m.IsLock != nil {
		return *m.IsLock
	}
	return false
}

func (m *Equip) GetIsRemove() bool {
	if m != nil && m.IsRemove != nil {
		return *m.IsRemove
	}
	return false
}

func (m *Equip) GetGetTime() int64 {
	if m != nil && m.GetTime != nil {
		return *m.GetTime
	}
	return 0
}

func init() {
	proto.RegisterType((*EquipSyncToS)(nil), "message.equipSync_toS")
	proto.RegisterType((*EquipSyncToC)(nil), "message.equipSync_toC")
	proto.RegisterType((*Equip)(nil), "message.equip")
}

func init() { proto.RegisterFile("cs/proto/message/equipSync.proto", fileDescriptor_3793271f2ab7fe8f) }

var fileDescriptor_3793271f2ab7fe8f = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xcf, 0x6a, 0xe3, 0x30,
	0x10, 0xc6, 0xb1, 0xbc, 0x4e, 0xbc, 0x13, 0x92, 0x0d, 0x62, 0x59, 0xc4, 0x9e, 0x84, 0x0f, 0x41,
	0xf4, 0x10, 0x43, 0xdf, 0x20, 0xb5, 0x2f, 0x86, 0x9c, 0x94, 0x9e, 0x7a, 0x29, 0xae, 0x33, 0x49,
	0x44, 0x6d, 0xcb, 0x95, 0x94, 0xd0, 0x3e, 0x4d, 0x5f, 0xb5, 0x58, 0x71, 0x42, 0xff, 0xdc, 0xf4,
	0xfb, 0x7d, 0xe2, 0x63, 0x86, 0x01, 0x5e, 0xd9, 0xb4, 0x33, 0xda, 0xe9, 0xb4, 0x41, 0x6b, 0xcb,
	0x3d, 0xa6, 0xf8, 0x72, 0x54, 0xdd, 0xe6, 0xad, 0xad, 0x96, 0xde, 0xd3, 0xf1, 0x10, 0x24, 0x7f,
	0x60, 0x7a, 0xcd, 0x1e, 0x9d, 0xde, 0x24, 0xf8, 0x55, 0x64, 0xf4, 0x2f, 0x44, 0xca, 0xae, 0xea,
	0x9a, 0x05, 0x9c, 0x88, 0x58, 0x9e, 0x81, 0x2e, 0x60, 0xe4, 0xbf, 0x59, 0x46, 0x78, 0x28, 0x26,
	0xb7, 0xb3, 0xe5, 0xd0, 0xb8, 0xf4, 0x5a, 0x0e, 0x29, 0xfd, 0x07, 0xa3, 0xa3, 0xc5, 0xac, 0xec,
	0x58, 0xc8, 0x89, 0x88, 0xe4, 0x40, 0xc9, 0x3b, 0x81, 0xc8, 0x7f, 0xa1, 0x33, 0x20, 0x45, 0xee,
	0xcb, 0xa7, 0x92, 0x14, 0x39, 0xfd, 0x0f, 0x71, 0xa6, 0xdb, 0x9d, 0xda, 0x17, 0x39, 0x23, 0x3c,
	0x10, 0x91, 0xbc, 0x72, 0x3f, 0x4b, 0x8d, 0x27, 0xac, 0x59, 0xe8, 0x83, 0x33, 0xd0, 0x39, 0x84,
	0xf8, 0xda, 0xb1, 0x5f, 0xde, 0xf5, 0x4f, 0xba, 0x80, 0x99, 0x29, 0xdb, 0xad, 0x6e, 0x56, 0xce,
	0x19, 0xf5, 0x54, 0x6c, 0xd9, 0xc4, 0x87, 0xdf, 0x2c, 0xe5, 0x30, 0x31, 0xb8, 0x53, 0x2d, 0xae,
	0x7d, 0x6b, 0xc4, 0x43, 0x11, 0xc9, 0xcf, 0x8a, 0xde, 0xc0, 0xdc, 0x8f, 0x99, 0x1d, 0x4a, 0x53,
	0x56, 0x0e, 0x4d, 0x91, 0xb3, 0x91, 0xef, 0xfa, 0xe1, 0xfb, 0x5d, 0x95, 0x5d, 0xeb, 0xea, 0x99,
	0xc5, 0x3c, 0x10, 0xb1, 0x1c, 0xa8, 0xdf, 0x48, 0x59, 0x89, 0x8d, 0x3e, 0x21, 0xfb, 0xed, 0x93,
	0x2b, 0x53, 0x06, 0xe3, 0x3d, 0xba, 0x7b, 0xd5, 0x20, 0x03, 0x1e, 0x88, 0x50, 0x5e, 0xf0, 0x2e,
	0x79, 0xe0, 0xaa, 0x55, 0x4e, 0x95, 0xb5, 0x3b, 0x18, 0xc4, 0xf3, 0x41, 0x2b, 0x5d, 0xa7, 0x95,
	0xbd, 0x9c, 0xf5, 0x23, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x3f, 0x46, 0xe6, 0xe9, 0x01, 0x00, 0x00,
}
