// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs/proto/message/equipStrengthen.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EquipStrengthenToS struct {
	EquipID              *uint32     `protobuf:"varint,1,req,name=equipID" json:"equipID,omitempty"`
	CostEquipIDs         []uint32    `protobuf:"varint,2,rep,name=costEquipIDs" json:"costEquipIDs,omitempty"`
	CostItems            []*CostItem `protobuf:"bytes,3,rep,name=costItems" json:"costItems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *EquipStrengthenToS) Reset()         { *m = EquipStrengthenToS{} }
func (m *EquipStrengthenToS) String() string { return proto.CompactTextString(m) }
func (*EquipStrengthenToS) ProtoMessage()    {}
func (*EquipStrengthenToS) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40c4120cef76305, []int{0}
}

func (m *EquipStrengthenToS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EquipStrengthenToS.Unmarshal(m, b)
}
func (m *EquipStrengthenToS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EquipStrengthenToS.Marshal(b, m, deterministic)
}
func (m *EquipStrengthenToS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EquipStrengthenToS.Merge(m, src)
}
func (m *EquipStrengthenToS) XXX_Size() int {
	return xxx_messageInfo_EquipStrengthenToS.Size(m)
}
func (m *EquipStrengthenToS) XXX_DiscardUnknown() {
	xxx_messageInfo_EquipStrengthenToS.DiscardUnknown(m)
}

var xxx_messageInfo_EquipStrengthenToS proto.InternalMessageInfo

func (m *EquipStrengthenToS) GetEquipID() uint32 {
	if m != nil && m.EquipID != nil {
		return *m.EquipID
	}
	return 0
}

func (m *EquipStrengthenToS) GetCostEquipIDs() []uint32 {
	if m != nil {
		return m.CostEquipIDs
	}
	return nil
}

func (m *EquipStrengthenToS) GetCostItems() []*CostItem {
	if m != nil {
		return m.CostItems
	}
	return nil
}

type EquipStrengthenToC struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EquipStrengthenToC) Reset()         { *m = EquipStrengthenToC{} }
func (m *EquipStrengthenToC) String() string { return proto.CompactTextString(m) }
func (*EquipStrengthenToC) ProtoMessage()    {}
func (*EquipStrengthenToC) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40c4120cef76305, []int{1}
}

func (m *EquipStrengthenToC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EquipStrengthenToC.Unmarshal(m, b)
}
func (m *EquipStrengthenToC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EquipStrengthenToC.Marshal(b, m, deterministic)
}
func (m *EquipStrengthenToC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EquipStrengthenToC.Merge(m, src)
}
func (m *EquipStrengthenToC) XXX_Size() int {
	return xxx_messageInfo_EquipStrengthenToC.Size(m)
}
func (m *EquipStrengthenToC) XXX_DiscardUnknown() {
	xxx_messageInfo_EquipStrengthenToC.DiscardUnknown(m)
}

var xxx_messageInfo_EquipStrengthenToC proto.InternalMessageInfo

func init() {
	proto.RegisterType((*EquipStrengthenToS)(nil), "message.equipStrengthen_toS")
	proto.RegisterType((*EquipStrengthenToC)(nil), "message.equipStrengthen_toC")
}

func init() {
	proto.RegisterFile("cs/proto/message/equipStrengthen.proto", fileDescriptor_b40c4120cef76305)
}

var fileDescriptor_b40c4120cef76305 = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4b, 0x2e, 0xd6, 0x2f,
	0x28, 0xca, 0x2f, 0xc9, 0xd7, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x4f, 0x2d, 0x2c,
	0xcd, 0x2c, 0x08, 0x2e, 0x29, 0x4a, 0xcd, 0x4b, 0x2f, 0xc9, 0x48, 0xcd, 0xd3, 0x03, 0xcb, 0x0a,
	0xb1, 0x43, 0xa5, 0xa5, 0x64, 0x31, 0x34, 0x24, 0xe7, 0xe7, 0xe6, 0xe6, 0x43, 0xd5, 0x29, 0xb5,
	0x30, 0x72, 0x09, 0xa3, 0x99, 0x10, 0x5f, 0x92, 0x1f, 0x2c, 0x24, 0xc1, 0xc5, 0x0e, 0x16, 0xf6,
	0x74, 0x91, 0x60, 0x54, 0x60, 0xd2, 0xe0, 0x0d, 0x82, 0x71, 0x85, 0x94, 0xb8, 0x78, 0x92, 0xf3,
	0x8b, 0x4b, 0x5c, 0x21, 0xdc, 0x62, 0x09, 0x26, 0x05, 0x66, 0x0d, 0xde, 0x20, 0x14, 0x31, 0x21,
	0x7d, 0x2e, 0x4e, 0x10, 0xdf, 0xb3, 0x24, 0x35, 0xb7, 0x58, 0x82, 0x59, 0x81, 0x59, 0x83, 0xdb,
	0x48, 0x50, 0x0f, 0x6a, 0xbf, 0x9e, 0x33, 0x54, 0x26, 0x08, 0xa1, 0x46, 0x49, 0x14, 0x9b, 0x2b,
	0x9c, 0x9d, 0x94, 0xa2, 0x14, 0x32, 0xf3, 0x32, 0x4b, 0x32, 0x13, 0x73, 0x4a, 0x32, 0x8a, 0x52,
	0x53, 0x21, 0x1e, 0x49, 0xce, 0xcf, 0xd1, 0x4f, 0x2e, 0x86, 0x79, 0x07, 0x10, 0x00, 0x00, 0xff,
	0xff, 0x21, 0x8e, 0x3f, 0x4f, 0x12, 0x01, 0x00, 0x00,
}
