// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs/proto/message/mailDelete.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MailDeleteToS struct {
	MailIDs              []uint32 `protobuf:"varint,1,rep,name=mailIDs" json:"mailIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailDeleteToS) Reset()         { *m = MailDeleteToS{} }
func (m *MailDeleteToS) String() string { return proto.CompactTextString(m) }
func (*MailDeleteToS) ProtoMessage()    {}
func (*MailDeleteToS) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ffbc3e7e3ba972e, []int{0}
}

func (m *MailDeleteToS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailDeleteToS.Unmarshal(m, b)
}
func (m *MailDeleteToS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailDeleteToS.Marshal(b, m, deterministic)
}
func (m *MailDeleteToS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailDeleteToS.Merge(m, src)
}
func (m *MailDeleteToS) XXX_Size() int {
	return xxx_messageInfo_MailDeleteToS.Size(m)
}
func (m *MailDeleteToS) XXX_DiscardUnknown() {
	xxx_messageInfo_MailDeleteToS.DiscardUnknown(m)
}

var xxx_messageInfo_MailDeleteToS proto.InternalMessageInfo

func (m *MailDeleteToS) GetMailIDs() []uint32 {
	if m != nil {
		return m.MailIDs
	}
	return nil
}

type MailDeleteToC struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailDeleteToC) Reset()         { *m = MailDeleteToC{} }
func (m *MailDeleteToC) String() string { return proto.CompactTextString(m) }
func (*MailDeleteToC) ProtoMessage()    {}
func (*MailDeleteToC) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ffbc3e7e3ba972e, []int{1}
}

func (m *MailDeleteToC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailDeleteToC.Unmarshal(m, b)
}
func (m *MailDeleteToC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailDeleteToC.Marshal(b, m, deterministic)
}
func (m *MailDeleteToC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailDeleteToC.Merge(m, src)
}
func (m *MailDeleteToC) XXX_Size() int {
	return xxx_messageInfo_MailDeleteToC.Size(m)
}
func (m *MailDeleteToC) XXX_DiscardUnknown() {
	xxx_messageInfo_MailDeleteToC.DiscardUnknown(m)
}

var xxx_messageInfo_MailDeleteToC proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MailDeleteToS)(nil), "message.mailDelete_toS")
	proto.RegisterType((*MailDeleteToC)(nil), "message.mailDelete_toC")
}

func init() { proto.RegisterFile("cs/proto/message/mailDelete.proto", fileDescriptor_3ffbc3e7e3ba972e) }

var fileDescriptor_3ffbc3e7e3ba972e = []byte{
	// 119 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4c, 0x2e, 0xd6, 0x2f,
	0x28, 0xca, 0x2f, 0xc9, 0xd7, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0xcf, 0x4d, 0xcc,
	0xcc, 0x71, 0x49, 0xcd, 0x49, 0x2d, 0x49, 0xd5, 0x03, 0x4b, 0x08, 0xb1, 0x43, 0x65, 0x94, 0xb4,
	0xb8, 0xf8, 0x10, 0x92, 0xf1, 0x25, 0xf9, 0xc1, 0x42, 0x12, 0x5c, 0xec, 0x20, 0x11, 0x4f, 0x97,
	0x62, 0x09, 0x46, 0x05, 0x66, 0x0d, 0xde, 0x20, 0x18, 0x57, 0x49, 0x00, 0x4d, 0xad, 0xb3, 0x93,
	0x52, 0x94, 0x42, 0x66, 0x5e, 0x66, 0x49, 0x66, 0x62, 0x4e, 0x49, 0x46, 0x51, 0x6a, 0x2a, 0xc4,
	0xd6, 0xe4, 0xfc, 0x1c, 0xfd, 0xe4, 0x62, 0x98, 0xdd, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7f,
	0x77, 0x1d, 0xc0, 0x8e, 0x00, 0x00, 0x00,
}
