// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs/proto/message/mailRead.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MailReadToS struct {
	MailIDs              []uint32 `protobuf:"varint,1,rep,name=mailIDs" json:"mailIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailReadToS) Reset()         { *m = MailReadToS{} }
func (m *MailReadToS) String() string { return proto.CompactTextString(m) }
func (*MailReadToS) ProtoMessage()    {}
func (*MailReadToS) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfd85195b573dc24, []int{0}
}

func (m *MailReadToS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailReadToS.Unmarshal(m, b)
}
func (m *MailReadToS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailReadToS.Marshal(b, m, deterministic)
}
func (m *MailReadToS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailReadToS.Merge(m, src)
}
func (m *MailReadToS) XXX_Size() int {
	return xxx_messageInfo_MailReadToS.Size(m)
}
func (m *MailReadToS) XXX_DiscardUnknown() {
	xxx_messageInfo_MailReadToS.DiscardUnknown(m)
}

var xxx_messageInfo_MailReadToS proto.InternalMessageInfo

func (m *MailReadToS) GetMailIDs() []uint32 {
	if m != nil {
		return m.MailIDs
	}
	return nil
}

type MailReadToC struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailReadToC) Reset()         { *m = MailReadToC{} }
func (m *MailReadToC) String() string { return proto.CompactTextString(m) }
func (*MailReadToC) ProtoMessage()    {}
func (*MailReadToC) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfd85195b573dc24, []int{1}
}

func (m *MailReadToC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailReadToC.Unmarshal(m, b)
}
func (m *MailReadToC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailReadToC.Marshal(b, m, deterministic)
}
func (m *MailReadToC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailReadToC.Merge(m, src)
}
func (m *MailReadToC) XXX_Size() int {
	return xxx_messageInfo_MailReadToC.Size(m)
}
func (m *MailReadToC) XXX_DiscardUnknown() {
	xxx_messageInfo_MailReadToC.DiscardUnknown(m)
}

var xxx_messageInfo_MailReadToC proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MailReadToS)(nil), "message.mailRead_toS")
	proto.RegisterType((*MailReadToC)(nil), "message.mailRead_toC")
}

func init() { proto.RegisterFile("cs/proto/message/mailRead.proto", fileDescriptor_dfd85195b573dc24) }

var fileDescriptor_dfd85195b573dc24 = []byte{
	// 117 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4f, 0x2e, 0xd6, 0x2f,
	0x28, 0xca, 0x2f, 0xc9, 0xd7, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0xcf, 0x4d, 0xcc,
	0xcc, 0x09, 0x4a, 0x4d, 0x4c, 0xd1, 0x03, 0x0b, 0x0b, 0xb1, 0x43, 0xc5, 0x95, 0x34, 0xb8, 0x78,
	0x60, 0x52, 0xf1, 0x25, 0xf9, 0xc1, 0x42, 0x12, 0x5c, 0xec, 0x20, 0xbe, 0xa7, 0x4b, 0xb1, 0x04,
	0xa3, 0x02, 0xb3, 0x06, 0x6f, 0x10, 0x8c, 0xab, 0xc4, 0x87, 0xa2, 0xd2, 0xd9, 0x49, 0x29, 0x4a,
	0x21, 0x33, 0x2f, 0xb3, 0x24, 0x33, 0x31, 0xa7, 0x24, 0xa3, 0x28, 0x35, 0x15, 0x62, 0x5f, 0x72,
	0x7e, 0x8e, 0x7e, 0x72, 0x31, 0xcc, 0x56, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x52, 0xd9,
	0xeb, 0x88, 0x00, 0x00, 0x00,
}
