// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs/proto/message/mainDungeonsSync.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MainDungeon struct {
	Id                   *int32   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Finished             *bool    `protobuf:"varint,2,opt,name=finished" json:"finished,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MainDungeon) Reset()         { *m = MainDungeon{} }
func (m *MainDungeon) String() string { return proto.CompactTextString(m) }
func (*MainDungeon) ProtoMessage()    {}
func (*MainDungeon) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c8418d75e23b51b, []int{0}
}

func (m *MainDungeon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MainDungeon.Unmarshal(m, b)
}
func (m *MainDungeon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MainDungeon.Marshal(b, m, deterministic)
}
func (m *MainDungeon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MainDungeon.Merge(m, src)
}
func (m *MainDungeon) XXX_Size() int {
	return xxx_messageInfo_MainDungeon.Size(m)
}
func (m *MainDungeon) XXX_DiscardUnknown() {
	xxx_messageInfo_MainDungeon.DiscardUnknown(m)
}

var xxx_messageInfo_MainDungeon proto.InternalMessageInfo

func (m *MainDungeon) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *MainDungeon) GetFinished() bool {
	if m != nil && m.Finished != nil {
		return *m.Finished
	}
	return false
}

type MainChapter struct {
	Id                   *int32   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Finished             *bool    `protobuf:"varint,2,opt,name=finished" json:"finished,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MainChapter) Reset()         { *m = MainChapter{} }
func (m *MainChapter) String() string { return proto.CompactTextString(m) }
func (*MainChapter) ProtoMessage()    {}
func (*MainChapter) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c8418d75e23b51b, []int{1}
}

func (m *MainChapter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MainChapter.Unmarshal(m, b)
}
func (m *MainChapter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MainChapter.Marshal(b, m, deterministic)
}
func (m *MainChapter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MainChapter.Merge(m, src)
}
func (m *MainChapter) XXX_Size() int {
	return xxx_messageInfo_MainChapter.Size(m)
}
func (m *MainChapter) XXX_DiscardUnknown() {
	xxx_messageInfo_MainChapter.DiscardUnknown(m)
}

var xxx_messageInfo_MainChapter proto.InternalMessageInfo

func (m *MainChapter) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *MainChapter) GetFinished() bool {
	if m != nil && m.Finished != nil {
		return *m.Finished
	}
	return false
}

type MainDungeonsSyncToS struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MainDungeonsSyncToS) Reset()         { *m = MainDungeonsSyncToS{} }
func (m *MainDungeonsSyncToS) String() string { return proto.CompactTextString(m) }
func (*MainDungeonsSyncToS) ProtoMessage()    {}
func (*MainDungeonsSyncToS) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c8418d75e23b51b, []int{2}
}

func (m *MainDungeonsSyncToS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MainDungeonsSyncToS.Unmarshal(m, b)
}
func (m *MainDungeonsSyncToS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MainDungeonsSyncToS.Marshal(b, m, deterministic)
}
func (m *MainDungeonsSyncToS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MainDungeonsSyncToS.Merge(m, src)
}
func (m *MainDungeonsSyncToS) XXX_Size() int {
	return xxx_messageInfo_MainDungeonsSyncToS.Size(m)
}
func (m *MainDungeonsSyncToS) XXX_DiscardUnknown() {
	xxx_messageInfo_MainDungeonsSyncToS.DiscardUnknown(m)
}

var xxx_messageInfo_MainDungeonsSyncToS proto.InternalMessageInfo

type MainDungeonsSyncToC struct {
	All                  *bool          `protobuf:"varint,1,opt,name=all" json:"all,omitempty"`
	Chapters             []*MainChapter `protobuf:"bytes,2,rep,name=chapters" json:"chapters,omitempty"`
	Dungeons             []*MainDungeon `protobuf:"bytes,3,rep,name=dungeons" json:"dungeons,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MainDungeonsSyncToC) Reset()         { *m = MainDungeonsSyncToC{} }
func (m *MainDungeonsSyncToC) String() string { return proto.CompactTextString(m) }
func (*MainDungeonsSyncToC) ProtoMessage()    {}
func (*MainDungeonsSyncToC) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c8418d75e23b51b, []int{3}
}

func (m *MainDungeonsSyncToC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MainDungeonsSyncToC.Unmarshal(m, b)
}
func (m *MainDungeonsSyncToC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MainDungeonsSyncToC.Marshal(b, m, deterministic)
}
func (m *MainDungeonsSyncToC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MainDungeonsSyncToC.Merge(m, src)
}
func (m *MainDungeonsSyncToC) XXX_Size() int {
	return xxx_messageInfo_MainDungeonsSyncToC.Size(m)
}
func (m *MainDungeonsSyncToC) XXX_DiscardUnknown() {
	xxx_messageInfo_MainDungeonsSyncToC.DiscardUnknown(m)
}

var xxx_messageInfo_MainDungeonsSyncToC proto.InternalMessageInfo

func (m *MainDungeonsSyncToC) GetAll() bool {
	if m != nil && m.All != nil {
		return *m.All
	}
	return false
}

func (m *MainDungeonsSyncToC) GetChapters() []*MainChapter {
	if m != nil {
		return m.Chapters
	}
	return nil
}

func (m *MainDungeonsSyncToC) GetDungeons() []*MainDungeon {
	if m != nil {
		return m.Dungeons
	}
	return nil
}

func init() {
	proto.RegisterType((*MainDungeon)(nil), "message.mainDungeon")
	proto.RegisterType((*MainChapter)(nil), "message.mainChapter")
	proto.RegisterType((*MainDungeonsSyncToS)(nil), "message.mainDungeonsSync_toS")
	proto.RegisterType((*MainDungeonsSyncToC)(nil), "message.mainDungeonsSync_toC")
}

func init() {
	proto.RegisterFile("cs/proto/message/mainDungeonsSync.proto", fileDescriptor_2c8418d75e23b51b)
}

var fileDescriptor_2c8418d75e23b51b = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4f, 0x2e, 0xd6, 0x2f,
	0x28, 0xca, 0x2f, 0xc9, 0xd7, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0xcf, 0x4d, 0xcc,
	0xcc, 0x73, 0x29, 0xcd, 0x4b, 0x4f, 0xcd, 0xcf, 0x2b, 0x0e, 0xae, 0xcc, 0x4b, 0xd6, 0x03, 0x4b,
	0x0b, 0xb1, 0x43, 0xe5, 0x95, 0x2c, 0xb9, 0xb8, 0x91, 0x94, 0x08, 0xf1, 0x71, 0x31, 0x65, 0xa6,
	0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x31, 0x65, 0xa6, 0x08, 0x49, 0x71, 0x71, 0xa4, 0x65,
	0xe6, 0x65, 0x16, 0x67, 0xa4, 0xa6, 0x48, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x04, 0xc1, 0xf9, 0x30,
	0xad, 0xce, 0x19, 0x89, 0x05, 0x25, 0xa9, 0x45, 0x24, 0x69, 0x15, 0xe3, 0x12, 0x41, 0x77, 0x58,
	0x7c, 0x49, 0x7e, 0xb0, 0x52, 0x0f, 0x23, 0x56, 0x09, 0x67, 0x21, 0x01, 0x2e, 0xe6, 0xc4, 0x9c,
	0x1c, 0xb0, 0xe9, 0x1c, 0x41, 0x20, 0xa6, 0x90, 0x01, 0x17, 0x47, 0x32, 0xc4, 0xe6, 0x62, 0x09,
	0x26, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x11, 0x3d, 0xa8, 0xa7, 0xf4, 0x90, 0x9c, 0x15, 0x04, 0x57,
	0x05, 0xd2, 0x91, 0x02, 0x35, 0x57, 0x82, 0x19, 0x8b, 0x0e, 0xa8, 0xa5, 0x41, 0x70, 0x55, 0x4e,
	0x4a, 0x51, 0x0a, 0x99, 0x79, 0x99, 0x25, 0x99, 0x89, 0x39, 0x25, 0x19, 0x45, 0xa9, 0xa9, 0x90,
	0xa0, 0x4d, 0xce, 0xcf, 0xd1, 0x4f, 0x2e, 0x86, 0x05, 0x30, 0x20, 0x00, 0x00, 0xff, 0xff, 0x54,
	0xe3, 0x20, 0x1f, 0x73, 0x01, 0x00, 0x00,
}
