// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs/proto/message/queryRoleInfo.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QueryRoleInfoToS struct {
	QueryArgs            []*QueryRoleInfoArg `protobuf:"bytes,1,rep,name=queryArgs" json:"queryArgs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *QueryRoleInfoToS) Reset()         { *m = QueryRoleInfoToS{} }
func (m *QueryRoleInfoToS) String() string { return proto.CompactTextString(m) }
func (*QueryRoleInfoToS) ProtoMessage()    {}
func (*QueryRoleInfoToS) Descriptor() ([]byte, []int) {
	return fileDescriptor_52b2e20e5cd59395, []int{0}
}

func (m *QueryRoleInfoToS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRoleInfoToS.Unmarshal(m, b)
}
func (m *QueryRoleInfoToS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRoleInfoToS.Marshal(b, m, deterministic)
}
func (m *QueryRoleInfoToS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRoleInfoToS.Merge(m, src)
}
func (m *QueryRoleInfoToS) XXX_Size() int {
	return xxx_messageInfo_QueryRoleInfoToS.Size(m)
}
func (m *QueryRoleInfoToS) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRoleInfoToS.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRoleInfoToS proto.InternalMessageInfo

func (m *QueryRoleInfoToS) GetQueryArgs() []*QueryRoleInfoArg {
	if m != nil {
		return m.QueryArgs
	}
	return nil
}

type QueryRoleInfoArg struct {
	UserID               *string  `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	GameID               *uint64  `protobuf:"varint,2,opt,name=gameID" json:"gameID,omitempty"`
	AttrIDs              []int32  `protobuf:"varint,3,rep,name=attrIDs" json:"attrIDs,omitempty"`
	QueryBase            *bool    `protobuf:"varint,4,opt,name=queryBase" json:"queryBase,omitempty"`
	CharacterIDs         []int32  `protobuf:"varint,5,rep,name=characterIDs" json:"characterIDs,omitempty"`
	WeaponIDs            []uint32 `protobuf:"varint,6,rep,name=weaponIDs" json:"weaponIDs,omitempty"`
	EquipIDs             []uint32 `protobuf:"varint,7,rep,name=equipIDs" json:"equipIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRoleInfoArg) Reset()         { *m = QueryRoleInfoArg{} }
func (m *QueryRoleInfoArg) String() string { return proto.CompactTextString(m) }
func (*QueryRoleInfoArg) ProtoMessage()    {}
func (*QueryRoleInfoArg) Descriptor() ([]byte, []int) {
	return fileDescriptor_52b2e20e5cd59395, []int{1}
}

func (m *QueryRoleInfoArg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRoleInfoArg.Unmarshal(m, b)
}
func (m *QueryRoleInfoArg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRoleInfoArg.Marshal(b, m, deterministic)
}
func (m *QueryRoleInfoArg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRoleInfoArg.Merge(m, src)
}
func (m *QueryRoleInfoArg) XXX_Size() int {
	return xxx_messageInfo_QueryRoleInfoArg.Size(m)
}
func (m *QueryRoleInfoArg) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRoleInfoArg.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRoleInfoArg proto.InternalMessageInfo

func (m *QueryRoleInfoArg) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *QueryRoleInfoArg) GetGameID() uint64 {
	if m != nil && m.GameID != nil {
		return *m.GameID
	}
	return 0
}

func (m *QueryRoleInfoArg) GetAttrIDs() []int32 {
	if m != nil {
		return m.AttrIDs
	}
	return nil
}

func (m *QueryRoleInfoArg) GetQueryBase() bool {
	if m != nil && m.QueryBase != nil {
		return *m.QueryBase
	}
	return false
}

func (m *QueryRoleInfoArg) GetCharacterIDs() []int32 {
	if m != nil {
		return m.CharacterIDs
	}
	return nil
}

func (m *QueryRoleInfoArg) GetWeaponIDs() []uint32 {
	if m != nil {
		return m.WeaponIDs
	}
	return nil
}

func (m *QueryRoleInfoArg) GetEquipIDs() []uint32 {
	if m != nil {
		return m.EquipIDs
	}
	return nil
}

type QueryRoleInfoToC struct {
	QueryResults         []*QueryRoleInfoResult `protobuf:"bytes,1,rep,name=queryResults" json:"queryResults,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *QueryRoleInfoToC) Reset()         { *m = QueryRoleInfoToC{} }
func (m *QueryRoleInfoToC) String() string { return proto.CompactTextString(m) }
func (*QueryRoleInfoToC) ProtoMessage()    {}
func (*QueryRoleInfoToC) Descriptor() ([]byte, []int) {
	return fileDescriptor_52b2e20e5cd59395, []int{2}
}

func (m *QueryRoleInfoToC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRoleInfoToC.Unmarshal(m, b)
}
func (m *QueryRoleInfoToC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRoleInfoToC.Marshal(b, m, deterministic)
}
func (m *QueryRoleInfoToC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRoleInfoToC.Merge(m, src)
}
func (m *QueryRoleInfoToC) XXX_Size() int {
	return xxx_messageInfo_QueryRoleInfoToC.Size(m)
}
func (m *QueryRoleInfoToC) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRoleInfoToC.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRoleInfoToC proto.InternalMessageInfo

func (m *QueryRoleInfoToC) GetQueryResults() []*QueryRoleInfoResult {
	if m != nil {
		return m.QueryResults
	}
	return nil
}

type QueryRoleInfoResult struct {
	UserID               *string      `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	GameID               *uint64      `protobuf:"varint,2,opt,name=gameID" json:"gameID,omitempty"`
	Attrs                []*Attr      `protobuf:"bytes,3,rep,name=attrs" json:"attrs,omitempty"`
	BaseResp             *BaseSyncToC `protobuf:"bytes,4,opt,name=baseResp" json:"baseResp,omitempty"`
	Characters           []*Character `protobuf:"bytes,5,rep,name=characters" json:"characters,omitempty"`
	Equips               []*Equip     `protobuf:"bytes,6,rep,name=equips" json:"equips,omitempty"`
	Weapons              []*Weapon    `protobuf:"bytes,7,rep,name=weapons" json:"weapons,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *QueryRoleInfoResult) Reset()         { *m = QueryRoleInfoResult{} }
func (m *QueryRoleInfoResult) String() string { return proto.CompactTextString(m) }
func (*QueryRoleInfoResult) ProtoMessage()    {}
func (*QueryRoleInfoResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_52b2e20e5cd59395, []int{3}
}

func (m *QueryRoleInfoResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRoleInfoResult.Unmarshal(m, b)
}
func (m *QueryRoleInfoResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRoleInfoResult.Marshal(b, m, deterministic)
}
func (m *QueryRoleInfoResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRoleInfoResult.Merge(m, src)
}
func (m *QueryRoleInfoResult) XXX_Size() int {
	return xxx_messageInfo_QueryRoleInfoResult.Size(m)
}
func (m *QueryRoleInfoResult) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRoleInfoResult.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRoleInfoResult proto.InternalMessageInfo

func (m *QueryRoleInfoResult) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *QueryRoleInfoResult) GetGameID() uint64 {
	if m != nil && m.GameID != nil {
		return *m.GameID
	}
	return 0
}

func (m *QueryRoleInfoResult) GetAttrs() []*Attr {
	if m != nil {
		return m.Attrs
	}
	return nil
}

func (m *QueryRoleInfoResult) GetBaseResp() *BaseSyncToC {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

func (m *QueryRoleInfoResult) GetCharacters() []*Character {
	if m != nil {
		return m.Characters
	}
	return nil
}

func (m *QueryRoleInfoResult) GetEquips() []*Equip {
	if m != nil {
		return m.Equips
	}
	return nil
}

func (m *QueryRoleInfoResult) GetWeapons() []*Weapon {
	if m != nil {
		return m.Weapons
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryRoleInfoToS)(nil), "message.queryRoleInfo_toS")
	proto.RegisterType((*QueryRoleInfoArg)(nil), "message.queryRoleInfoArg")
	proto.RegisterType((*QueryRoleInfoToC)(nil), "message.queryRoleInfo_toC")
	proto.RegisterType((*QueryRoleInfoResult)(nil), "message.queryRoleInfoResult")
}

func init() {
	proto.RegisterFile("cs/proto/message/queryRoleInfo.proto", fileDescriptor_52b2e20e5cd59395)
}

var fileDescriptor_52b2e20e5cd59395 = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x4f, 0x8f, 0x94, 0x30,
	0x18, 0xc6, 0xc3, 0xb2, 0x33, 0xcc, 0xbe, 0xec, 0xfa, 0xa7, 0x46, 0x83, 0x93, 0x35, 0x56, 0x34,
	0x06, 0x2f, 0x43, 0xe4, 0xe2, 0xd5, 0x59, 0xe7, 0x42, 0xe2, 0xa9, 0x1b, 0x2f, 0x5e, 0x4c, 0x25,
	0x95, 0x25, 0x01, 0xca, 0xb6, 0x25, 0x66, 0xbf, 0x8f, 0x1f, 0xca, 0x8f, 0x63, 0xda, 0x42, 0x19,
	0x64, 0x2f, 0x7b, 0xec, 0xf3, 0xfc, 0xde, 0x42, 0x7f, 0x79, 0xe1, 0x5d, 0x21, 0xd3, 0x4e, 0x70,
	0xc5, 0xd3, 0x86, 0x49, 0x49, 0x4b, 0x96, 0xde, 0xf6, 0x4c, 0xdc, 0x11, 0x5e, 0xb3, 0xbc, 0xfd,
	0xc5, 0x77, 0xa6, 0x43, 0xc1, 0x50, 0x6e, 0x5f, 0x2f, 0xf0, 0x9f, 0x54, 0xb2, 0xeb, 0xbb, 0xb6,
	0xb0, 0xe4, 0xf6, 0xd5, 0x02, 0x28, 0x78, 0xd3, 0xf0, 0x76, 0xa8, 0x97, 0x9f, 0x2b, 0x6e, 0xa8,
	0xa0, 0x85, 0x62, 0xe2, 0xe8, 0x12, 0xbc, 0xa0, 0xd8, 0x6d, 0x5f, 0x75, 0x47, 0xc4, 0x9b, 0x05,
	0xf1, 0x9b, 0xd1, 0x8e, 0xb7, 0x13, 0x12, 0x7f, 0x85, 0xa7, 0xb3, 0xa7, 0xfc, 0x50, 0xfc, 0x1a,
	0x7d, 0x82, 0x33, 0x13, 0xee, 0x45, 0x29, 0x23, 0x0f, 0xfb, 0x49, 0x98, 0xbd, 0xdc, 0x0d, 0x57,
	0xec, 0x66, 0xf8, 0x5e, 0x94, 0x64, 0x62, 0xe3, 0xbf, 0x1e, 0x3c, 0xf9, 0xbf, 0x47, 0x2f, 0x60,
	0xdd, 0x4b, 0x26, 0xf2, 0x43, 0xe4, 0x61, 0x2f, 0x39, 0x23, 0xc3, 0x49, 0xe7, 0x25, 0x6d, 0x58,
	0x7e, 0x88, 0x4e, 0xb0, 0x97, 0x9c, 0x92, 0xe1, 0x84, 0x22, 0x08, 0xa8, 0x52, 0x22, 0x3f, 0xc8,
	0xc8, 0xc7, 0x7e, 0xb2, 0x22, 0xe3, 0x11, 0x5d, 0x0e, 0xff, 0x75, 0x45, 0x25, 0x8b, 0x4e, 0xb1,
	0x97, 0x6c, 0xc8, 0x14, 0xa0, 0x18, 0xce, 0x9d, 0x26, 0x3d, 0xbc, 0x32, 0xc3, 0xb3, 0x4c, 0xdf,
	0x60, 0x15, 0x68, 0x60, 0x8d, 0xfd, 0xe4, 0x82, 0x4c, 0x01, 0xda, 0xc2, 0xc6, 0x28, 0xd4, 0x65,
	0x60, 0x4a, 0x77, 0x8e, 0xbf, 0x2d, 0x45, 0x7d, 0x41, 0x9f, 0xe1, 0xdc, 0x86, 0x4c, 0xf6, 0xb5,
	0x1a, 0x5d, 0x5d, 0xde, 0xef, 0xca, 0x42, 0x64, 0x36, 0x11, 0xff, 0x39, 0x81, 0x67, 0xf7, 0x50,
	0x0f, 0x96, 0xf6, 0x16, 0x56, 0xda, 0x92, 0x55, 0x16, 0x66, 0x17, 0xee, 0x17, 0xf6, 0x4a, 0x09,
	0x62, 0x3b, 0xf4, 0x11, 0x36, 0x7a, 0x11, 0x09, 0x93, 0x9d, 0xd1, 0x17, 0x66, 0xcf, 0x1d, 0x37,
	0x6e, 0xa8, 0x7e, 0x17, 0x71, 0x18, 0xca, 0x00, 0x9c, 0x40, 0xab, 0x34, 0xcc, 0x90, 0x1b, 0x72,
	0x15, 0x39, 0xa2, 0xd0, 0x7b, 0x58, 0x1b, 0x6d, 0xd6, 0x70, 0x98, 0x3d, 0x72, 0xbc, 0x89, 0xc9,
	0xd0, 0xa2, 0x0f, 0x10, 0x58, 0xf7, 0xd6, 0x76, 0x98, 0x3d, 0x76, 0xa0, 0xcd, 0xc9, 0xd8, 0x5f,
	0xc5, 0xdf, 0x71, 0xd5, 0x56, 0xaa, 0xa2, 0xb5, 0xba, 0x11, 0x8c, 0xd9, 0xad, 0x2e, 0x78, 0x9d,
	0x16, 0x72, 0xdc, 0xed, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe0, 0xd9, 0x90, 0x6a, 0xa5, 0x03,
	0x00, 0x00,
}
