// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs/proto/message/reputationRefresh.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReputationRefreshToS struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReputationRefreshToS) Reset()         { *m = ReputationRefreshToS{} }
func (m *ReputationRefreshToS) String() string { return proto.CompactTextString(m) }
func (*ReputationRefreshToS) ProtoMessage()    {}
func (*ReputationRefreshToS) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5205a6969b41a3, []int{0}
}

func (m *ReputationRefreshToS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReputationRefreshToS.Unmarshal(m, b)
}
func (m *ReputationRefreshToS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReputationRefreshToS.Marshal(b, m, deterministic)
}
func (m *ReputationRefreshToS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReputationRefreshToS.Merge(m, src)
}
func (m *ReputationRefreshToS) XXX_Size() int {
	return xxx_messageInfo_ReputationRefreshToS.Size(m)
}
func (m *ReputationRefreshToS) XXX_DiscardUnknown() {
	xxx_messageInfo_ReputationRefreshToS.DiscardUnknown(m)
}

var xxx_messageInfo_ReputationRefreshToS proto.InternalMessageInfo

func (m *ReputationRefreshToS) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type ReputationRefreshToC struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReputationRefreshToC) Reset()         { *m = ReputationRefreshToC{} }
func (m *ReputationRefreshToC) String() string { return proto.CompactTextString(m) }
func (*ReputationRefreshToC) ProtoMessage()    {}
func (*ReputationRefreshToC) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5205a6969b41a3, []int{1}
}

func (m *ReputationRefreshToC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReputationRefreshToC.Unmarshal(m, b)
}
func (m *ReputationRefreshToC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReputationRefreshToC.Marshal(b, m, deterministic)
}
func (m *ReputationRefreshToC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReputationRefreshToC.Merge(m, src)
}
func (m *ReputationRefreshToC) XXX_Size() int {
	return xxx_messageInfo_ReputationRefreshToC.Size(m)
}
func (m *ReputationRefreshToC) XXX_DiscardUnknown() {
	xxx_messageInfo_ReputationRefreshToC.DiscardUnknown(m)
}

var xxx_messageInfo_ReputationRefreshToC proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ReputationRefreshToS)(nil), "message.reputationRefresh_toS")
	proto.RegisterType((*ReputationRefreshToC)(nil), "message.reputationRefresh_toC")
}

func init() {
	proto.RegisterFile("cs/proto/message/reputationRefresh.proto", fileDescriptor_3b5205a6969b41a3)
}

var fileDescriptor_3b5205a6969b41a3 = []byte{
	// 125 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x48, 0x2e, 0xd6, 0x2f,
	0x28, 0xca, 0x2f, 0xc9, 0xd7, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2f, 0x4a, 0x2d,
	0x28, 0x2d, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0x0b, 0x4a, 0x4d, 0x2b, 0x4a, 0x2d, 0xce, 0xd0, 0x03,
	0xcb, 0x0b, 0xb1, 0x43, 0x15, 0x28, 0xa9, 0x73, 0x89, 0x62, 0xa8, 0x89, 0x2f, 0xc9, 0x0f, 0x16,
	0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd2, 0x60, 0x0d, 0x62, 0xca, 0x4c, 0x51,
	0x12, 0xc7, 0xae, 0xd0, 0xd9, 0x49, 0x29, 0x4a, 0x21, 0x33, 0x2f, 0xb3, 0x24, 0x33, 0x31, 0xa7,
	0x24, 0xa3, 0x28, 0x35, 0x15, 0xe2, 0x80, 0xe4, 0xfc, 0x1c, 0xfd, 0xe4, 0x62, 0x98, 0x33, 0x00,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x73, 0x33, 0x74, 0xc0, 0x99, 0x00, 0x00, 0x00,
}
