// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs/proto/message/rewardQuestSync.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RewardQuestSyncToS struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RewardQuestSyncToS) Reset()         { *m = RewardQuestSyncToS{} }
func (m *RewardQuestSyncToS) String() string { return proto.CompactTextString(m) }
func (*RewardQuestSyncToS) ProtoMessage()    {}
func (*RewardQuestSyncToS) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d2af3604d8696e3, []int{0}
}

func (m *RewardQuestSyncToS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RewardQuestSyncToS.Unmarshal(m, b)
}
func (m *RewardQuestSyncToS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RewardQuestSyncToS.Marshal(b, m, deterministic)
}
func (m *RewardQuestSyncToS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RewardQuestSyncToS.Merge(m, src)
}
func (m *RewardQuestSyncToS) XXX_Size() int {
	return xxx_messageInfo_RewardQuestSyncToS.Size(m)
}
func (m *RewardQuestSyncToS) XXX_DiscardUnknown() {
	xxx_messageInfo_RewardQuestSyncToS.DiscardUnknown(m)
}

var xxx_messageInfo_RewardQuestSyncToS proto.InternalMessageInfo

type RewardQuestSyncToC struct {
	IsAll                *bool          `protobuf:"varint,1,req,name=isAll" json:"isAll,omitempty"`
	Quests               []*RewardQuest `protobuf:"bytes,2,rep,name=Quests" json:"Quests,omitempty"`
	RefreshTimes         *int32         `protobuf:"varint,3,req,name=refreshTimes" json:"refreshTimes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RewardQuestSyncToC) Reset()         { *m = RewardQuestSyncToC{} }
func (m *RewardQuestSyncToC) String() string { return proto.CompactTextString(m) }
func (*RewardQuestSyncToC) ProtoMessage()    {}
func (*RewardQuestSyncToC) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d2af3604d8696e3, []int{1}
}

func (m *RewardQuestSyncToC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RewardQuestSyncToC.Unmarshal(m, b)
}
func (m *RewardQuestSyncToC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RewardQuestSyncToC.Marshal(b, m, deterministic)
}
func (m *RewardQuestSyncToC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RewardQuestSyncToC.Merge(m, src)
}
func (m *RewardQuestSyncToC) XXX_Size() int {
	return xxx_messageInfo_RewardQuestSyncToC.Size(m)
}
func (m *RewardQuestSyncToC) XXX_DiscardUnknown() {
	xxx_messageInfo_RewardQuestSyncToC.DiscardUnknown(m)
}

var xxx_messageInfo_RewardQuestSyncToC proto.InternalMessageInfo

func (m *RewardQuestSyncToC) GetIsAll() bool {
	if m != nil && m.IsAll != nil {
		return *m.IsAll
	}
	return false
}

func (m *RewardQuestSyncToC) GetQuests() []*RewardQuest {
	if m != nil {
		return m.Quests
	}
	return nil
}

func (m *RewardQuestSyncToC) GetRefreshTimes() int32 {
	if m != nil && m.RefreshTimes != nil {
		return *m.RefreshTimes
	}
	return 0
}

type RewardQuest struct {
	QuestID              *int32      `protobuf:"varint,1,req,name=questID" json:"questID,omitempty"`
	State                *QuestState `protobuf:"varint,2,opt,name=State,enum=message.QuestState" json:"State,omitempty"`
	Characters           []int32     `protobuf:"varint,3,rep,name=characters" json:"characters,omitempty"`
	AcceptTimestamp      *int64      `protobuf:"varint,4,opt,name=acceptTimestamp" json:"acceptTimestamp,omitempty"`
	IsRemoved            *bool       `protobuf:"varint,5,opt,name=isRemoved" json:"isRemoved,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RewardQuest) Reset()         { *m = RewardQuest{} }
func (m *RewardQuest) String() string { return proto.CompactTextString(m) }
func (*RewardQuest) ProtoMessage()    {}
func (*RewardQuest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d2af3604d8696e3, []int{2}
}

func (m *RewardQuest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RewardQuest.Unmarshal(m, b)
}
func (m *RewardQuest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RewardQuest.Marshal(b, m, deterministic)
}
func (m *RewardQuest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RewardQuest.Merge(m, src)
}
func (m *RewardQuest) XXX_Size() int {
	return xxx_messageInfo_RewardQuest.Size(m)
}
func (m *RewardQuest) XXX_DiscardUnknown() {
	xxx_messageInfo_RewardQuest.DiscardUnknown(m)
}

var xxx_messageInfo_RewardQuest proto.InternalMessageInfo

func (m *RewardQuest) GetQuestID() int32 {
	if m != nil && m.QuestID != nil {
		return *m.QuestID
	}
	return 0
}

func (m *RewardQuest) GetState() QuestState {
	if m != nil && m.State != nil {
		return *m.State
	}
	return QuestState_Running
}

func (m *RewardQuest) GetCharacters() []int32 {
	if m != nil {
		return m.Characters
	}
	return nil
}

func (m *RewardQuest) GetAcceptTimestamp() int64 {
	if m != nil && m.AcceptTimestamp != nil {
		return *m.AcceptTimestamp
	}
	return 0
}

func (m *RewardQuest) GetIsRemoved() bool {
	if m != nil && m.IsRemoved != nil {
		return *m.IsRemoved
	}
	return false
}

func init() {
	proto.RegisterType((*RewardQuestSyncToS)(nil), "message.rewardQuestSync_toS")
	proto.RegisterType((*RewardQuestSyncToC)(nil), "message.rewardQuestSync_toC")
	proto.RegisterType((*RewardQuest)(nil), "message.rewardQuest")
}

func init() {
	proto.RegisterFile("cs/proto/message/rewardQuestSync.proto", fileDescriptor_3d2af3604d8696e3)
}

var fileDescriptor_3d2af3604d8696e3 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0x69, 0x6b, 0xdc, 0x75, 0x56, 0x14, 0xb2, 0x2b, 0x04, 0x11, 0x09, 0x3d, 0x48, 0x04,
	0x69, 0x61, 0xbf, 0x81, 0x7f, 0x2e, 0x1e, 0x4d, 0x3d, 0x79, 0x91, 0x90, 0x1d, 0x6d, 0xa0, 0xdd,
	0xd6, 0x24, 0x2a, 0x1e, 0xfc, 0x62, 0x7e, 0x3a, 0xd9, 0xb4, 0xab, 0xdd, 0xd5, 0xe3, 0xfc, 0xde,
	0x9b, 0x79, 0x0f, 0x06, 0xce, 0xb4, 0xcb, 0x5b, 0xdb, 0xf8, 0x26, 0xaf, 0xd1, 0x39, 0xf5, 0x8c,
	0xb9, 0xc5, 0x77, 0x65, 0x17, 0x77, 0xaf, 0xe8, 0x7c, 0xf1, 0xb1, 0xd4, 0x59, 0x50, 0xe9, 0xa8,
	0x97, 0x8f, 0xf9, 0x9f, 0x85, 0x97, 0x4d, 0x6b, 0x7a, 0x04, 0xd3, 0xad, 0x1b, 0x8f, 0xbe, 0x29,
	0xd2, 0xcf, 0xff, 0xf0, 0x35, 0x9d, 0x01, 0x31, 0xee, 0xb2, 0xaa, 0x58, 0xc4, 0x63, 0x31, 0x96,
	0xdd, 0x40, 0x2f, 0x60, 0x37, 0xd8, 0x1c, 0x8b, 0x79, 0x22, 0x26, 0xf3, 0x59, 0xd6, 0xa7, 0x65,
	0x83, 0x1b, 0xb2, 0xf7, 0xd0, 0x14, 0xf6, 0x2d, 0x3e, 0x59, 0x74, 0xe5, 0xbd, 0xa9, 0xd1, 0xb1,
	0x84, 0xc7, 0x82, 0xc8, 0x0d, 0x96, 0x7e, 0x45, 0x30, 0x19, 0xec, 0x52, 0x06, 0xa3, 0x50, 0xfc,
	0xf6, 0x26, 0x24, 0x13, 0xb9, 0x1e, 0xe9, 0x39, 0x90, 0xc2, 0x2b, 0x8f, 0x2c, 0xe6, 0x91, 0x38,
	0x98, 0x4f, 0x7f, 0xa2, 0xbb, 0xe2, 0x2b, 0x49, 0x76, 0x0e, 0x7a, 0x0a, 0xa0, 0x4b, 0x65, 0x95,
	0xf6, 0x68, 0x57, 0xb1, 0x89, 0x20, 0x72, 0x40, 0xa8, 0x80, 0x43, 0xa5, 0x35, 0xb6, 0x3e, 0x74,
	0xf0, 0xaa, 0x6e, 0xd9, 0x0e, 0x8f, 0x44, 0x22, 0xb7, 0x31, 0x3d, 0x81, 0x3d, 0xe3, 0x24, 0xd6,
	0xcd, 0x1b, 0x2e, 0x18, 0xe1, 0x91, 0x18, 0xcb, 0x5f, 0x70, 0x95, 0x3e, 0x70, 0xb3, 0x34, 0xde,
	0xa8, 0xca, 0x97, 0x16, 0xb1, 0x7b, 0x80, 0x6e, 0xaa, 0x5c, 0xbb, 0xf5, 0x1b, 0xbe, 0x03, 0x00,
	0x00, 0xff, 0xff, 0xdb, 0x8e, 0xbd, 0x75, 0xca, 0x01, 0x00, 0x00,
}
