// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs/proto/message/scarsIngrainTeamPrefabSet.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ScarsIngrainTeamPrefabSetToS struct {
	BossID               *int32   `protobuf:"varint,1,opt,name=bossID" json:"bossID,omitempty"`
	CharacterList        []int32  `protobuf:"varint,2,rep,name=characterList" json:"characterList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScarsIngrainTeamPrefabSetToS) Reset()         { *m = ScarsIngrainTeamPrefabSetToS{} }
func (m *ScarsIngrainTeamPrefabSetToS) String() string { return proto.CompactTextString(m) }
func (*ScarsIngrainTeamPrefabSetToS) ProtoMessage()    {}
func (*ScarsIngrainTeamPrefabSetToS) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf5756746b64f8c4, []int{0}
}

func (m *ScarsIngrainTeamPrefabSetToS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScarsIngrainTeamPrefabSetToS.Unmarshal(m, b)
}
func (m *ScarsIngrainTeamPrefabSetToS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScarsIngrainTeamPrefabSetToS.Marshal(b, m, deterministic)
}
func (m *ScarsIngrainTeamPrefabSetToS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScarsIngrainTeamPrefabSetToS.Merge(m, src)
}
func (m *ScarsIngrainTeamPrefabSetToS) XXX_Size() int {
	return xxx_messageInfo_ScarsIngrainTeamPrefabSetToS.Size(m)
}
func (m *ScarsIngrainTeamPrefabSetToS) XXX_DiscardUnknown() {
	xxx_messageInfo_ScarsIngrainTeamPrefabSetToS.DiscardUnknown(m)
}

var xxx_messageInfo_ScarsIngrainTeamPrefabSetToS proto.InternalMessageInfo

func (m *ScarsIngrainTeamPrefabSetToS) GetBossID() int32 {
	if m != nil && m.BossID != nil {
		return *m.BossID
	}
	return 0
}

func (m *ScarsIngrainTeamPrefabSetToS) GetCharacterList() []int32 {
	if m != nil {
		return m.CharacterList
	}
	return nil
}

type ScarsIngrainTeamPrefabSetToC struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScarsIngrainTeamPrefabSetToC) Reset()         { *m = ScarsIngrainTeamPrefabSetToC{} }
func (m *ScarsIngrainTeamPrefabSetToC) String() string { return proto.CompactTextString(m) }
func (*ScarsIngrainTeamPrefabSetToC) ProtoMessage()    {}
func (*ScarsIngrainTeamPrefabSetToC) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf5756746b64f8c4, []int{1}
}

func (m *ScarsIngrainTeamPrefabSetToC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScarsIngrainTeamPrefabSetToC.Unmarshal(m, b)
}
func (m *ScarsIngrainTeamPrefabSetToC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScarsIngrainTeamPrefabSetToC.Marshal(b, m, deterministic)
}
func (m *ScarsIngrainTeamPrefabSetToC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScarsIngrainTeamPrefabSetToC.Merge(m, src)
}
func (m *ScarsIngrainTeamPrefabSetToC) XXX_Size() int {
	return xxx_messageInfo_ScarsIngrainTeamPrefabSetToC.Size(m)
}
func (m *ScarsIngrainTeamPrefabSetToC) XXX_DiscardUnknown() {
	xxx_messageInfo_ScarsIngrainTeamPrefabSetToC.DiscardUnknown(m)
}

var xxx_messageInfo_ScarsIngrainTeamPrefabSetToC proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ScarsIngrainTeamPrefabSetToS)(nil), "message.scarsIngrainTeamPrefabSet_toS")
	proto.RegisterType((*ScarsIngrainTeamPrefabSetToC)(nil), "message.scarsIngrainTeamPrefabSet_toC")
}

func init() {
	proto.RegisterFile("cs/proto/message/scarsIngrainTeamPrefabSet.proto", fileDescriptor_cf5756746b64f8c4)
}

var fileDescriptor_cf5756746b64f8c4 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x48, 0x2e, 0xd6, 0x2f,
	0x28, 0xca, 0x2f, 0xc9, 0xd7, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2f, 0x4e, 0x4e,
	0x2c, 0x2a, 0xf6, 0xcc, 0x4b, 0x2f, 0x4a, 0xcc, 0xcc, 0x0b, 0x49, 0x4d, 0xcc, 0x0d, 0x28, 0x4a,
	0x4d, 0x4b, 0x4c, 0x0a, 0x4e, 0x2d, 0xd1, 0x03, 0xab, 0x13, 0x62, 0x87, 0x2a, 0x54, 0x8a, 0xe5,
	0x92, 0xc5, 0xa9, 0x36, 0xbe, 0x24, 0x3f, 0x58, 0x48, 0x8c, 0x8b, 0x2d, 0x29, 0xbf, 0xb8, 0xd8,
	0xd3, 0x45, 0x82, 0x51, 0x81, 0x51, 0x83, 0x35, 0x08, 0xca, 0x13, 0x52, 0xe1, 0xe2, 0x4d, 0xce,
	0x48, 0x2c, 0x4a, 0x4c, 0x2e, 0x49, 0x2d, 0xf2, 0xc9, 0x2c, 0x2e, 0x91, 0x60, 0x52, 0x60, 0xd6,
	0x60, 0x0d, 0x42, 0x15, 0x54, 0x92, 0xc7, 0x6f, 0xbc, 0xb3, 0x93, 0x52, 0x94, 0x42, 0x66, 0x5e,
	0x66, 0x49, 0x66, 0x62, 0x4e, 0x49, 0x46, 0x51, 0x6a, 0x2a, 0xc4, 0x1b, 0xc9, 0xf9, 0x39, 0xfa,
	0xc9, 0xc5, 0x30, 0xcf, 0x00, 0x02, 0x00, 0x00, 0xff, 0xff, 0x66, 0x79, 0xe7, 0x0f, 0xdf, 0x00,
	0x00, 0x00,
}
