// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs/proto/message/scarsIngrainSaveScore.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ScarsIngrainSaveScoreToS struct {
	ScoreID              *int32   `protobuf:"varint,1,req,name=scoreID" json:"scoreID,omitempty"`
	IsSave               *bool    `protobuf:"varint,2,req,name=isSave" json:"isSave,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScarsIngrainSaveScoreToS) Reset()         { *m = ScarsIngrainSaveScoreToS{} }
func (m *ScarsIngrainSaveScoreToS) String() string { return proto.CompactTextString(m) }
func (*ScarsIngrainSaveScoreToS) ProtoMessage()    {}
func (*ScarsIngrainSaveScoreToS) Descriptor() ([]byte, []int) {
	return fileDescriptor_7df275104c1cac5d, []int{0}
}

func (m *ScarsIngrainSaveScoreToS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScarsIngrainSaveScoreToS.Unmarshal(m, b)
}
func (m *ScarsIngrainSaveScoreToS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScarsIngrainSaveScoreToS.Marshal(b, m, deterministic)
}
func (m *ScarsIngrainSaveScoreToS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScarsIngrainSaveScoreToS.Merge(m, src)
}
func (m *ScarsIngrainSaveScoreToS) XXX_Size() int {
	return xxx_messageInfo_ScarsIngrainSaveScoreToS.Size(m)
}
func (m *ScarsIngrainSaveScoreToS) XXX_DiscardUnknown() {
	xxx_messageInfo_ScarsIngrainSaveScoreToS.DiscardUnknown(m)
}

var xxx_messageInfo_ScarsIngrainSaveScoreToS proto.InternalMessageInfo

func (m *ScarsIngrainSaveScoreToS) GetScoreID() int32 {
	if m != nil && m.ScoreID != nil {
		return *m.ScoreID
	}
	return 0
}

func (m *ScarsIngrainSaveScoreToS) GetIsSave() bool {
	if m != nil && m.IsSave != nil {
		return *m.IsSave
	}
	return false
}

type ScarsIngrainSaveScoreToC struct {
	Score                *int32   `protobuf:"varint,1,opt,name=score" json:"score,omitempty"`
	DropAwards           []*Award `protobuf:"bytes,2,rep,name=dropAwards" json:"dropAwards,omitempty"`
	Rank                 *int32   `protobuf:"varint,3,opt,name=rank" json:"rank,omitempty"`
	Total                *int32   `protobuf:"varint,4,opt,name=total" json:"total,omitempty"`
	Percent              *int32   `protobuf:"varint,5,opt,name=percent" json:"percent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScarsIngrainSaveScoreToC) Reset()         { *m = ScarsIngrainSaveScoreToC{} }
func (m *ScarsIngrainSaveScoreToC) String() string { return proto.CompactTextString(m) }
func (*ScarsIngrainSaveScoreToC) ProtoMessage()    {}
func (*ScarsIngrainSaveScoreToC) Descriptor() ([]byte, []int) {
	return fileDescriptor_7df275104c1cac5d, []int{1}
}

func (m *ScarsIngrainSaveScoreToC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScarsIngrainSaveScoreToC.Unmarshal(m, b)
}
func (m *ScarsIngrainSaveScoreToC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScarsIngrainSaveScoreToC.Marshal(b, m, deterministic)
}
func (m *ScarsIngrainSaveScoreToC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScarsIngrainSaveScoreToC.Merge(m, src)
}
func (m *ScarsIngrainSaveScoreToC) XXX_Size() int {
	return xxx_messageInfo_ScarsIngrainSaveScoreToC.Size(m)
}
func (m *ScarsIngrainSaveScoreToC) XXX_DiscardUnknown() {
	xxx_messageInfo_ScarsIngrainSaveScoreToC.DiscardUnknown(m)
}

var xxx_messageInfo_ScarsIngrainSaveScoreToC proto.InternalMessageInfo

func (m *ScarsIngrainSaveScoreToC) GetScore() int32 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func (m *ScarsIngrainSaveScoreToC) GetDropAwards() []*Award {
	if m != nil {
		return m.DropAwards
	}
	return nil
}

func (m *ScarsIngrainSaveScoreToC) GetRank() int32 {
	if m != nil && m.Rank != nil {
		return *m.Rank
	}
	return 0
}

func (m *ScarsIngrainSaveScoreToC) GetTotal() int32 {
	if m != nil && m.Total != nil {
		return *m.Total
	}
	return 0
}

func (m *ScarsIngrainSaveScoreToC) GetPercent() int32 {
	if m != nil && m.Percent != nil {
		return *m.Percent
	}
	return 0
}

func init() {
	proto.RegisterType((*ScarsIngrainSaveScoreToS)(nil), "message.scarsIngrainSaveScore_toS")
	proto.RegisterType((*ScarsIngrainSaveScoreToC)(nil), "message.scarsIngrainSaveScore_toC")
}

func init() {
	proto.RegisterFile("cs/proto/message/scarsIngrainSaveScore.proto", fileDescriptor_7df275104c1cac5d)
}

var fileDescriptor_7df275104c1cac5d = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xcd, 0x4a, 0xc4, 0x30,
	0x10, 0x80, 0x69, 0x77, 0xeb, 0x4a, 0x04, 0x0f, 0x41, 0x24, 0x0a, 0x42, 0xe8, 0xa9, 0x07, 0x69,
	0xc1, 0x37, 0xf0, 0xe7, 0xb2, 0x07, 0x2f, 0xed, 0xcd, 0x8b, 0x0c, 0xd9, 0x61, 0x0d, 0xb6, 0x99,
	0x32, 0x13, 0xf4, 0x89, 0x7c, 0x4f, 0x69, 0xda, 0x82, 0xa0, 0xde, 0xf2, 0x0d, 0x5f, 0x3e, 0x86,
	0x51, 0xb7, 0x4e, 0x9a, 0x91, 0x29, 0x52, 0x33, 0xa0, 0x08, 0x1c, 0xb1, 0x11, 0x07, 0x2c, 0xfb,
	0x70, 0x64, 0xf0, 0xa1, 0x83, 0x0f, 0xec, 0x1c, 0x31, 0xd6, 0xc9, 0xd1, 0xbb, 0x45, 0xba, 0xbe,
	0xf9, 0xf5, 0xcd, 0xd1, 0x30, 0x50, 0x98, 0xbd, 0xf2, 0x59, 0x5d, 0xfd, 0x99, 0x79, 0x8d, 0xd4,
	0x69, 0xa3, 0x76, 0x32, 0xc1, 0xfe, 0xc9, 0x64, 0x36, 0xaf, 0x8a, 0x76, 0x45, 0x7d, 0xa9, 0x4e,
	0xbc, 0x4c, 0xb2, 0xc9, 0x6d, 0x5e, 0x9d, 0xb6, 0x0b, 0x95, 0x5f, 0xd9, 0xff, 0xbd, 0x47, 0x7d,
	0xa1, 0x8a, 0x14, 0x30, 0x99, 0xcd, 0xaa, 0xa2, 0x9d, 0x41, 0xd7, 0x4a, 0x1d, 0x98, 0xc6, 0xfb,
	0x4f, 0xe0, 0x83, 0x98, 0xdc, 0x6e, 0xaa, 0xb3, 0xbb, 0xf3, 0x7a, 0xd9, 0xb6, 0x4e, 0xe3, 0xf6,
	0x87, 0xa1, 0xb5, 0xda, 0x32, 0x84, 0x77, 0xb3, 0x49, 0x91, 0xf4, 0x9e, 0xca, 0x91, 0x22, 0xf4,
	0x66, 0x3b, 0x97, 0x13, 0x4c, 0xfb, 0x8f, 0xc8, 0x0e, 0x43, 0x34, 0x45, 0x9a, 0xaf, 0xf8, 0x50,
	0xbe, 0x58, 0x1f, 0x7c, 0xf4, 0xd0, 0xc7, 0x37, 0x46, 0x9c, 0x2f, 0xe4, 0xa8, 0x6f, 0x9c, 0xac,
	0x77, 0xfa, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x34, 0x58, 0xca, 0x82, 0x71, 0x01, 0x00, 0x00,
}
