// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs/proto/message/scarsIngrainSync.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ScarsIngrainSyncToS struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScarsIngrainSyncToS) Reset()         { *m = ScarsIngrainSyncToS{} }
func (m *ScarsIngrainSyncToS) String() string { return proto.CompactTextString(m) }
func (*ScarsIngrainSyncToS) ProtoMessage()    {}
func (*ScarsIngrainSyncToS) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d0a64d81223676, []int{0}
}

func (m *ScarsIngrainSyncToS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScarsIngrainSyncToS.Unmarshal(m, b)
}
func (m *ScarsIngrainSyncToS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScarsIngrainSyncToS.Marshal(b, m, deterministic)
}
func (m *ScarsIngrainSyncToS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScarsIngrainSyncToS.Merge(m, src)
}
func (m *ScarsIngrainSyncToS) XXX_Size() int {
	return xxx_messageInfo_ScarsIngrainSyncToS.Size(m)
}
func (m *ScarsIngrainSyncToS) XXX_DiscardUnknown() {
	xxx_messageInfo_ScarsIngrainSyncToS.DiscardUnknown(m)
}

var xxx_messageInfo_ScarsIngrainSyncToS proto.InternalMessageInfo

type ScarsIngrainSyncToC struct {
	ScarsIngrainGroup    []*ScarsIngrain     `protobuf:"bytes,1,rep,name=scarsIngrainGroup" json:"scarsIngrainGroup,omitempty"`
	CurrentID            *int32              `protobuf:"varint,2,req,name=currentID" json:"currentID,omitempty"`
	TotalScore           *int32              `protobuf:"varint,3,opt,name=totalScore" json:"totalScore,omitempty"`
	BossGroup            []*ScarsIngrainBoss `protobuf:"bytes,4,rep,name=bossGroup" json:"bossGroup,omitempty"`
	CurrentRankId        *int32              `protobuf:"varint,5,opt,name=currentRankId" json:"currentRankId,omitempty"`
	ScoreRewardGet       []int32             `protobuf:"varint,6,rep,name=scoreRewardGet" json:"scoreRewardGet,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ScarsIngrainSyncToC) Reset()         { *m = ScarsIngrainSyncToC{} }
func (m *ScarsIngrainSyncToC) String() string { return proto.CompactTextString(m) }
func (*ScarsIngrainSyncToC) ProtoMessage()    {}
func (*ScarsIngrainSyncToC) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d0a64d81223676, []int{1}
}

func (m *ScarsIngrainSyncToC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScarsIngrainSyncToC.Unmarshal(m, b)
}
func (m *ScarsIngrainSyncToC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScarsIngrainSyncToC.Marshal(b, m, deterministic)
}
func (m *ScarsIngrainSyncToC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScarsIngrainSyncToC.Merge(m, src)
}
func (m *ScarsIngrainSyncToC) XXX_Size() int {
	return xxx_messageInfo_ScarsIngrainSyncToC.Size(m)
}
func (m *ScarsIngrainSyncToC) XXX_DiscardUnknown() {
	xxx_messageInfo_ScarsIngrainSyncToC.DiscardUnknown(m)
}

var xxx_messageInfo_ScarsIngrainSyncToC proto.InternalMessageInfo

func (m *ScarsIngrainSyncToC) GetScarsIngrainGroup() []*ScarsIngrain {
	if m != nil {
		return m.ScarsIngrainGroup
	}
	return nil
}

func (m *ScarsIngrainSyncToC) GetCurrentID() int32 {
	if m != nil && m.CurrentID != nil {
		return *m.CurrentID
	}
	return 0
}

func (m *ScarsIngrainSyncToC) GetTotalScore() int32 {
	if m != nil && m.TotalScore != nil {
		return *m.TotalScore
	}
	return 0
}

func (m *ScarsIngrainSyncToC) GetBossGroup() []*ScarsIngrainBoss {
	if m != nil {
		return m.BossGroup
	}
	return nil
}

func (m *ScarsIngrainSyncToC) GetCurrentRankId() int32 {
	if m != nil && m.CurrentRankId != nil {
		return *m.CurrentRankId
	}
	return 0
}

func (m *ScarsIngrainSyncToC) GetScoreRewardGet() []int32 {
	if m != nil {
		return m.ScoreRewardGet
	}
	return nil
}

type ScarsIngrain struct {
	ScarsIngrainID       *int32   `protobuf:"varint,1,req,name=scarsIngrainID" json:"scarsIngrainID,omitempty"`
	RankID               *int32   `protobuf:"varint,2,req,name=rankID" json:"rankID,omitempty"`
	BossIDs              []int32  `protobuf:"varint,3,rep,name=bossIDs" json:"bossIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScarsIngrain) Reset()         { *m = ScarsIngrain{} }
func (m *ScarsIngrain) String() string { return proto.CompactTextString(m) }
func (*ScarsIngrain) ProtoMessage()    {}
func (*ScarsIngrain) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d0a64d81223676, []int{2}
}

func (m *ScarsIngrain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScarsIngrain.Unmarshal(m, b)
}
func (m *ScarsIngrain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScarsIngrain.Marshal(b, m, deterministic)
}
func (m *ScarsIngrain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScarsIngrain.Merge(m, src)
}
func (m *ScarsIngrain) XXX_Size() int {
	return xxx_messageInfo_ScarsIngrain.Size(m)
}
func (m *ScarsIngrain) XXX_DiscardUnknown() {
	xxx_messageInfo_ScarsIngrain.DiscardUnknown(m)
}

var xxx_messageInfo_ScarsIngrain proto.InternalMessageInfo

func (m *ScarsIngrain) GetScarsIngrainID() int32 {
	if m != nil && m.ScarsIngrainID != nil {
		return *m.ScarsIngrainID
	}
	return 0
}

func (m *ScarsIngrain) GetRankID() int32 {
	if m != nil && m.RankID != nil {
		return *m.RankID
	}
	return 0
}

func (m *ScarsIngrain) GetBossIDs() []int32 {
	if m != nil {
		return m.BossIDs
	}
	return nil
}

type ScarsIngrainBoss struct {
	BossID               *int32   `protobuf:"varint,1,req,name=bossID" json:"bossID,omitempty"`
	ChallengeID          *int32   `protobuf:"varint,2,req,name=challengeID" json:"challengeID,omitempty"`
	DifficultScore       []int32  `protobuf:"varint,3,rep,name=difficultScore" json:"difficultScore,omitempty"`
	DefendCharacterList  []int32  `protobuf:"varint,4,rep,name=defendCharacterList" json:"defendCharacterList,omitempty"`
	PrefabCharacterList  []int32  `protobuf:"varint,5,rep,name=prefabCharacterList" json:"prefabCharacterList,omitempty"`
	Opened               *bool    `protobuf:"varint,6,opt,name=opened" json:"opened,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScarsIngrainBoss) Reset()         { *m = ScarsIngrainBoss{} }
func (m *ScarsIngrainBoss) String() string { return proto.CompactTextString(m) }
func (*ScarsIngrainBoss) ProtoMessage()    {}
func (*ScarsIngrainBoss) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d0a64d81223676, []int{3}
}

func (m *ScarsIngrainBoss) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScarsIngrainBoss.Unmarshal(m, b)
}
func (m *ScarsIngrainBoss) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScarsIngrainBoss.Marshal(b, m, deterministic)
}
func (m *ScarsIngrainBoss) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScarsIngrainBoss.Merge(m, src)
}
func (m *ScarsIngrainBoss) XXX_Size() int {
	return xxx_messageInfo_ScarsIngrainBoss.Size(m)
}
func (m *ScarsIngrainBoss) XXX_DiscardUnknown() {
	xxx_messageInfo_ScarsIngrainBoss.DiscardUnknown(m)
}

var xxx_messageInfo_ScarsIngrainBoss proto.InternalMessageInfo

func (m *ScarsIngrainBoss) GetBossID() int32 {
	if m != nil && m.BossID != nil {
		return *m.BossID
	}
	return 0
}

func (m *ScarsIngrainBoss) GetChallengeID() int32 {
	if m != nil && m.ChallengeID != nil {
		return *m.ChallengeID
	}
	return 0
}

func (m *ScarsIngrainBoss) GetDifficultScore() []int32 {
	if m != nil {
		return m.DifficultScore
	}
	return nil
}

func (m *ScarsIngrainBoss) GetDefendCharacterList() []int32 {
	if m != nil {
		return m.DefendCharacterList
	}
	return nil
}

func (m *ScarsIngrainBoss) GetPrefabCharacterList() []int32 {
	if m != nil {
		return m.PrefabCharacterList
	}
	return nil
}

func (m *ScarsIngrainBoss) GetOpened() bool {
	if m != nil && m.Opened != nil {
		return *m.Opened
	}
	return false
}

func init() {
	proto.RegisterType((*ScarsIngrainSyncToS)(nil), "message.scarsIngrainSync_toS")
	proto.RegisterType((*ScarsIngrainSyncToC)(nil), "message.scarsIngrainSync_toC")
	proto.RegisterType((*ScarsIngrain)(nil), "message.scarsIngrain")
	proto.RegisterType((*ScarsIngrainBoss)(nil), "message.scarsIngrainBoss")
}

func init() {
	proto.RegisterFile("cs/proto/message/scarsIngrainSync.proto", fileDescriptor_d4d0a64d81223676)
}

var fileDescriptor_d4d0a64d81223676 = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x5f, 0x4b, 0xf3, 0x30,
	0x18, 0xc5, 0xe9, 0xfa, 0x76, 0x7b, 0x97, 0xa9, 0x68, 0xd4, 0x11, 0x41, 0xa4, 0x14, 0xd1, 0x5e,
	0xad, 0xe2, 0x8d, 0xf7, 0xdb, 0x60, 0x14, 0xbc, 0xca, 0xee, 0xbc, 0x91, 0x2c, 0x7d, 0xba, 0x16,
	0x6b, 0x52, 0x92, 0x0c, 0xf1, 0xdb, 0xf8, 0x11, 0xfd, 0x08, 0xd2, 0x7f, 0xae, 0xab, 0xbd, 0x3c,
	0xe7, 0x3c, 0x4f, 0x7e, 0x39, 0x21, 0xe8, 0x9e, 0xeb, 0x20, 0x57, 0xd2, 0xc8, 0xe0, 0x1d, 0xb4,
	0x66, 0x5b, 0x08, 0x34, 0x67, 0x4a, 0x87, 0x62, 0xab, 0x58, 0x2a, 0xd6, 0x9f, 0x82, 0xcf, 0xca,
	0x18, 0x8f, 0xea, 0xdc, 0x9b, 0xa2, 0x8b, 0xee, 0xc8, 0xab, 0x91, 0x6b, 0xef, 0x6b, 0xd0, 0x1b,
	0x2c, 0xf0, 0x02, 0x9d, 0xb5, 0xfd, 0x95, 0x92, 0xbb, 0x9c, 0x58, 0xae, 0xed, 0x4f, 0x1e, 0x2f,
	0x67, 0xf5, 0xa9, 0xb3, 0xf6, 0x04, 0xfd, 0x3b, 0x8f, 0xaf, 0xd1, 0x98, 0xef, 0x94, 0x02, 0x61,
	0xc2, 0x25, 0x19, 0xb8, 0x03, 0xdf, 0xa1, 0x7b, 0x03, 0xdf, 0x20, 0x64, 0xa4, 0x61, 0xd9, 0x9a,
	0x4b, 0x05, 0xc4, 0x76, 0x2d, 0xdf, 0xa1, 0x2d, 0x07, 0x3f, 0xa1, 0xf1, 0x46, 0x6a, 0x5d, 0xa1,
	0xff, 0x95, 0xe8, 0xab, 0x5e, 0xf4, 0x5c, 0x6a, 0x4d, 0xf7, 0xb3, 0xf8, 0x16, 0x1d, 0xd7, 0x14,
	0xca, 0xc4, 0x5b, 0x18, 0x11, 0xa7, 0x3c, 0xfb, 0xd0, 0xc4, 0x77, 0xe8, 0x44, 0x17, 0x1c, 0x0a,
	0x1f, 0x4c, 0x45, 0x2b, 0x30, 0x64, 0xe8, 0xda, 0xbe, 0x43, 0x3b, 0xae, 0x97, 0xa0, 0xa3, 0x36,
	0xac, 0xda, 0xdb, 0xeb, 0x70, 0x49, 0xac, 0xb2, 0x59, 0xc7, 0xc5, 0x53, 0x34, 0x54, 0x05, 0xa9,
	0x69, 0x5e, 0x2b, 0x4c, 0xd0, 0xa8, 0xb8, 0x6a, 0xb8, 0xd4, 0xc4, 0x2e, 0x81, 0x8d, 0xf4, 0xbe,
	0x2d, 0x74, 0xda, 0xed, 0x55, 0x1c, 0x53, 0xe5, 0x35, 0xa6, 0x56, 0xd8, 0x45, 0x13, 0x9e, 0xb0,
	0x2c, 0x03, 0xb1, 0x85, 0x5f, 0x46, 0xdb, 0x2a, 0x2e, 0x1a, 0xa5, 0x71, 0x9c, 0xf2, 0x5d, 0x66,
	0x9a, 0x37, 0x2e, 0x0b, 0x1e, 0xba, 0xf8, 0x01, 0x9d, 0x47, 0x10, 0x83, 0x88, 0x16, 0x09, 0x53,
	0x8c, 0x1b, 0x50, 0xcf, 0xa9, 0x36, 0xe5, 0x8b, 0x3b, 0xb4, 0x2f, 0x2a, 0x36, 0x72, 0x05, 0x31,
	0xdb, 0x1c, 0x6e, 0x38, 0xd5, 0x46, 0x4f, 0x54, 0xb4, 0x90, 0x39, 0x08, 0x88, 0xc8, 0xd0, 0xb5,
	0xfc, 0xff, 0xb4, 0x56, 0x73, 0xef, 0xc5, 0x4d, 0x45, 0x6a, 0x52, 0x96, 0x99, 0x44, 0x01, 0x54,
	0xbf, 0x9a, 0xcb, 0x2c, 0xe0, 0xba, 0xf9, 0xdb, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x67, 0xeb,
	0x56, 0x7a, 0xee, 0x02, 0x00, 0x00,
}
