// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs/proto/message/serverList.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserType int32

const (
	UserType_NONE       UserType = 0
	UserType_LAST_LOGIN UserType = 1
)

var UserType_name = map[int32]string{
	0: "NONE",
	1: "LAST_LOGIN",
}

var UserType_value = map[string]int32{
	"NONE":       0,
	"LAST_LOGIN": 1,
}

func (x UserType) Enum() *UserType {
	p := new(UserType)
	*p = x
	return p
}

func (x UserType) String() string {
	return proto.EnumName(UserType_name, int32(x))
}

func (x *UserType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(UserType_value, data, "UserType")
	if err != nil {
		return err
	}
	*x = UserType(value)
	return nil
}

func (UserType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0b36f03a999007c1, []int{0}
}

type ServerType int32

const (
	ServerType_OPERATION ServerType = 1
	ServerType_SHUTOFF   ServerType = 2
)

var ServerType_name = map[int32]string{
	1: "OPERATION",
	2: "SHUTOFF",
}

var ServerType_value = map[string]int32{
	"OPERATION": 1,
	"SHUTOFF":   2,
}

func (x ServerType) Enum() *ServerType {
	p := new(ServerType)
	*p = x
	return p
}

func (x ServerType) String() string {
	return proto.EnumName(ServerType_name, int32(x))
}

func (x *ServerType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ServerType_value, data, "ServerType")
	if err != nil {
		return err
	}
	*x = ServerType(value)
	return nil
}

func (ServerType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0b36f03a999007c1, []int{1}
}

type ServerListToS struct {
	UserID               *string  `protobuf:"bytes,1,req,name=userID" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerListToS) Reset()         { *m = ServerListToS{} }
func (m *ServerListToS) String() string { return proto.CompactTextString(m) }
func (*ServerListToS) ProtoMessage()    {}
func (*ServerListToS) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b36f03a999007c1, []int{0}
}

func (m *ServerListToS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerListToS.Unmarshal(m, b)
}
func (m *ServerListToS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerListToS.Marshal(b, m, deterministic)
}
func (m *ServerListToS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerListToS.Merge(m, src)
}
func (m *ServerListToS) XXX_Size() int {
	return xxx_messageInfo_ServerListToS.Size(m)
}
func (m *ServerListToS) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerListToS.DiscardUnknown(m)
}

var xxx_messageInfo_ServerListToS proto.InternalMessageInfo

func (m *ServerListToS) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

type ServerListToC struct {
	ServerList           []*Server `protobuf:"bytes,1,rep,name=serverList" json:"serverList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ServerListToC) Reset()         { *m = ServerListToC{} }
func (m *ServerListToC) String() string { return proto.CompactTextString(m) }
func (*ServerListToC) ProtoMessage()    {}
func (*ServerListToC) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b36f03a999007c1, []int{1}
}

func (m *ServerListToC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerListToC.Unmarshal(m, b)
}
func (m *ServerListToC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerListToC.Marshal(b, m, deterministic)
}
func (m *ServerListToC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerListToC.Merge(m, src)
}
func (m *ServerListToC) XXX_Size() int {
	return xxx_messageInfo_ServerListToC.Size(m)
}
func (m *ServerListToC) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerListToC.DiscardUnknown(m)
}

var xxx_messageInfo_ServerListToC proto.InternalMessageInfo

func (m *ServerListToC) GetServerList() []*Server {
	if m != nil {
		return m.ServerList
	}
	return nil
}

type Server struct {
	UserType             *UserType   `protobuf:"varint,1,req,name=userType,enum=message.UserType" json:"userType,omitempty"`
	ServerType           *ServerType `protobuf:"varint,2,req,name=serverType,enum=message.ServerType" json:"serverType,omitempty"`
	ServerId             *int32      `protobuf:"varint,3,req,name=serverId" json:"serverId,omitempty"`
	ServerName           *string     `protobuf:"bytes,4,req,name=serverName" json:"serverName,omitempty"`
	ServerAddr           *string     `protobuf:"bytes,5,req,name=serverAddr" json:"serverAddr,omitempty"`
	PlayerNum            *int32      `protobuf:"varint,6,req,name=playerNum" json:"playerNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Server) Reset()         { *m = Server{} }
func (m *Server) String() string { return proto.CompactTextString(m) }
func (*Server) ProtoMessage()    {}
func (*Server) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b36f03a999007c1, []int{2}
}

func (m *Server) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Server.Unmarshal(m, b)
}
func (m *Server) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Server.Marshal(b, m, deterministic)
}
func (m *Server) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Server.Merge(m, src)
}
func (m *Server) XXX_Size() int {
	return xxx_messageInfo_Server.Size(m)
}
func (m *Server) XXX_DiscardUnknown() {
	xxx_messageInfo_Server.DiscardUnknown(m)
}

var xxx_messageInfo_Server proto.InternalMessageInfo

func (m *Server) GetUserType() UserType {
	if m != nil && m.UserType != nil {
		return *m.UserType
	}
	return UserType_NONE
}

func (m *Server) GetServerType() ServerType {
	if m != nil && m.ServerType != nil {
		return *m.ServerType
	}
	return ServerType_OPERATION
}

func (m *Server) GetServerId() int32 {
	if m != nil && m.ServerId != nil {
		return *m.ServerId
	}
	return 0
}

func (m *Server) GetServerName() string {
	if m != nil && m.ServerName != nil {
		return *m.ServerName
	}
	return ""
}

func (m *Server) GetServerAddr() string {
	if m != nil && m.ServerAddr != nil {
		return *m.ServerAddr
	}
	return ""
}

func (m *Server) GetPlayerNum() int32 {
	if m != nil && m.PlayerNum != nil {
		return *m.PlayerNum
	}
	return 0
}

func init() {
	proto.RegisterEnum("message.UserType", UserType_name, UserType_value)
	proto.RegisterEnum("message.ServerType", ServerType_name, ServerType_value)
	proto.RegisterType((*ServerListToS)(nil), "message.serverList_toS")
	proto.RegisterType((*ServerListToC)(nil), "message.serverList_toC")
	proto.RegisterType((*Server)(nil), "message.Server")
}

func init() { proto.RegisterFile("cs/proto/message/serverList.proto", fileDescriptor_0b36f03a999007c1) }

var fileDescriptor_0b36f03a999007c1 = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xdd, 0x4a, 0xc3, 0x40,
	0x10, 0x85, 0x4d, 0xfa, 0x97, 0x4e, 0xb1, 0xc6, 0x11, 0x64, 0x11, 0x91, 0x18, 0xbc, 0x08, 0x05,
	0x1b, 0xa8, 0x4f, 0x10, 0xb5, 0xd5, 0x40, 0xd9, 0x48, 0x92, 0xde, 0x78, 0x53, 0x42, 0xbb, 0x68,
	0xa0, 0x31, 0x61, 0x37, 0x15, 0xfa, 0xc2, 0x3e, 0x87, 0x74, 0xf3, 0x4b, 0x2f, 0xe7, 0x7c, 0xe7,
	0x9c, 0xd9, 0x65, 0xe0, 0x7e, 0x23, 0xec, 0x8c, 0xa7, 0x79, 0x6a, 0x27, 0x4c, 0x88, 0xe8, 0x8b,
	0xd9, 0x82, 0xf1, 0x5f, 0xc6, 0x97, 0xb1, 0xc8, 0xa7, 0x12, 0xe0, 0xa0, 0x24, 0xa6, 0x05, 0xe3,
	0x06, 0xae, 0xf3, 0x34, 0xc0, 0x6b, 0xe8, 0xef, 0x05, 0xe3, 0xee, 0x2b, 0x51, 0x0c, 0xd5, 0x1a,
	0xfa, 0xe5, 0x64, 0x3a, 0x27, 0xce, 0x17, 0xb4, 0x01, 0x1a, 0x85, 0x28, 0x46, 0xc7, 0x1a, 0xcd,
	0x2e, 0xa6, 0x65, 0xf3, 0x34, 0x90, 0xc8, 0x6f, 0x59, 0xcc, 0x3f, 0x05, 0xfa, 0x85, 0x8c, 0x8f,
	0xa0, 0x1d, 0x7b, 0xc3, 0x43, 0xc6, 0xe4, 0x9e, 0xf1, 0xec, 0xb2, 0x4e, 0xae, 0x4a, 0xe0, 0xd7,
	0x16, 0x7c, 0xaa, 0x56, 0xc9, 0x80, 0x2a, 0x03, 0x57, 0x27, 0xab, 0x64, 0xa4, 0x65, 0xc3, 0x1b,
	0xd0, 0x8a, 0xc9, 0xdd, 0x92, 0x8e, 0xa1, 0x5a, 0x3d, 0xbf, 0x9e, 0xf1, 0xae, 0x2a, 0xa4, 0x51,
	0xc2, 0x48, 0x57, 0xfe, 0xb4, 0xa5, 0x34, 0xdc, 0xd9, 0x6e, 0x39, 0xe9, 0xb5, 0xf9, 0x51, 0xc1,
	0x5b, 0x18, 0x66, 0xbb, 0xe8, 0xc0, 0x38, 0xdd, 0x27, 0xa4, 0x2f, 0xcb, 0x1b, 0x61, 0xf2, 0x00,
	0x5a, 0xf5, 0x09, 0xd4, 0xa0, 0x4b, 0x3d, 0x3a, 0xd7, 0xcf, 0x70, 0x0c, 0xb0, 0x74, 0x82, 0x70,
	0xbd, 0xf4, 0xde, 0x5c, 0xaa, 0x2b, 0x13, 0x0b, 0xa0, 0x79, 0x39, 0x9e, 0xc3, 0xd0, 0xfb, 0x98,
	0xfb, 0x4e, 0xe8, 0x7a, 0x54, 0x57, 0x70, 0x04, 0x83, 0xe0, 0x7d, 0x15, 0x7a, 0x8b, 0x85, 0xae,
	0x3e, 0x9b, 0x9f, 0x46, 0xfc, 0x13, 0xe7, 0x71, 0xb4, 0xcb, 0xbf, 0x39, 0x63, 0xc5, 0x75, 0x37,
	0xe9, 0xce, 0xde, 0x88, 0xea, 0xc6, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x70, 0x71, 0xbd, 0x9d,
	0xf6, 0x01, 0x00, 0x00,
}
