// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs/proto/message/shopBuy.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ShopBuyToS struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Count                *int32   `protobuf:"varint,2,req,name=count" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShopBuyToS) Reset()         { *m = ShopBuyToS{} }
func (m *ShopBuyToS) String() string { return proto.CompactTextString(m) }
func (*ShopBuyToS) ProtoMessage()    {}
func (*ShopBuyToS) Descriptor() ([]byte, []int) {
	return fileDescriptor_71027df1ef784c78, []int{0}
}

func (m *ShopBuyToS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopBuyToS.Unmarshal(m, b)
}
func (m *ShopBuyToS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopBuyToS.Marshal(b, m, deterministic)
}
func (m *ShopBuyToS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopBuyToS.Merge(m, src)
}
func (m *ShopBuyToS) XXX_Size() int {
	return xxx_messageInfo_ShopBuyToS.Size(m)
}
func (m *ShopBuyToS) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopBuyToS.DiscardUnknown(m)
}

var xxx_messageInfo_ShopBuyToS proto.InternalMessageInfo

func (m *ShopBuyToS) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *ShopBuyToS) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

type ShopBuyToC struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShopBuyToC) Reset()         { *m = ShopBuyToC{} }
func (m *ShopBuyToC) String() string { return proto.CompactTextString(m) }
func (*ShopBuyToC) ProtoMessage()    {}
func (*ShopBuyToC) Descriptor() ([]byte, []int) {
	return fileDescriptor_71027df1ef784c78, []int{1}
}

func (m *ShopBuyToC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopBuyToC.Unmarshal(m, b)
}
func (m *ShopBuyToC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopBuyToC.Marshal(b, m, deterministic)
}
func (m *ShopBuyToC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopBuyToC.Merge(m, src)
}
func (m *ShopBuyToC) XXX_Size() int {
	return xxx_messageInfo_ShopBuyToC.Size(m)
}
func (m *ShopBuyToC) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopBuyToC.DiscardUnknown(m)
}

var xxx_messageInfo_ShopBuyToC proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ShopBuyToS)(nil), "message.shopBuy_toS")
	proto.RegisterType((*ShopBuyToC)(nil), "message.shopBuy_toC")
}

func init() { proto.RegisterFile("cs/proto/message/shopBuy.proto", fileDescriptor_71027df1ef784c78) }

var fileDescriptor_71027df1ef784c78 = []byte{
	// 129 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4b, 0x2e, 0xd6, 0x2f,
	0x28, 0xca, 0x2f, 0xc9, 0xd7, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2f, 0xce, 0xc8,
	0x2f, 0x70, 0x2a, 0xad, 0xd4, 0x03, 0x8b, 0x0a, 0xb1, 0x43, 0x85, 0x95, 0x8c, 0xb9, 0xb8, 0xa1,
	0x32, 0xf1, 0x25, 0xf9, 0xc1, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x4c, 0x1a,
	0xac, 0x41, 0x4c, 0x99, 0x29, 0x42, 0x22, 0x5c, 0xac, 0xc9, 0xf9, 0xa5, 0x79, 0x25, 0x12, 0x4c,
	0x60, 0x21, 0x08, 0x47, 0x89, 0x17, 0x59, 0x93, 0xb3, 0x93, 0x52, 0x94, 0x42, 0x66, 0x5e, 0x66,
	0x49, 0x66, 0x62, 0x4e, 0x49, 0x46, 0x51, 0x6a, 0x2a, 0xc4, 0xe2, 0xe4, 0xfc, 0x1c, 0xfd, 0xe4,
	0x62, 0x98, 0xf5, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6e, 0x0f, 0xcc, 0x03, 0x91, 0x00, 0x00,
	0x00,
}
