// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs/proto/message/signIn.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignInToS struct {
	Id                   *int32   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInToS) Reset()         { *m = SignInToS{} }
func (m *SignInToS) String() string { return proto.CompactTextString(m) }
func (*SignInToS) ProtoMessage()    {}
func (*SignInToS) Descriptor() ([]byte, []int) {
	return fileDescriptor_930ec94160d94bda, []int{0}
}

func (m *SignInToS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInToS.Unmarshal(m, b)
}
func (m *SignInToS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInToS.Marshal(b, m, deterministic)
}
func (m *SignInToS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInToS.Merge(m, src)
}
func (m *SignInToS) XXX_Size() int {
	return xxx_messageInfo_SignInToS.Size(m)
}
func (m *SignInToS) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInToS.DiscardUnknown(m)
}

var xxx_messageInfo_SignInToS proto.InternalMessageInfo

func (m *SignInToS) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type SignInToC struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInToC) Reset()         { *m = SignInToC{} }
func (m *SignInToC) String() string { return proto.CompactTextString(m) }
func (*SignInToC) ProtoMessage()    {}
func (*SignInToC) Descriptor() ([]byte, []int) {
	return fileDescriptor_930ec94160d94bda, []int{1}
}

func (m *SignInToC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInToC.Unmarshal(m, b)
}
func (m *SignInToC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInToC.Marshal(b, m, deterministic)
}
func (m *SignInToC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInToC.Merge(m, src)
}
func (m *SignInToC) XXX_Size() int {
	return xxx_messageInfo_SignInToC.Size(m)
}
func (m *SignInToC) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInToC.DiscardUnknown(m)
}

var xxx_messageInfo_SignInToC proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SignInToS)(nil), "message.signIn_toS")
	proto.RegisterType((*SignInToC)(nil), "message.signIn_toC")
}

func init() { proto.RegisterFile("cs/proto/message/signIn.proto", fileDescriptor_930ec94160d94bda) }

var fileDescriptor_930ec94160d94bda = []byte{
	// 113 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4d, 0x2e, 0xd6, 0x2f,
	0x28, 0xca, 0x2f, 0xc9, 0xd7, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2f, 0xce, 0x4c,
	0xcf, 0xf3, 0xcc, 0xd3, 0x03, 0x0b, 0x0a, 0xb1, 0x43, 0x45, 0x95, 0x64, 0xb8, 0xb8, 0x20, 0x12,
	0xf1, 0x25, 0xf9, 0xc1, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xac,
	0x41, 0x4c, 0x99, 0x29, 0x4a, 0x3c, 0x48, 0xb2, 0xce, 0x4e, 0x4a, 0x51, 0x0a, 0x99, 0x79, 0x99,
	0x25, 0x99, 0x89, 0x39, 0x25, 0x19, 0x45, 0xa9, 0xa9, 0x10, 0xf3, 0x93, 0xf3, 0x73, 0xf4, 0x93,
	0x8b, 0x61, 0xb6, 0x00, 0x02, 0x00, 0x00, 0xff, 0xff, 0xbf, 0xe5, 0xbe, 0x58, 0x78, 0x00, 0x00,
	0x00,
}
