// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs/proto/message/teachNone.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TeachNoneToS struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeachNoneToS) Reset()         { *m = TeachNoneToS{} }
func (m *TeachNoneToS) String() string { return proto.CompactTextString(m) }
func (*TeachNoneToS) ProtoMessage()    {}
func (*TeachNoneToS) Descriptor() ([]byte, []int) {
	return fileDescriptor_8366adea9e00e849, []int{0}
}

func (m *TeachNoneToS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeachNoneToS.Unmarshal(m, b)
}
func (m *TeachNoneToS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeachNoneToS.Marshal(b, m, deterministic)
}
func (m *TeachNoneToS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeachNoneToS.Merge(m, src)
}
func (m *TeachNoneToS) XXX_Size() int {
	return xxx_messageInfo_TeachNoneToS.Size(m)
}
func (m *TeachNoneToS) XXX_DiscardUnknown() {
	xxx_messageInfo_TeachNoneToS.DiscardUnknown(m)
}

var xxx_messageInfo_TeachNoneToS proto.InternalMessageInfo

type TeachNoneToC struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeachNoneToC) Reset()         { *m = TeachNoneToC{} }
func (m *TeachNoneToC) String() string { return proto.CompactTextString(m) }
func (*TeachNoneToC) ProtoMessage()    {}
func (*TeachNoneToC) Descriptor() ([]byte, []int) {
	return fileDescriptor_8366adea9e00e849, []int{1}
}

func (m *TeachNoneToC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeachNoneToC.Unmarshal(m, b)
}
func (m *TeachNoneToC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeachNoneToC.Marshal(b, m, deterministic)
}
func (m *TeachNoneToC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeachNoneToC.Merge(m, src)
}
func (m *TeachNoneToC) XXX_Size() int {
	return xxx_messageInfo_TeachNoneToC.Size(m)
}
func (m *TeachNoneToC) XXX_DiscardUnknown() {
	xxx_messageInfo_TeachNoneToC.DiscardUnknown(m)
}

var xxx_messageInfo_TeachNoneToC proto.InternalMessageInfo

func init() {
	proto.RegisterType((*TeachNoneToS)(nil), "message.teachNone_toS")
	proto.RegisterType((*TeachNoneToC)(nil), "message.teachNone_toC")
}

func init() { proto.RegisterFile("cs/proto/message/teachNone.proto", fileDescriptor_8366adea9e00e849) }

var fileDescriptor_8366adea9e00e849 = []byte{
	// 98 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x48, 0x2e, 0xd6, 0x2f,
	0x28, 0xca, 0x2f, 0xc9, 0xd7, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2f, 0x49, 0x4d,
	0x4c, 0xce, 0xf0, 0xcb, 0xcf, 0x4b, 0xd5, 0x03, 0x8b, 0x0b, 0xb1, 0x43, 0x25, 0x94, 0xf8, 0xb9,
	0x78, 0xe1, 0x72, 0xf1, 0x25, 0xf9, 0xc1, 0xe8, 0x02, 0xce, 0x4e, 0x4a, 0x51, 0x0a, 0x99, 0x79,
	0x99, 0x25, 0x99, 0x89, 0x39, 0x25, 0x19, 0x45, 0xa9, 0xa9, 0x10, 0x83, 0x93, 0xf3, 0x73, 0xf4,
	0x93, 0x8b, 0x61, 0xc6, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x0b, 0x7c, 0x70, 0x71, 0x00,
	0x00, 0x00,
}
