// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs/proto/message/trialDungeonSync.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TrialDungeonSyncToS struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrialDungeonSyncToS) Reset()         { *m = TrialDungeonSyncToS{} }
func (m *TrialDungeonSyncToS) String() string { return proto.CompactTextString(m) }
func (*TrialDungeonSyncToS) ProtoMessage()    {}
func (*TrialDungeonSyncToS) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b029c587e561965, []int{0}
}

func (m *TrialDungeonSyncToS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrialDungeonSyncToS.Unmarshal(m, b)
}
func (m *TrialDungeonSyncToS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrialDungeonSyncToS.Marshal(b, m, deterministic)
}
func (m *TrialDungeonSyncToS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrialDungeonSyncToS.Merge(m, src)
}
func (m *TrialDungeonSyncToS) XXX_Size() int {
	return xxx_messageInfo_TrialDungeonSyncToS.Size(m)
}
func (m *TrialDungeonSyncToS) XXX_DiscardUnknown() {
	xxx_messageInfo_TrialDungeonSyncToS.DiscardUnknown(m)
}

var xxx_messageInfo_TrialDungeonSyncToS proto.InternalMessageInfo

type TrialDungeonSyncToC struct {
	All                  *bool               `protobuf:"varint,1,opt,name=all" json:"all,omitempty"`
	TrialDungeons        []*TrialDungeon     `protobuf:"bytes,2,rep,name=trialDungeons" json:"trialDungeons,omitempty"`
	TrailCount           *int32              `protobuf:"varint,3,opt,name=trailCount" json:"trailCount,omitempty"`
	StageReward          []*TrialStageReward `protobuf:"bytes,4,rep,name=stageReward" json:"stageReward,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *TrialDungeonSyncToC) Reset()         { *m = TrialDungeonSyncToC{} }
func (m *TrialDungeonSyncToC) String() string { return proto.CompactTextString(m) }
func (*TrialDungeonSyncToC) ProtoMessage()    {}
func (*TrialDungeonSyncToC) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b029c587e561965, []int{1}
}

func (m *TrialDungeonSyncToC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrialDungeonSyncToC.Unmarshal(m, b)
}
func (m *TrialDungeonSyncToC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrialDungeonSyncToC.Marshal(b, m, deterministic)
}
func (m *TrialDungeonSyncToC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrialDungeonSyncToC.Merge(m, src)
}
func (m *TrialDungeonSyncToC) XXX_Size() int {
	return xxx_messageInfo_TrialDungeonSyncToC.Size(m)
}
func (m *TrialDungeonSyncToC) XXX_DiscardUnknown() {
	xxx_messageInfo_TrialDungeonSyncToC.DiscardUnknown(m)
}

var xxx_messageInfo_TrialDungeonSyncToC proto.InternalMessageInfo

func (m *TrialDungeonSyncToC) GetAll() bool {
	if m != nil && m.All != nil {
		return *m.All
	}
	return false
}

func (m *TrialDungeonSyncToC) GetTrialDungeons() []*TrialDungeon {
	if m != nil {
		return m.TrialDungeons
	}
	return nil
}

func (m *TrialDungeonSyncToC) GetTrailCount() int32 {
	if m != nil && m.TrailCount != nil {
		return *m.TrailCount
	}
	return 0
}

func (m *TrialDungeonSyncToC) GetStageReward() []*TrialStageReward {
	if m != nil {
		return m.StageReward
	}
	return nil
}

type TrialDungeon struct {
	DungeonID            *int32   `protobuf:"varint,1,opt,name=dungeonID" json:"dungeonID,omitempty"`
	GetReward            *bool    `protobuf:"varint,2,opt,name=getReward" json:"getReward,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrialDungeon) Reset()         { *m = TrialDungeon{} }
func (m *TrialDungeon) String() string { return proto.CompactTextString(m) }
func (*TrialDungeon) ProtoMessage()    {}
func (*TrialDungeon) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b029c587e561965, []int{2}
}

func (m *TrialDungeon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrialDungeon.Unmarshal(m, b)
}
func (m *TrialDungeon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrialDungeon.Marshal(b, m, deterministic)
}
func (m *TrialDungeon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrialDungeon.Merge(m, src)
}
func (m *TrialDungeon) XXX_Size() int {
	return xxx_messageInfo_TrialDungeon.Size(m)
}
func (m *TrialDungeon) XXX_DiscardUnknown() {
	xxx_messageInfo_TrialDungeon.DiscardUnknown(m)
}

var xxx_messageInfo_TrialDungeon proto.InternalMessageInfo

func (m *TrialDungeon) GetDungeonID() int32 {
	if m != nil && m.DungeonID != nil {
		return *m.DungeonID
	}
	return 0
}

func (m *TrialDungeon) GetGetReward() bool {
	if m != nil && m.GetReward != nil {
		return *m.GetReward
	}
	return false
}

type TrialStageReward struct {
	Stage                *int32   `protobuf:"varint,1,opt,name=stage" json:"stage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrialStageReward) Reset()         { *m = TrialStageReward{} }
func (m *TrialStageReward) String() string { return proto.CompactTextString(m) }
func (*TrialStageReward) ProtoMessage()    {}
func (*TrialStageReward) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b029c587e561965, []int{3}
}

func (m *TrialStageReward) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrialStageReward.Unmarshal(m, b)
}
func (m *TrialStageReward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrialStageReward.Marshal(b, m, deterministic)
}
func (m *TrialStageReward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrialStageReward.Merge(m, src)
}
func (m *TrialStageReward) XXX_Size() int {
	return xxx_messageInfo_TrialStageReward.Size(m)
}
func (m *TrialStageReward) XXX_DiscardUnknown() {
	xxx_messageInfo_TrialStageReward.DiscardUnknown(m)
}

var xxx_messageInfo_TrialStageReward proto.InternalMessageInfo

func (m *TrialStageReward) GetStage() int32 {
	if m != nil && m.Stage != nil {
		return *m.Stage
	}
	return 0
}

func init() {
	proto.RegisterType((*TrialDungeonSyncToS)(nil), "message.trialDungeonSync_toS")
	proto.RegisterType((*TrialDungeonSyncToC)(nil), "message.trialDungeonSync_toC")
	proto.RegisterType((*TrialDungeon)(nil), "message.trialDungeon")
	proto.RegisterType((*TrialStageReward)(nil), "message.trialStageReward")
}

func init() {
	proto.RegisterFile("cs/proto/message/trialDungeonSync.proto", fileDescriptor_5b029c587e561965)
}

var fileDescriptor_5b029c587e561965 = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x49, 0x63, 0x50, 0xa7, 0x0a, 0x65, 0xa9, 0x12, 0x41, 0x24, 0xec, 0xc5, 0x9c, 0x12,
	0xf0, 0xda, 0x9b, 0xed, 0x45, 0x8f, 0x9b, 0x9b, 0x17, 0x59, 0xd2, 0x21, 0x2e, 0xac, 0xbb, 0xb2,
	0x3b, 0x45, 0xfc, 0x7b, 0xfe, 0x32, 0xe9, 0x66, 0x25, 0xdb, 0xd2, 0xdb, 0xcc, 0x7b, 0x8f, 0xf7,
	0x31, 0x0c, 0x3c, 0xf6, 0xbe, 0xfd, 0x72, 0x96, 0x6c, 0xfb, 0x89, 0xde, 0xcb, 0x01, 0x5b, 0x72,
	0x4a, 0xea, 0xcd, 0xce, 0x0c, 0x68, 0x4d, 0xf7, 0x63, 0xfa, 0x26, 0xd8, 0xec, 0x3c, 0xfa, 0xfc,
	0x16, 0x96, 0xc7, 0x91, 0x77, 0xb2, 0x1d, 0xff, 0xcd, 0x4e, 0x1a, 0x6b, 0xb6, 0x80, 0x5c, 0x6a,
	0x5d, 0x66, 0x55, 0x56, 0x5f, 0x88, 0xfd, 0xc8, 0x56, 0x70, 0x9d, 0x26, 0x7d, 0x39, 0xab, 0xf2,
	0x7a, 0xfe, 0x74, 0xd3, 0x44, 0x46, 0x93, 0xba, 0xe2, 0x30, 0xcb, 0x1e, 0x00, 0xc8, 0x49, 0xa5,
	0xd7, 0x76, 0x67, 0xa8, 0xcc, 0xab, 0xac, 0x2e, 0x44, 0xa2, 0xb0, 0x15, 0xcc, 0x3d, 0xc9, 0x01,
	0x05, 0x7e, 0x4b, 0xb7, 0x2d, 0xcf, 0x42, 0xf5, 0xdd, 0x61, 0x75, 0x37, 0x05, 0x44, 0x9a, 0xe6,
	0xaf, 0x70, 0x95, 0xd2, 0xd8, 0x3d, 0x5c, 0x6e, 0xc7, 0xf1, 0x65, 0x13, 0x2e, 0x28, 0xc4, 0x24,
	0xec, 0xdd, 0x01, 0x29, 0x82, 0x66, 0xe1, 0xbe, 0x49, 0xe0, 0x35, 0x2c, 0x8e, 0x61, 0x6c, 0x09,
	0x45, 0xc0, 0xc5, 0xae, 0x71, 0x79, 0xe6, 0x6f, 0x95, 0x32, 0x8a, 0x94, 0xd4, 0xf4, 0xe1, 0x10,
	0xc7, 0x87, 0xf4, 0x56, 0xb7, 0xbd, 0xff, 0x7f, 0xcb, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x36,
	0x39, 0x3c, 0xf3, 0xa9, 0x01, 0x00, 0x00,
}
