// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs/proto/message/updatePos.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpdatePosToS struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePosToS) Reset()         { *m = UpdatePosToS{} }
func (m *UpdatePosToS) String() string { return proto.CompactTextString(m) }
func (*UpdatePosToS) ProtoMessage()    {}
func (*UpdatePosToS) Descriptor() ([]byte, []int) {
	return fileDescriptor_bec299f3bd3f6396, []int{0}
}

func (m *UpdatePosToS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePosToS.Unmarshal(m, b)
}
func (m *UpdatePosToS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePosToS.Marshal(b, m, deterministic)
}
func (m *UpdatePosToS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePosToS.Merge(m, src)
}
func (m *UpdatePosToS) XXX_Size() int {
	return xxx_messageInfo_UpdatePosToS.Size(m)
}
func (m *UpdatePosToS) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePosToS.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePosToS proto.InternalMessageInfo

type UpdateObj struct {
	RoleID               *uint64   `protobuf:"varint,1,opt,name=roleID" json:"roleID,omitempty"`
	Pos                  *Position `protobuf:"bytes,2,opt,name=pos" json:"pos,omitempty"`
	Angle                *int32    `protobuf:"varint,3,opt,name=angle" json:"angle,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateObj) Reset()         { *m = UpdateObj{} }
func (m *UpdateObj) String() string { return proto.CompactTextString(m) }
func (*UpdateObj) ProtoMessage()    {}
func (*UpdateObj) Descriptor() ([]byte, []int) {
	return fileDescriptor_bec299f3bd3f6396, []int{1}
}

func (m *UpdateObj) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateObj.Unmarshal(m, b)
}
func (m *UpdateObj) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateObj.Marshal(b, m, deterministic)
}
func (m *UpdateObj) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateObj.Merge(m, src)
}
func (m *UpdateObj) XXX_Size() int {
	return xxx_messageInfo_UpdateObj.Size(m)
}
func (m *UpdateObj) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateObj.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateObj proto.InternalMessageInfo

func (m *UpdateObj) GetRoleID() uint64 {
	if m != nil && m.RoleID != nil {
		return *m.RoleID
	}
	return 0
}

func (m *UpdateObj) GetPos() *Position {
	if m != nil {
		return m.Pos
	}
	return nil
}

func (m *UpdateObj) GetAngle() int32 {
	if m != nil && m.Angle != nil {
		return *m.Angle
	}
	return 0
}

type UpdatePosToC struct {
	Objs                 []*UpdateObj `protobuf:"bytes,1,rep,name=objs" json:"objs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpdatePosToC) Reset()         { *m = UpdatePosToC{} }
func (m *UpdatePosToC) String() string { return proto.CompactTextString(m) }
func (*UpdatePosToC) ProtoMessage()    {}
func (*UpdatePosToC) Descriptor() ([]byte, []int) {
	return fileDescriptor_bec299f3bd3f6396, []int{2}
}

func (m *UpdatePosToC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePosToC.Unmarshal(m, b)
}
func (m *UpdatePosToC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePosToC.Marshal(b, m, deterministic)
}
func (m *UpdatePosToC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePosToC.Merge(m, src)
}
func (m *UpdatePosToC) XXX_Size() int {
	return xxx_messageInfo_UpdatePosToC.Size(m)
}
func (m *UpdatePosToC) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePosToC.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePosToC proto.InternalMessageInfo

func (m *UpdatePosToC) GetObjs() []*UpdateObj {
	if m != nil {
		return m.Objs
	}
	return nil
}

func init() {
	proto.RegisterType((*UpdatePosToS)(nil), "message.updatePos_toS")
	proto.RegisterType((*UpdateObj)(nil), "message.updateObj")
	proto.RegisterType((*UpdatePosToC)(nil), "message.updatePos_toC")
}

func init() { proto.RegisterFile("cs/proto/message/updatePos.proto", fileDescriptor_bec299f3bd3f6396) }

var fileDescriptor_bec299f3bd3f6396 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0x41, 0x4b, 0xc4, 0x30,
	0x14, 0x84, 0x89, 0xdd, 0x55, 0xcc, 0x22, 0x62, 0x10, 0x09, 0x82, 0x10, 0x22, 0x48, 0x4e, 0x0d,
	0xec, 0xc5, 0xbb, 0x7a, 0xf1, 0x64, 0x89, 0x37, 0x0f, 0x4a, 0x1a, 0x43, 0x4d, 0x49, 0xf3, 0x4a,
	0x5f, 0xfc, 0xff, 0x62, 0x53, 0x0b, 0xb2, 0xc7, 0x99, 0x6f, 0x32, 0x79, 0x43, 0x85, 0x43, 0x3d,
	0x4e, 0x90, 0x41, 0x0f, 0x1e, 0xd1, 0x76, 0x5e, 0x7f, 0x8f, 0x9f, 0x36, 0xfb, 0x06, 0xb0, 0x9e,
	0x7d, 0x76, 0xb2, 0x80, 0xeb, 0x9b, 0x83, 0xa8, 0x83, 0x61, 0x80, 0x54, 0x72, 0xf2, 0x9c, 0x9e,
	0xad, 0x4f, 0x3f, 0x32, 0xbc, 0xca, 0x77, 0x7a, 0x5a, 0x8c, 0x97, 0xb6, 0x67, 0x57, 0xf4, 0x78,
	0x82, 0xe8, 0x9f, 0x9f, 0x38, 0x11, 0x44, 0x6d, 0xcc, 0xa2, 0xd8, 0x2d, 0xad, 0x46, 0x40, 0x7e,
	0x24, 0x88, 0xda, 0xed, 0x2f, 0xea, 0xa5, 0xb9, 0x6e, 0x00, 0x43, 0x0e, 0x90, 0xcc, 0x2f, 0x65,
	0x97, 0x74, 0x6b, 0x53, 0x17, 0x3d, 0xaf, 0x04, 0x51, 0x5b, 0x53, 0x84, 0xbc, 0xff, 0xff, 0xe1,
	0x23, 0xbb, 0xa3, 0x1b, 0x68, 0x7b, 0xe4, 0x44, 0x54, 0x6a, 0xb7, 0x67, 0x6b, 0xd9, 0x7a, 0x85,
	0x99, 0xf9, 0x83, 0x7c, 0x13, 0x21, 0x85, 0x1c, 0x6c, 0xcc, 0x5f, 0x93, 0xf7, 0x65, 0x94, 0x83,
	0xa8, 0x1d, 0xfe, 0x4d, 0xfb, 0x09, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x6a, 0x12, 0x63, 0x18, 0x01,
	0x00, 0x00,
}
