// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs/proto/message/weaponStrengthen.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WeaponStrengthenToS struct {
	WeaponID             *uint32     `protobuf:"varint,1,req,name=weaponID" json:"weaponID,omitempty"`
	CostWeaponIDs        []uint32    `protobuf:"varint,2,rep,name=costWeaponIDs" json:"costWeaponIDs,omitempty"`
	CostItems            []*CostItem `protobuf:"bytes,3,rep,name=costItems" json:"costItems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *WeaponStrengthenToS) Reset()         { *m = WeaponStrengthenToS{} }
func (m *WeaponStrengthenToS) String() string { return proto.CompactTextString(m) }
func (*WeaponStrengthenToS) ProtoMessage()    {}
func (*WeaponStrengthenToS) Descriptor() ([]byte, []int) {
	return fileDescriptor_0529ee41b378e7cc, []int{0}
}

func (m *WeaponStrengthenToS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeaponStrengthenToS.Unmarshal(m, b)
}
func (m *WeaponStrengthenToS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeaponStrengthenToS.Marshal(b, m, deterministic)
}
func (m *WeaponStrengthenToS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeaponStrengthenToS.Merge(m, src)
}
func (m *WeaponStrengthenToS) XXX_Size() int {
	return xxx_messageInfo_WeaponStrengthenToS.Size(m)
}
func (m *WeaponStrengthenToS) XXX_DiscardUnknown() {
	xxx_messageInfo_WeaponStrengthenToS.DiscardUnknown(m)
}

var xxx_messageInfo_WeaponStrengthenToS proto.InternalMessageInfo

func (m *WeaponStrengthenToS) GetWeaponID() uint32 {
	if m != nil && m.WeaponID != nil {
		return *m.WeaponID
	}
	return 0
}

func (m *WeaponStrengthenToS) GetCostWeaponIDs() []uint32 {
	if m != nil {
		return m.CostWeaponIDs
	}
	return nil
}

func (m *WeaponStrengthenToS) GetCostItems() []*CostItem {
	if m != nil {
		return m.CostItems
	}
	return nil
}

type WeaponStrengthenToC struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WeaponStrengthenToC) Reset()         { *m = WeaponStrengthenToC{} }
func (m *WeaponStrengthenToC) String() string { return proto.CompactTextString(m) }
func (*WeaponStrengthenToC) ProtoMessage()    {}
func (*WeaponStrengthenToC) Descriptor() ([]byte, []int) {
	return fileDescriptor_0529ee41b378e7cc, []int{1}
}

func (m *WeaponStrengthenToC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeaponStrengthenToC.Unmarshal(m, b)
}
func (m *WeaponStrengthenToC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeaponStrengthenToC.Marshal(b, m, deterministic)
}
func (m *WeaponStrengthenToC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeaponStrengthenToC.Merge(m, src)
}
func (m *WeaponStrengthenToC) XXX_Size() int {
	return xxx_messageInfo_WeaponStrengthenToC.Size(m)
}
func (m *WeaponStrengthenToC) XXX_DiscardUnknown() {
	xxx_messageInfo_WeaponStrengthenToC.DiscardUnknown(m)
}

var xxx_messageInfo_WeaponStrengthenToC proto.InternalMessageInfo

func init() {
	proto.RegisterType((*WeaponStrengthenToS)(nil), "message.weaponStrengthen_toS")
	proto.RegisterType((*WeaponStrengthenToC)(nil), "message.weaponStrengthen_toC")
}

func init() {
	proto.RegisterFile("cs/proto/message/weaponStrengthen.proto", fileDescriptor_0529ee41b378e7cc)
}

var fileDescriptor_0529ee41b378e7cc = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4f, 0x2e, 0xd6, 0x2f,
	0x28, 0xca, 0x2f, 0xc9, 0xd7, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2f, 0x4f, 0x4d,
	0x2c, 0xc8, 0xcf, 0x0b, 0x2e, 0x29, 0x4a, 0xcd, 0x4b, 0x2f, 0xc9, 0x48, 0xcd, 0xd3, 0x03, 0x4b,
	0x0b, 0xb1, 0x43, 0xe5, 0xa5, 0x64, 0x31, 0x74, 0x24, 0xe7, 0xe7, 0xe6, 0xe6, 0x43, 0xd5, 0x29,
	0x75, 0x32, 0x72, 0x89, 0xa0, 0x1b, 0x11, 0x5f, 0x92, 0x1f, 0x2c, 0x24, 0xc5, 0xc5, 0x01, 0x11,
	0xf7, 0x74, 0x91, 0x60, 0x54, 0x60, 0xd2, 0xe0, 0x0d, 0x82, 0xf3, 0x85, 0x54, 0xb8, 0x78, 0x93,
	0xf3, 0x8b, 0x4b, 0xc2, 0xa1, 0xfc, 0x62, 0x09, 0x26, 0x05, 0x66, 0x0d, 0xde, 0x20, 0x54, 0x41,
	0x21, 0x7d, 0x2e, 0x4e, 0x90, 0x80, 0x67, 0x49, 0x6a, 0x6e, 0xb1, 0x04, 0xb3, 0x02, 0xb3, 0x06,
	0xb7, 0x91, 0xa0, 0x1e, 0xd4, 0x11, 0x7a, 0xce, 0x50, 0x99, 0x20, 0x84, 0x1a, 0x25, 0x31, 0xac,
	0x4e, 0x71, 0x76, 0x52, 0x8a, 0x52, 0xc8, 0xcc, 0xcb, 0x2c, 0xc9, 0x4c, 0xcc, 0x29, 0xc9, 0x28,
	0x4a, 0x4d, 0x85, 0x78, 0x27, 0x39, 0x3f, 0x47, 0x3f, 0xb9, 0x18, 0xe6, 0x29, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x43, 0x3c, 0x38, 0x18, 0x19, 0x01, 0x00, 0x00,
}
