// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs/proto/message/worldQuestSync.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WorldQuestSyncToS struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorldQuestSyncToS) Reset()         { *m = WorldQuestSyncToS{} }
func (m *WorldQuestSyncToS) String() string { return proto.CompactTextString(m) }
func (*WorldQuestSyncToS) ProtoMessage()    {}
func (*WorldQuestSyncToS) Descriptor() ([]byte, []int) {
	return fileDescriptor_08dc89ee7f39f35d, []int{0}
}

func (m *WorldQuestSyncToS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorldQuestSyncToS.Unmarshal(m, b)
}
func (m *WorldQuestSyncToS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorldQuestSyncToS.Marshal(b, m, deterministic)
}
func (m *WorldQuestSyncToS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorldQuestSyncToS.Merge(m, src)
}
func (m *WorldQuestSyncToS) XXX_Size() int {
	return xxx_messageInfo_WorldQuestSyncToS.Size(m)
}
func (m *WorldQuestSyncToS) XXX_DiscardUnknown() {
	xxx_messageInfo_WorldQuestSyncToS.DiscardUnknown(m)
}

var xxx_messageInfo_WorldQuestSyncToS proto.InternalMessageInfo

type WorldQuestSyncToC struct {
	IsAll                *bool         `protobuf:"varint,1,req,name=isAll" json:"isAll,omitempty"`
	WorldQuests          []*WorldQuest `protobuf:"bytes,2,rep,name=worldQuests" json:"worldQuests,omitempty"`
	RefreshTimes         *int32        `protobuf:"varint,3,opt,name=refreshTimes" json:"refreshTimes,omitempty"`
	DoneTimes            *int32        `protobuf:"varint,4,opt,name=doneTimes" json:"doneTimes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *WorldQuestSyncToC) Reset()         { *m = WorldQuestSyncToC{} }
func (m *WorldQuestSyncToC) String() string { return proto.CompactTextString(m) }
func (*WorldQuestSyncToC) ProtoMessage()    {}
func (*WorldQuestSyncToC) Descriptor() ([]byte, []int) {
	return fileDescriptor_08dc89ee7f39f35d, []int{1}
}

func (m *WorldQuestSyncToC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorldQuestSyncToC.Unmarshal(m, b)
}
func (m *WorldQuestSyncToC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorldQuestSyncToC.Marshal(b, m, deterministic)
}
func (m *WorldQuestSyncToC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorldQuestSyncToC.Merge(m, src)
}
func (m *WorldQuestSyncToC) XXX_Size() int {
	return xxx_messageInfo_WorldQuestSyncToC.Size(m)
}
func (m *WorldQuestSyncToC) XXX_DiscardUnknown() {
	xxx_messageInfo_WorldQuestSyncToC.DiscardUnknown(m)
}

var xxx_messageInfo_WorldQuestSyncToC proto.InternalMessageInfo

func (m *WorldQuestSyncToC) GetIsAll() bool {
	if m != nil && m.IsAll != nil {
		return *m.IsAll
	}
	return false
}

func (m *WorldQuestSyncToC) GetWorldQuests() []*WorldQuest {
	if m != nil {
		return m.WorldQuests
	}
	return nil
}

func (m *WorldQuestSyncToC) GetRefreshTimes() int32 {
	if m != nil && m.RefreshTimes != nil {
		return *m.RefreshTimes
	}
	return 0
}

func (m *WorldQuestSyncToC) GetDoneTimes() int32 {
	if m != nil && m.DoneTimes != nil {
		return *m.DoneTimes
	}
	return 0
}

type WorldQuest struct {
	QuestID              *int32   `protobuf:"varint,1,opt,name=questID" json:"questID,omitempty"`
	Done                 *bool    `protobuf:"varint,2,opt,name=done" json:"done,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorldQuest) Reset()         { *m = WorldQuest{} }
func (m *WorldQuest) String() string { return proto.CompactTextString(m) }
func (*WorldQuest) ProtoMessage()    {}
func (*WorldQuest) Descriptor() ([]byte, []int) {
	return fileDescriptor_08dc89ee7f39f35d, []int{2}
}

func (m *WorldQuest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorldQuest.Unmarshal(m, b)
}
func (m *WorldQuest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorldQuest.Marshal(b, m, deterministic)
}
func (m *WorldQuest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorldQuest.Merge(m, src)
}
func (m *WorldQuest) XXX_Size() int {
	return xxx_messageInfo_WorldQuest.Size(m)
}
func (m *WorldQuest) XXX_DiscardUnknown() {
	xxx_messageInfo_WorldQuest.DiscardUnknown(m)
}

var xxx_messageInfo_WorldQuest proto.InternalMessageInfo

func (m *WorldQuest) GetQuestID() int32 {
	if m != nil && m.QuestID != nil {
		return *m.QuestID
	}
	return 0
}

func (m *WorldQuest) GetDone() bool {
	if m != nil && m.Done != nil {
		return *m.Done
	}
	return false
}

func init() {
	proto.RegisterType((*WorldQuestSyncToS)(nil), "message.worldQuestSync_toS")
	proto.RegisterType((*WorldQuestSyncToC)(nil), "message.worldQuestSync_toC")
	proto.RegisterType((*WorldQuest)(nil), "message.worldQuest")
}

func init() {
	proto.RegisterFile("cs/proto/message/worldQuestSync.proto", fileDescriptor_08dc89ee7f39f35d)
}

var fileDescriptor_08dc89ee7f39f35d = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4d, 0x2e, 0xd6, 0x2f,
	0x28, 0xca, 0x2f, 0xc9, 0xd7, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2f, 0xcf, 0x2f,
	0xca, 0x49, 0x09, 0x2c, 0x4d, 0x2d, 0x2e, 0x09, 0xae, 0xcc, 0x4b, 0xd6, 0x03, 0x4b, 0x0a, 0xb1,
	0x43, 0x65, 0x95, 0x44, 0xb8, 0x84, 0x50, 0x15, 0xc4, 0x97, 0xe4, 0x07, 0x2b, 0x2d, 0x66, 0xc4,
	0x22, 0xec, 0x2c, 0x24, 0xc2, 0xc5, 0x9a, 0x59, 0xec, 0x98, 0x93, 0x23, 0xc1, 0xa8, 0xc0, 0xa4,
	0xc1, 0x11, 0x04, 0xe1, 0x08, 0x99, 0x72, 0x71, 0x23, 0xd4, 0x16, 0x4b, 0x30, 0x29, 0x30, 0x6b,
	0x70, 0x1b, 0x09, 0xeb, 0x41, 0x6d, 0xd0, 0x43, 0xc8, 0x05, 0x21, 0xab, 0x13, 0x52, 0xe2, 0xe2,
	0x29, 0x4a, 0x4d, 0x2b, 0x4a, 0x2d, 0xce, 0x08, 0xc9, 0xcc, 0x4d, 0x2d, 0x96, 0x60, 0x56, 0x60,
	0xd4, 0x60, 0x0d, 0x42, 0x11, 0x13, 0x92, 0xe1, 0xe2, 0x4c, 0xc9, 0xcf, 0x4b, 0x85, 0x28, 0x60,
	0x01, 0x2b, 0x40, 0x08, 0x28, 0x59, 0x71, 0x71, 0x21, 0x0c, 0x14, 0x92, 0xe0, 0x62, 0x2f, 0x04,
	0x31, 0x3c, 0x5d, 0x24, 0x18, 0xc1, 0x2a, 0x61, 0x5c, 0x21, 0x21, 0x2e, 0x16, 0x90, 0x26, 0x09,
	0x26, 0x05, 0x46, 0x0d, 0x8e, 0x20, 0x30, 0xdb, 0x49, 0x29, 0x4a, 0x21, 0x33, 0x2f, 0xb3, 0x24,
	0x33, 0x31, 0xa7, 0x24, 0xa3, 0x28, 0x35, 0x15, 0x12, 0x66, 0xc9, 0xf9, 0x39, 0xfa, 0xc9, 0xc5,
	0xb0, 0x90, 0x03, 0x04, 0x00, 0x00, 0xff, 0xff, 0x40, 0xf2, 0x6a, 0xd4, 0x4c, 0x01, 0x00, 0x00,
}
